
//
//  Automatically generated by Kony
//
//  This is a generated file. Do not modify this file.
//  Copyright 2014 Kony Labs. All rights reserved.
//
#import "CallBack.h"
#import <QRPOC/ScanQRWrapperClass.h>
#import <AVFoundation/AVFoundation.h>
