#import <objc/runtime.h>
#import "allincludes.h"
#import <NFIUtility/CallbackSupport.h>
#import <NFIUtility/PointerSupport.h>
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#pragma clang diagnostic ignored "-Wnullability-completeness"
static void addProtocols()
{
}
static void registerCFunctions(JSContext* context)
{
}
static void registerEnumConstants(JSContext* context)
{
}
static void registerGlobalConstants(JSContext* context)
{
	void* p; p = NULL;
	p = (void*) &AVMetadataiTunesMetadataKeyConductor;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyConductor"] = AVMetadataiTunesMetadataKeyConductor;
	p = (void*) &AVMetadataCommonKeyTitle;
	if (p != NULL) context[@"AVMetadataCommonKeyTitle"] = AVMetadataCommonKeyTitle;
	p = (void*) &AVMetadataQuickTimeMetadataKeyCredits;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyCredits"] = AVMetadataQuickTimeMetadataKeyCredits;
	p = (void*) &AVMetadataID3MetadataKeyCopyright;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyCopyright"] = AVMetadataID3MetadataKeyCopyright;
	p = (void*) &AVMetadataCommonKeyArtist;
	if (p != NULL) context[@"AVMetadataCommonKeyArtist"] = AVMetadataCommonKeyArtist;
	p = (void*) &AVMetadataiTunesMetadataKeyBeatsPerMin;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyBeatsPerMin"] = AVMetadataiTunesMetadataKeyBeatsPerMin;
	p = (void*) &AVMetadataID3MetadataKeyPlaylistDelay;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyPlaylistDelay"] = AVMetadataID3MetadataKeyPlaylistDelay;
	p = (void*) &AVMetadataiTunesMetadataKeyDirector;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyDirector"] = AVMetadataiTunesMetadataKeyDirector;
	p = (void*) &AVMetadataiTunesMetadataKeyOnlineExtras;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyOnlineExtras"] = AVMetadataiTunesMetadataKeyOnlineExtras;
	p = (void*) &AVMetadataQuickTimeUserDataKeyChapter;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyChapter"] = AVMetadataQuickTimeUserDataKeyChapter;
	p = (void*) &AVMetadataCommonKeyLanguage;
	if (p != NULL) context[@"AVMetadataCommonKeyLanguage"] = AVMetadataCommonKeyLanguage;
	p = (void*) &AVMetadataiTunesMetadataKeyGrouping;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyGrouping"] = AVMetadataiTunesMetadataKeyGrouping;
	p = (void*) &AVMetadataiTunesMetadataKeyPublisher;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyPublisher"] = AVMetadataiTunesMetadataKeyPublisher;
	p = (void*) &AVMetadataID3MetadataKeyEqualization2;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyEqualization2"] = AVMetadataID3MetadataKeyEqualization2;
	p = (void*) &AVMetadataiTunesMetadataKeyThanks;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyThanks"] = AVMetadataiTunesMetadataKeyThanks;
	p = (void*) &AVMetadata3GPUserDataKeyRecordingYear;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyRecordingYear"] = AVMetadata3GPUserDataKeyRecordingYear;
	p = (void*) &AVMetadataCommonKeyIdentifier;
	if (p != NULL) context[@"AVMetadataCommonKeyIdentifier"] = AVMetadataCommonKeyIdentifier;
	p = (void*) &AVMetadataQuickTimeUserDataKeyFullName;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyFullName"] = AVMetadataQuickTimeUserDataKeyFullName;
	p = (void*) &AVMetadataID3MetadataKeySynchronizedTempoCodes;
	if (p != NULL) context[@"AVMetadataID3MetadataKeySynchronizedTempoCodes"] = AVMetadataID3MetadataKeySynchronizedTempoCodes;
	p = (void*) &AVMetadataQuickTimeUserDataKeyPhonogramRights;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyPhonogramRights"] = AVMetadataQuickTimeUserDataKeyPhonogramRights;
	p = (void*) &AVMetadataQuickTimeMetadataKeyDirectionFacing;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyDirectionFacing"] = AVMetadataQuickTimeMetadataKeyDirectionFacing;
	p = (void*) &AVMetadataCommonKeyMake;
	if (p != NULL) context[@"AVMetadataCommonKeyMake"] = AVMetadataCommonKeyMake;
	p = (void*) &AVMetadataQuickTimeUserDataKeySoftware;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeySoftware"] = AVMetadataQuickTimeUserDataKeySoftware;
	p = (void*) &AVMetadataID3MetadataKeyBand;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyBand"] = AVMetadataID3MetadataKeyBand;
	p = (void*) &AVMetadataiTunesMetadataKeyArtDirector;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyArtDirector"] = AVMetadataiTunesMetadataKeyArtDirector;
	p = (void*) &AVMetadataiTunesMetadataKeyAlbum;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyAlbum"] = AVMetadataiTunesMetadataKeyAlbum;
	p = (void*) &AVMetadataID3MetadataKeyCommercialInformation;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyCommercialInformation"] = AVMetadataID3MetadataKeyCommercialInformation;
	p = (void*) &AVMetadataQuickTimeMetadataKeyPerformer;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyPerformer"] = AVMetadataQuickTimeMetadataKeyPerformer;
	p = (void*) &AVMetadataQuickTimeMetadataKeyDirectionMotion;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyDirectionMotion"] = AVMetadataQuickTimeMetadataKeyDirectionMotion;
	p = (void*) &AVMetadataQuickTimeMetadataKeyLocationNote;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyLocationNote"] = AVMetadataQuickTimeMetadataKeyLocationNote;
	p = (void*) &AVMetadataQuickTimeMetadataKeyAccessibilityDescription;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyAccessibilityDescription"] = AVMetadataQuickTimeMetadataKeyAccessibilityDescription;
	p = (void*) &AVMetadataiTunesMetadataKeyComposer;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyComposer"] = AVMetadataiTunesMetadataKeyComposer;
	p = (void*) &AVMetadataIcyMetadataKeyStreamTitle;
	if (p != NULL) context[@"AVMetadataIcyMetadataKeyStreamTitle"] = AVMetadataIcyMetadataKeyStreamTitle;
	p = (void*) &AVMetadataiTunesMetadataKeyDescription;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyDescription"] = AVMetadataiTunesMetadataKeyDescription;
	p = (void*) &AVMetadataID3MetadataKeyOwnership;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOwnership"] = AVMetadataID3MetadataKeyOwnership;
	p = (void*) &AVMetadataQuickTimeUserDataKeyPerformers;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyPerformers"] = AVMetadataQuickTimeUserDataKeyPerformers;
	p = (void*) &AVMetadata3GPUserDataKeyThumbnail;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyThumbnail"] = AVMetadata3GPUserDataKeyThumbnail;
	p = (void*) &AVMetadataQuickTimeUserDataKeyDirector;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyDirector"] = AVMetadataQuickTimeUserDataKeyDirector;
	p = (void*) &AVMetadataID3MetadataKeyTrackNumber;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyTrackNumber"] = AVMetadataID3MetadataKeyTrackNumber;
	p = (void*) &AVMetadataID3MetadataKeyReleaseTime;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyReleaseTime"] = AVMetadataID3MetadataKeyReleaseTime;
	p = (void*) &AVMetadataID3MetadataKeyAttachedPicture;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyAttachedPicture"] = AVMetadataID3MetadataKeyAttachedPicture;
	p = (void*) &AVMetadataQuickTimeUserDataKeyOriginalArtist;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyOriginalArtist"] = AVMetadataQuickTimeUserDataKeyOriginalArtist;
	p = (void*) &AVMetadataID3MetadataKeyOfficialAudioSourceWebpage;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOfficialAudioSourceWebpage"] = AVMetadataID3MetadataKeyOfficialAudioSourceWebpage;
	p = (void*) &AVMetadataiTunesMetadataKeyCopyright;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyCopyright"] = AVMetadataiTunesMetadataKeyCopyright;
	p = (void*) &AVMetadataID3MetadataKeyTitleDescription;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyTitleDescription"] = AVMetadataID3MetadataKeyTitleDescription;
	p = (void*) &AVMetadataID3MetadataKeyPayment;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyPayment"] = AVMetadataID3MetadataKeyPayment;
	p = (void*) &AVMetadataID3MetadataKeyYear;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyYear"] = AVMetadataID3MetadataKeyYear;
	p = (void*) &AVMetadataQuickTimeUserDataKeyCreationDate;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyCreationDate"] = AVMetadataQuickTimeUserDataKeyCreationDate;
	p = (void*) &AVMetadataCommonKeyModel;
	if (p != NULL) context[@"AVMetadataCommonKeyModel"] = AVMetadataCommonKeyModel;
	p = (void*) &AVMetadataID3MetadataKeyCommerical;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyCommerical"] = AVMetadataID3MetadataKeyCommerical;
	p = (void*) &AVMetadataCommonKeyAccessibilityDescription;
	if (p != NULL) context[@"AVMetadataCommonKeyAccessibilityDescription"] = AVMetadataCommonKeyAccessibilityDescription;
	p = (void*) &AVMetadataISOUserDataKeyCopyright;
	if (p != NULL) context[@"AVMetadataISOUserDataKeyCopyright"] = AVMetadataISOUserDataKeyCopyright;
	p = (void*) &AVMetadataQuickTimeMetadataKeyiXML;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyiXML"] = AVMetadataQuickTimeMetadataKeyiXML;
	p = (void*) &AVMetadataQuickTimeUserDataKeyWriter;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyWriter"] = AVMetadataQuickTimeUserDataKeyWriter;
	p = (void*) &AVMetadataiTunesMetadataKeyEncodingTool;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyEncodingTool"] = AVMetadataiTunesMetadataKeyEncodingTool;
	p = (void*) &AVMetadataiTunesMetadataKeyReleaseDate;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyReleaseDate"] = AVMetadataiTunesMetadataKeyReleaseDate;
	p = (void*) &AVMetadataCommonKeyCreationDate;
	if (p != NULL) context[@"AVMetadataCommonKeyCreationDate"] = AVMetadataCommonKeyCreationDate;
	p = (void*) &AVMetadataID3MetadataKeyDate;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyDate"] = AVMetadataID3MetadataKeyDate;
	p = (void*) &AVMetadataID3MetadataKeyLink;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyLink"] = AVMetadataID3MetadataKeyLink;
	p = (void*) &AVMetadataID3MetadataKeyCommercial;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyCommercial"] = AVMetadataID3MetadataKeyCommercial;
	p = (void*) &AVMetadataID3MetadataKeyLanguage;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyLanguage"] = AVMetadataID3MetadataKeyLanguage;
	p = (void*) &AVMetadataID3MetadataKeyConductor;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyConductor"] = AVMetadataID3MetadataKeyConductor;
	p = (void*) &AVMetadataQuickTimeUserDataKeyOriginalSource;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyOriginalSource"] = AVMetadataQuickTimeUserDataKeyOriginalSource;
	p = (void*) &AVMetadataQuickTimeUserDataKeyProducer;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyProducer"] = AVMetadataQuickTimeUserDataKeyProducer;
	p = (void*) &AVMetadataFormatHLSMetadata;
	if (p != NULL) context[@"AVMetadataFormatHLSMetadata"] = AVMetadataFormatHLSMetadata;
	p = (void*) &AVMetadataQuickTimeMetadataKeyGenre;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyGenre"] = AVMetadataQuickTimeMetadataKeyGenre;
	p = (void*) &AVMetadataiTunesMetadataKeyCredits;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyCredits"] = AVMetadataiTunesMetadataKeyCredits;
	p = (void*) &AVMetadataISOUserDataKeyTaggedCharacteristic;
	if (p != NULL) context[@"AVMetadataISOUserDataKeyTaggedCharacteristic"] = AVMetadataISOUserDataKeyTaggedCharacteristic;
	p = (void*) &AVMetadataID3MetadataKeyOriginalAlbumTitle;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOriginalAlbumTitle"] = AVMetadataID3MetadataKeyOriginalAlbumTitle;
	p = (void*) &AVMetadata3GPUserDataKeyMediaRating;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyMediaRating"] = AVMetadata3GPUserDataKeyMediaRating;
	p = (void*) &AVMetadataFormatQuickTimeMetadata;
	if (p != NULL) context[@"AVMetadataFormatQuickTimeMetadata"] = AVMetadataFormatQuickTimeMetadata;
	p = (void*) &AVMetadataQuickTimeMetadataKeyDisplayName;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyDisplayName"] = AVMetadataQuickTimeMetadataKeyDisplayName;
	p = (void*) &AVMetadataID3MetadataKeyAudioEncryption;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyAudioEncryption"] = AVMetadataID3MetadataKeyAudioEncryption;
	p = (void*) &AVMetadata3GPUserDataKeyUserRating;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyUserRating"] = AVMetadata3GPUserDataKeyUserRating;
	p = (void*) &AVMetadataQuickTimeMetadataKeyEncodedBy;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyEncodedBy"] = AVMetadataQuickTimeMetadataKeyEncodedBy;
	p = (void*) &AVMetadataID3MetadataKeySeek;
	if (p != NULL) context[@"AVMetadataID3MetadataKeySeek"] = AVMetadataID3MetadataKeySeek;
	p = (void*) &AVMetadataQuickTimeUserDataKeyComposer;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyComposer"] = AVMetadataQuickTimeUserDataKeyComposer;
	p = (void*) &AVMetadataID3MetadataKeySignature;
	if (p != NULL) context[@"AVMetadataID3MetadataKeySignature"] = AVMetadataID3MetadataKeySignature;
	p = (void*) &AVMetadataQuickTimeMetadataKeyCameraFrameReadoutTime;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyCameraFrameReadoutTime"] = AVMetadataQuickTimeMetadataKeyCameraFrameReadoutTime;
	p = (void*) &AVMetadata3GPUserDataKeyTitle;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyTitle"] = AVMetadata3GPUserDataKeyTitle;
	p = (void*) &AVMetadataID3MetadataKeyOriginalFilename;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOriginalFilename"] = AVMetadataID3MetadataKeyOriginalFilename;
	p = (void*) &AVMetadataID3MetadataKeyEncodingTime;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyEncodingTime"] = AVMetadataID3MetadataKeyEncodingTime;
	p = (void*) &AVMetadataID3MetadataKeyInternetRadioStationName;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyInternetRadioStationName"] = AVMetadataID3MetadataKeyInternetRadioStationName;
	p = (void*) &AVMetadataCommonKeyAuthor;
	if (p != NULL) context[@"AVMetadataCommonKeyAuthor"] = AVMetadataCommonKeyAuthor;
	p = (void*) &AVMetadataCommonKeyCreator;
	if (p != NULL) context[@"AVMetadataCommonKeyCreator"] = AVMetadataCommonKeyCreator;
	p = (void*) &AVMetadataID3MetadataKeyOriginalReleaseYear;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOriginalReleaseYear"] = AVMetadataID3MetadataKeyOriginalReleaseYear;
	p = (void*) &AVMetadataQuickTimeMetadataKeyAuthor;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyAuthor"] = AVMetadataQuickTimeMetadataKeyAuthor;
	p = (void*) &AVMetadataiTunesMetadataKeyAppleID;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyAppleID"] = AVMetadataiTunesMetadataKeyAppleID;
	p = (void*) &AVMetadataQuickTimeUserDataKeyOriginalFormat;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyOriginalFormat"] = AVMetadataQuickTimeUserDataKeyOriginalFormat;
	p = (void*) &AVMetadataID3MetadataKeyPlayCounter;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyPlayCounter"] = AVMetadataID3MetadataKeyPlayCounter;
	p = (void*) &AVMetadataID3MetadataKeyGeneralEncapsulatedObject;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyGeneralEncapsulatedObject"] = AVMetadataID3MetadataKeyGeneralEncapsulatedObject;
	p = (void*) &AVMetadataiTunesMetadataKeyDiscNumber;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyDiscNumber"] = AVMetadataiTunesMetadataKeyDiscNumber;
	p = (void*) &AVMetadataID3MetadataKeyOriginalArtist;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOriginalArtist"] = AVMetadataID3MetadataKeyOriginalArtist;
	p = (void*) &AVMetadataID3MetadataKeyComments;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyComments"] = AVMetadataID3MetadataKeyComments;
	p = (void*) &AVMetadataiTunesMetadataKeyAuthor;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyAuthor"] = AVMetadataiTunesMetadataKeyAuthor;
	p = (void*) &AVMetadataID3MetadataKeySetSubtitle;
	if (p != NULL) context[@"AVMetadataID3MetadataKeySetSubtitle"] = AVMetadataID3MetadataKeySetSubtitle;
	p = (void*) &AVMetadataiTunesMetadataKeyArtistID;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyArtistID"] = AVMetadataiTunesMetadataKeyArtistID;
	p = (void*) &AVMetadataID3MetadataKeyReverb;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyReverb"] = AVMetadataID3MetadataKeyReverb;
	p = (void*) &AVMetadataQuickTimeUserDataKeyDisclaimer;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyDisclaimer"] = AVMetadataQuickTimeUserDataKeyDisclaimer;
	p = (void*) &AVMetadataiTunesMetadataKeyLyrics;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyLyrics"] = AVMetadataiTunesMetadataKeyLyrics;
	p = (void*) &AVMetadata3GPUserDataKeyGenre;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyGenre"] = AVMetadata3GPUserDataKeyGenre;
	p = (void*) &AVMetadataID3MetadataKeyUnsynchronizedLyric;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyUnsynchronizedLyric"] = AVMetadataID3MetadataKeyUnsynchronizedLyric;
	p = (void*) &AVMetadataQuickTimeMetadataKeySoftware;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeySoftware"] = AVMetadataQuickTimeMetadataKeySoftware;
	p = (void*) &AVMetadataIcyMetadataKeyStreamURL;
	if (p != NULL) context[@"AVMetadataIcyMetadataKeyStreamURL"] = AVMetadataIcyMetadataKeyStreamURL;
	p = (void*) &AVMetadataID3MetadataKeyRecommendedBufferSize;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyRecommendedBufferSize"] = AVMetadataID3MetadataKeyRecommendedBufferSize;
	p = (void*) &AVMetadataID3MetadataKeyGroupIdentifier;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyGroupIdentifier"] = AVMetadataID3MetadataKeyGroupIdentifier;
	p = (void*) &AVMetadataID3MetadataKeyOfficialPublisherWebpage;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOfficialPublisherWebpage"] = AVMetadataID3MetadataKeyOfficialPublisherWebpage;
	p = (void*) &AVMetadataID3MetadataKeyOriginalLyricist;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOriginalLyricist"] = AVMetadataID3MetadataKeyOriginalLyricist;
	p = (void*) &AVMetadataQuickTimeMetadataKeyPhonogramRights;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyPhonogramRights"] = AVMetadataQuickTimeMetadataKeyPhonogramRights;
	p = (void*) &AVMetadataQuickTimeUserDataKeyHostComputer;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyHostComputer"] = AVMetadataQuickTimeUserDataKeyHostComputer;
	p = (void*) &AVMetadataiTunesMetadataKeyRecordCompany;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyRecordCompany"] = AVMetadataiTunesMetadataKeyRecordCompany;
	p = (void*) &AVMetadataID3MetadataKeyEncryption;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyEncryption"] = AVMetadataID3MetadataKeyEncryption;
	p = (void*) &AVMetadataID3MetadataKeyRelativeVolumeAdjustment;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyRelativeVolumeAdjustment"] = AVMetadataID3MetadataKeyRelativeVolumeAdjustment;
	p = (void*) &AVMetadataID3MetadataKeyEncodedWith;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyEncodedWith"] = AVMetadataID3MetadataKeyEncodedWith;
	p = (void*) &AVMetadataQuickTimeMetadataKeyLocationName;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyLocationName"] = AVMetadataQuickTimeMetadataKeyLocationName;
	p = (void*) &AVMetadataQuickTimeUserDataKeyTaggedCharacteristic;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyTaggedCharacteristic"] = AVMetadataQuickTimeUserDataKeyTaggedCharacteristic;
	p = (void*) &AVMetadataCommonKeyCopyrights;
	if (p != NULL) context[@"AVMetadataCommonKeyCopyrights"] = AVMetadataCommonKeyCopyrights;
	p = (void*) &AVMetadataCommonKeyLastModifiedDate;
	if (p != NULL) context[@"AVMetadataCommonKeyLastModifiedDate"] = AVMetadataCommonKeyLastModifiedDate;
	p = (void*) &AVMetadata3GPUserDataKeyCopyright;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyCopyright"] = AVMetadata3GPUserDataKeyCopyright;
	p = (void*) &AVMetadataID3MetadataKeyModifiedBy;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyModifiedBy"] = AVMetadataID3MetadataKeyModifiedBy;
	p = (void*) &AVMetadataID3MetadataKeyPrivate;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyPrivate"] = AVMetadataID3MetadataKeyPrivate;
	p = (void*) &AVMetadataID3MetadataKeyMPEGLocationLookupTable;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyMPEGLocationLookupTable"] = AVMetadataID3MetadataKeyMPEGLocationLookupTable;
	p = (void*) &AVMetadataQuickTimeMetadataKeyComment;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyComment"] = AVMetadataQuickTimeMetadataKeyComment;
	p = (void*) &AVMetadataQuickTimeMetadataKeyCreationDate;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyCreationDate"] = AVMetadataQuickTimeMetadataKeyCreationDate;
	p = (void*) &AVMetadataiTunesMetadataKeySoundEngineer;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeySoundEngineer"] = AVMetadataiTunesMetadataKeySoundEngineer;
	p = (void*) &AVMetadataFormatID3Metadata;
	if (p != NULL) context[@"AVMetadataFormatID3Metadata"] = AVMetadataFormatID3Metadata;
	p = (void*) &AVMetadataiTunesMetadataKeyOriginalArtist;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyOriginalArtist"] = AVMetadataiTunesMetadataKeyOriginalArtist;
	p = (void*) &AVMetadataID3MetadataKeyLength;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyLength"] = AVMetadataID3MetadataKeyLength;
	p = (void*) &AVMetadataiTunesMetadataKeyTrackSubTitle;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyTrackSubTitle"] = AVMetadataiTunesMetadataKeyTrackSubTitle;
	p = (void*) &AVMetadataID3MetadataKeyMood;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyMood"] = AVMetadataID3MetadataKeyMood;
	p = (void*) &AVMetadataQuickTimeUserDataKeyTrackName;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyTrackName"] = AVMetadataQuickTimeUserDataKeyTrackName;
	p = (void*) &AVMetadataFormatQuickTimeUserData;
	if (p != NULL) context[@"AVMetadataFormatQuickTimeUserData"] = AVMetadataFormatQuickTimeUserData;
	p = (void*) &AVMetadataQuickTimeUserDataKeyInformation;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyInformation"] = AVMetadataQuickTimeUserDataKeyInformation;
	p = (void*) &AVMetadataQuickTimeMetadataKeyInformation;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyInformation"] = AVMetadataQuickTimeMetadataKeyInformation;
	p = (void*) &AVMetadataQuickTimeMetadataKeyArranger;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyArranger"] = AVMetadataQuickTimeMetadataKeyArranger;
	p = (void*) &AVMetadataQuickTimeUserDataKeyLocationISO6709;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyLocationISO6709"] = AVMetadataQuickTimeUserDataKeyLocationISO6709;
	p = (void*) &AVMetadataiTunesMetadataKeyCoverArt;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyCoverArt"] = AVMetadataiTunesMetadataKeyCoverArt;
	p = (void*) &AVMetadataiTunesMetadataKeyPerformer;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyPerformer"] = AVMetadataiTunesMetadataKeyPerformer;
	p = (void*) &AVMetadataiTunesMetadataKeyExecProducer;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyExecProducer"] = AVMetadataiTunesMetadataKeyExecProducer;
	p = (void*) &AVMetadataKeySpaceQuickTimeMetadata;
	if (p != NULL) context[@"AVMetadataKeySpaceQuickTimeMetadata"] = AVMetadataKeySpaceQuickTimeMetadata;
	p = (void*) &AVMetadataID3MetadataKeyProducedNotice;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyProducedNotice"] = AVMetadataID3MetadataKeyProducedNotice;
	p = (void*) &AVMetadataID3MetadataKeyTaggingTime;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyTaggingTime"] = AVMetadataID3MetadataKeyTaggingTime;
	p = (void*) &AVMetadataQuickTimeUserDataKeyCredits;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyCredits"] = AVMetadataQuickTimeUserDataKeyCredits;
	p = (void*) &AVMetadataiTunesMetadataKeyArtist;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyArtist"] = AVMetadataiTunesMetadataKeyArtist;
	p = (void*) &AVMetadata3GPUserDataKeyDescription;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyDescription"] = AVMetadata3GPUserDataKeyDescription;
	p = (void*) &AVMetadataQuickTimeUserDataKeyAlbum;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyAlbum"] = AVMetadataQuickTimeUserDataKeyAlbum;
	p = (void*) &AVMetadataQuickTimeUserDataKeySpecialPlaybackRequirements;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeySpecialPlaybackRequirements"] = AVMetadataQuickTimeUserDataKeySpecialPlaybackRequirements;
	p = (void*) &AVMetadataCommonKeyType;
	if (p != NULL) context[@"AVMetadataCommonKeyType"] = AVMetadataCommonKeyType;
	p = (void*) &AVMetadataiTunesMetadataKeyPlaylistID;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyPlaylistID"] = AVMetadataiTunesMetadataKeyPlaylistID;
	p = (void*) &AVMetadataKeySpaceCommon;
	if (p != NULL) context[@"AVMetadataKeySpaceCommon"] = AVMetadataKeySpaceCommon;
	p = (void*) &AVMetadataQuickTimeUserDataKeyAuthor;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyAuthor"] = AVMetadataQuickTimeUserDataKeyAuthor;
	p = (void*) &AVMetadataID3MetadataKeyEncodedBy;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyEncodedBy"] = AVMetadataID3MetadataKeyEncodedBy;
	p = (void*) &AVMetadata3GPUserDataKeyCollection;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyCollection"] = AVMetadata3GPUserDataKeyCollection;
	p = (void*) &AVMetadataID3MetadataKeyPublisher;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyPublisher"] = AVMetadataID3MetadataKeyPublisher;
	p = (void*) &AVMetadataQuickTimeMetadataKeyLocationISO6709;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyLocationISO6709"] = AVMetadataQuickTimeMetadataKeyLocationISO6709;
	p = (void*) &AVMetadataQuickTimeMetadataKeyLocationRole;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyLocationRole"] = AVMetadataQuickTimeMetadataKeyLocationRole;
	p = (void*) &AVMetadataiTunesMetadataKeyAcknowledgement;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyAcknowledgement"] = AVMetadataiTunesMetadataKeyAcknowledgement;
	p = (void*) &AVMetadataID3MetadataKeyContentGroupDescription;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyContentGroupDescription"] = AVMetadataID3MetadataKeyContentGroupDescription;
	p = (void*) &AVMetadataiTunesMetadataKeyEncodedBy;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyEncodedBy"] = AVMetadataiTunesMetadataKeyEncodedBy;
	p = (void*) &AVMetadataQuickTimeUserDataKeyArtist;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyArtist"] = AVMetadataQuickTimeUserDataKeyArtist;
	p = (void*) &AVMetadata3GPUserDataKeyKeywordList;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyKeywordList"] = AVMetadata3GPUserDataKeyKeywordList;
	p = (void*) &AVMetadataID3MetadataKeyPartOfASet;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyPartOfASet"] = AVMetadataID3MetadataKeyPartOfASet;
	p = (void*) &AVMetadataQuickTimeMetadataKeyDirector;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyDirector"] = AVMetadataQuickTimeMetadataKeyDirector;
	p = (void*) &AVMetadataQuickTimeUserDataKeyDescription;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyDescription"] = AVMetadataQuickTimeUserDataKeyDescription;
	p = (void*) &AVMetadataID3MetadataKeyOfficialInternetRadioStationHomepage;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOfficialInternetRadioStationHomepage"] = AVMetadataID3MetadataKeyOfficialInternetRadioStationHomepage;
	p = (void*) &AVMetadataID3MetadataKeyInvolvedPeopleList_v24;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyInvolvedPeopleList_v24"] = AVMetadataID3MetadataKeyInvolvedPeopleList_v24;
	p = (void*) &AVMetadataID3MetadataKeyInvolvedPeopleList_v23;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyInvolvedPeopleList_v23"] = AVMetadataID3MetadataKeyInvolvedPeopleList_v23;
	p = (void*) &AVMetadataQuickTimeMetadataKeyContentIdentifier;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyContentIdentifier"] = AVMetadataQuickTimeMetadataKeyContentIdentifier;
	p = (void*) &AVMetadataCommonKeyContributor;
	if (p != NULL) context[@"AVMetadataCommonKeyContributor"] = AVMetadataCommonKeyContributor;
	p = (void*) &AVMetadataKeySpaceHLSDateRange;
	if (p != NULL) context[@"AVMetadataKeySpaceHLSDateRange"] = AVMetadataKeySpaceHLSDateRange;
	p = (void*) &AVMetadataQuickTimeMetadataKeyMake;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyMake"] = AVMetadataQuickTimeMetadataKeyMake;
	p = (void*) &AVMetadataID3MetadataKeyInternationalStandardRecordingCode;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyInternationalStandardRecordingCode"] = AVMetadataID3MetadataKeyInternationalStandardRecordingCode;
	p = (void*) &AVMetadataKeySpaceISOUserData;
	if (p != NULL) context[@"AVMetadataKeySpaceISOUserData"] = AVMetadataKeySpaceISOUserData;
	p = (void*) &AVMetadataCommonKeySubject;
	if (p != NULL) context[@"AVMetadataCommonKeySubject"] = AVMetadataCommonKeySubject;
	p = (void*) &AVMetadataCommonKeyAlbumName;
	if (p != NULL) context[@"AVMetadataCommonKeyAlbumName"] = AVMetadataCommonKeyAlbumName;
	p = (void*) &AVMetadataKeySpaceQuickTimeUserData;
	if (p != NULL) context[@"AVMetadataKeySpaceQuickTimeUserData"] = AVMetadataKeySpaceQuickTimeUserData;
	p = (void*) &AVMetadataID3MetadataKeyPositionSynchronization;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyPositionSynchronization"] = AVMetadataID3MetadataKeyPositionSynchronization;
	p = (void*) &AVMetadataID3MetadataKeyContentType;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyContentType"] = AVMetadataID3MetadataKeyContentType;
	p = (void*) &AVMetadataQuickTimeUserDataKeyKeywords;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyKeywords"] = AVMetadataQuickTimeUserDataKeyKeywords;
	p = (void*) &AVMetadataID3MetadataKeyUserText;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyUserText"] = AVMetadataID3MetadataKeyUserText;
	p = (void*) &AVMetadataKeySpaceID3;
	if (p != NULL) context[@"AVMetadataKeySpaceID3"] = AVMetadataKeySpaceID3;
	p = (void*) &AVMetadataCommonKeyDescription;
	if (p != NULL) context[@"AVMetadataCommonKeyDescription"] = AVMetadataCommonKeyDescription;
	p = (void*) &AVMetadataQuickTimeUserDataKeyWarning;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyWarning"] = AVMetadataQuickTimeUserDataKeyWarning;
	p = (void*) &AVMetadataiTunesMetadataKeyAlbumArtist;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyAlbumArtist"] = AVMetadataiTunesMetadataKeyAlbumArtist;
	p = (void*) &AVMetadataiTunesMetadataKeySoloist;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeySoloist"] = AVMetadataiTunesMetadataKeySoloist;
	p = (void*) &AVMetadataCommonKeyPublisher;
	if (p != NULL) context[@"AVMetadataCommonKeyPublisher"] = AVMetadataCommonKeyPublisher;
	p = (void*) &AVMetadata3GPUserDataKeyPerformer;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyPerformer"] = AVMetadata3GPUserDataKeyPerformer;
	p = (void*) &AVMetadataQuickTimeMetadataKeyCopyright;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyCopyright"] = AVMetadataQuickTimeMetadataKeyCopyright;
	p = (void*) &AVMetadataID3MetadataKeySize;
	if (p != NULL) context[@"AVMetadataID3MetadataKeySize"] = AVMetadataID3MetadataKeySize;
	p = (void*) &AVMetadataID3MetadataKeyFileOwner;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyFileOwner"] = AVMetadataID3MetadataKeyFileOwner;
	p = (void*) &AVMetadataKeySpaceAudioFile;
	if (p != NULL) context[@"AVMetadataKeySpaceAudioFile"] = AVMetadataKeySpaceAudioFile;
	p = (void*) &AVMetadataISOUserDataKeyAccessibilityDescription;
	if (p != NULL) context[@"AVMetadataISOUserDataKeyAccessibilityDescription"] = AVMetadataISOUserDataKeyAccessibilityDescription;
	p = (void*) &AVMetadataQuickTimeUserDataKeyComment;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyComment"] = AVMetadataQuickTimeUserDataKeyComment;
	p = (void*) &AVMetadataID3MetadataKeyOfficialArtistWebpage;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOfficialArtistWebpage"] = AVMetadataID3MetadataKeyOfficialArtistWebpage;
	p = (void*) &AVMetadataID3MetadataKeyUniqueFileIdentifier;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyUniqueFileIdentifier"] = AVMetadataID3MetadataKeyUniqueFileIdentifier;
	p = (void*) &AVMetadataID3MetadataKeyLeadPerformer;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyLeadPerformer"] = AVMetadataID3MetadataKeyLeadPerformer;
	p = (void*) &AVMetadataQuickTimeMetadataKeyYear;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyYear"] = AVMetadataQuickTimeMetadataKeyYear;
	p = (void*) &AVMetadataID3MetadataKeyAlbumSortOrder;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyAlbumSortOrder"] = AVMetadataID3MetadataKeyAlbumSortOrder;
	p = (void*) &AVMetadataID3MetadataKeyOfficialAudioFileWebpage;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOfficialAudioFileWebpage"] = AVMetadataID3MetadataKeyOfficialAudioFileWebpage;
	p = (void*) &AVMetadataQuickTimeUserDataKeyCopyright;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyCopyright"] = AVMetadataQuickTimeUserDataKeyCopyright;
	p = (void*) &AVMetadataQuickTimeUserDataKeyURLLink;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyURLLink"] = AVMetadataQuickTimeUserDataKeyURLLink;
	p = (void*) &AVMetadataQuickTimeMetadataKeyComposer;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyComposer"] = AVMetadataQuickTimeMetadataKeyComposer;
	p = (void*) &AVMetadataiTunesMetadataKeyUserGenre;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyUserGenre"] = AVMetadataiTunesMetadataKeyUserGenre;
	p = (void*) &AVMetadataID3MetadataKeyPopularimeter;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyPopularimeter"] = AVMetadataID3MetadataKeyPopularimeter;
	p = (void*) &AVMetadataQuickTimeMetadataKeyArtist;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyArtist"] = AVMetadataQuickTimeMetadataKeyArtist;
	p = (void*) &AVMetadataFormatISOUserData;
	if (p != NULL) context[@"AVMetadataFormatISOUserData"] = AVMetadataFormatISOUserData;
	p = (void*) &AVMetadataQuickTimeMetadataKeyCameraIdentifier;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyCameraIdentifier"] = AVMetadataQuickTimeMetadataKeyCameraIdentifier;
	p = (void*) &AVMetadataCommonKeyRelation;
	if (p != NULL) context[@"AVMetadataCommonKeyRelation"] = AVMetadataCommonKeyRelation;
	p = (void*) &AVMetadataQuickTimeMetadataKeyProducer;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyProducer"] = AVMetadataQuickTimeMetadataKeyProducer;
	p = (void*) &AVMetadata3GPUserDataKeyAuthor;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyAuthor"] = AVMetadata3GPUserDataKeyAuthor;
	p = (void*) &AVMetadataExtraAttributeBaseURIKey;
	if (p != NULL) context[@"AVMetadataExtraAttributeBaseURIKey"] = AVMetadataExtraAttributeBaseURIKey;
	p = (void*) &AVMetadataKeySpaceIcy;
	if (p != NULL) context[@"AVMetadataKeySpaceIcy"] = AVMetadataKeySpaceIcy;
	p = (void*) &AVMetadataFormatUnknown;
	if (p != NULL) context[@"AVMetadataFormatUnknown"] = AVMetadataFormatUnknown;
	p = (void*) &AVMetadataQuickTimeUserDataKeyTrack;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyTrack"] = AVMetadataQuickTimeUserDataKeyTrack;
	p = (void*) &AVMetadataQuickTimeUserDataKeyPublisher;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyPublisher"] = AVMetadataQuickTimeUserDataKeyPublisher;
	p = (void*) &AVMetadataQuickTimeMetadataKeyKeywords;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyKeywords"] = AVMetadataQuickTimeMetadataKeyKeywords;
	p = (void*) &AVMetadataQuickTimeUserDataKeyEncodedBy;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyEncodedBy"] = AVMetadataQuickTimeUserDataKeyEncodedBy;
	p = (void*) &AVMetadataQuickTimeMetadataKeyArtwork;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyArtwork"] = AVMetadataQuickTimeMetadataKeyArtwork;
	p = (void*) &AVMetadataQuickTimeMetadataKeyPublisher;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyPublisher"] = AVMetadataQuickTimeMetadataKeyPublisher;
	p = (void*) &AVMetadataID3MetadataKeySynchronizedLyric;
	if (p != NULL) context[@"AVMetadataID3MetadataKeySynchronizedLyric"] = AVMetadataID3MetadataKeySynchronizedLyric;
	p = (void*) &AVMetadataID3MetadataKeyInitialKey;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyInitialKey"] = AVMetadataID3MetadataKeyInitialKey;
	p = (void*) &AVMetadataiTunesMetadataKeyTrackNumber;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyTrackNumber"] = AVMetadataiTunesMetadataKeyTrackNumber;
	p = (void*) &AVMetadata3GPUserDataKeyMediaClassification;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyMediaClassification"] = AVMetadata3GPUserDataKeyMediaClassification;
	p = (void*) &AVMetadataID3MetadataKeyRecordingTime;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyRecordingTime"] = AVMetadataID3MetadataKeyRecordingTime;
	p = (void*) &AVMetadataID3MetadataKeyComposer;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyComposer"] = AVMetadataID3MetadataKeyComposer;
	p = (void*) &AVMetadataExtraAttributeValueURIKey;
	if (p != NULL) context[@"AVMetadataExtraAttributeValueURIKey"] = AVMetadataExtraAttributeValueURIKey;
	p = (void*) &AVMetadataISOUserDataKeyDate;
	if (p != NULL) context[@"AVMetadataISOUserDataKeyDate"] = AVMetadataISOUserDataKeyDate;
	p = (void*) &AVMetadataiTunesMetadataKeyEQ;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyEQ"] = AVMetadataiTunesMetadataKeyEQ;
	p = (void*) &AVMetadataQuickTimeMetadataKeyAlbum;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyAlbum"] = AVMetadataQuickTimeMetadataKeyAlbum;
	p = (void*) &AVMetadataID3MetadataKeyAlbumTitle;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyAlbumTitle"] = AVMetadataID3MetadataKeyAlbumTitle;
	p = (void*) &AVMetadataID3MetadataKeyMediaType;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyMediaType"] = AVMetadataID3MetadataKeyMediaType;
	p = (void*) &AVMetadataiTunesMetadataKeyUserComment;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyUserComment"] = AVMetadataiTunesMetadataKeyUserComment;
	p = (void*) &AVMetadataQuickTimeMetadataKeyRatingUser;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyRatingUser"] = AVMetadataQuickTimeMetadataKeyRatingUser;
	p = (void*) &AVMetadataID3MetadataKeyAudioSeekPointIndex;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyAudioSeekPointIndex"] = AVMetadataID3MetadataKeyAudioSeekPointIndex;
	p = (void*) &AVMetadataiTunesMetadataKeyAccountKind;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyAccountKind"] = AVMetadataiTunesMetadataKeyAccountKind;
	p = (void*) &AVMetadataID3MetadataKeyEqualization;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyEqualization"] = AVMetadataID3MetadataKeyEqualization;
	p = (void*) &AVMetadataExtraAttributeInfoKey;
	if (p != NULL) context[@"AVMetadataExtraAttributeInfoKey"] = AVMetadataExtraAttributeInfoKey;
	p = (void*) &AVMetadataQuickTimeUserDataKeyProduct;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyProduct"] = AVMetadataQuickTimeUserDataKeyProduct;
	p = (void*) &AVMetadataQuickTimeUserDataKeyAccessibilityDescription;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyAccessibilityDescription"] = AVMetadataQuickTimeUserDataKeyAccessibilityDescription;
	p = (void*) &AVMetadataID3MetadataKeyEventTimingCodes;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyEventTimingCodes"] = AVMetadataID3MetadataKeyEventTimingCodes;
	p = (void*) &AVMetadataQuickTimeMetadataKeyCollectionUser;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyCollectionUser"] = AVMetadataQuickTimeMetadataKeyCollectionUser;
	p = (void*) &AVMetadataID3MetadataKeyTermsOfUse;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyTermsOfUse"] = AVMetadataID3MetadataKeyTermsOfUse;
	p = (void*) &AVMetadataiTunesMetadataKeyContentRating;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyContentRating"] = AVMetadataiTunesMetadataKeyContentRating;
	p = (void*) &AVMetadataCommonKeySource;
	if (p != NULL) context[@"AVMetadataCommonKeySource"] = AVMetadataCommonKeySource;
	p = (void*) &AVMetadataCommonKeyFormat;
	if (p != NULL) context[@"AVMetadataCommonKeyFormat"] = AVMetadataCommonKeyFormat;
	p = (void*) &AVMetadataID3MetadataKeyMusicianCreditsList;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyMusicianCreditsList"] = AVMetadataID3MetadataKeyMusicianCreditsList;
	p = (void*) &AVMetadataQuickTimeUserDataKeyArranger;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyArranger"] = AVMetadataQuickTimeUserDataKeyArranger;
	p = (void*) &AVMetadataCommonKeyArtwork;
	if (p != NULL) context[@"AVMetadataCommonKeyArtwork"] = AVMetadataCommonKeyArtwork;
	p = (void*) &AVMetadataiTunesMetadataKeyPredefinedGenre;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyPredefinedGenre"] = AVMetadataiTunesMetadataKeyPredefinedGenre;
	p = (void*) &AVMetadata3GPUserDataKeyAlbumAndTrack;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyAlbumAndTrack"] = AVMetadata3GPUserDataKeyAlbumAndTrack;
	p = (void*) &AVMetadataID3MetadataKeyBeatsPerMinute;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyBeatsPerMinute"] = AVMetadataID3MetadataKeyBeatsPerMinute;
	p = (void*) &AVMetadataiTunesMetadataKeyGenreID;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyGenreID"] = AVMetadataiTunesMetadataKeyGenreID;
	p = (void*) &AVMetadataQuickTimeUserDataKeyMake;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyMake"] = AVMetadataQuickTimeUserDataKeyMake;
	p = (void*) &AVMetadataCommonKeyLocation;
	if (p != NULL) context[@"AVMetadataCommonKeyLocation"] = AVMetadataCommonKeyLocation;
	p = (void*) &AVMetadataFormatiTunesMetadata;
	if (p != NULL) context[@"AVMetadataFormatiTunesMetadata"] = AVMetadataFormatiTunesMetadata;
	p = (void*) &AVMetadataID3MetadataKeyRecordingDates;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyRecordingDates"] = AVMetadataID3MetadataKeyRecordingDates;
	p = (void*) &AVMetadataID3MetadataKeyPerformerSortOrder;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyPerformerSortOrder"] = AVMetadataID3MetadataKeyPerformerSortOrder;
	p = (void*) &AVMetadataQuickTimeMetadataKeyOriginalArtist;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyOriginalArtist"] = AVMetadataQuickTimeMetadataKeyOriginalArtist;
	p = (void*) &AVMetadataID3MetadataKeyRelativeVolumeAdjustment2;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyRelativeVolumeAdjustment2"] = AVMetadataID3MetadataKeyRelativeVolumeAdjustment2;
	p = (void*) &AVMetadataQuickTimeMetadataKeyLocationDate;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyLocationDate"] = AVMetadataQuickTimeMetadataKeyLocationDate;
	p = (void*) &AVMetadataQuickTimeMetadataKeyModel;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyModel"] = AVMetadataQuickTimeMetadataKeyModel;
	p = (void*) &AVMetadataID3MetadataKeyTitleSortOrder;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyTitleSortOrder"] = AVMetadataID3MetadataKeyTitleSortOrder;
	p = (void*) &AVMetadataiTunesMetadataKeyProducer;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyProducer"] = AVMetadataiTunesMetadataKeyProducer;
	p = (void*) &AVMetadataID3MetadataKeyInternetRadioStationOwner;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyInternetRadioStationOwner"] = AVMetadataID3MetadataKeyInternetRadioStationOwner;
	p = (void*) &AVMetadataID3MetadataKeyUserURL;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyUserURL"] = AVMetadataID3MetadataKeyUserURL;
	p = (void*) &AVMetadataID3MetadataKeyCopyrightInformation;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyCopyrightInformation"] = AVMetadataID3MetadataKeyCopyrightInformation;
	p = (void*) &AVMetadataID3MetadataKeyOriginalReleaseTime;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyOriginalReleaseTime"] = AVMetadataID3MetadataKeyOriginalReleaseTime;
	p = (void*) &AVMetadataID3MetadataKeyFileType;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyFileType"] = AVMetadataID3MetadataKeyFileType;
	p = (void*) &AVMetadataQuickTimeMetadataKeyLocationBody;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyLocationBody"] = AVMetadataQuickTimeMetadataKeyLocationBody;
	p = (void*) &AVMetadataiTunesMetadataKeySongID;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeySongID"] = AVMetadataiTunesMetadataKeySongID;
	p = (void*) &AVMetadataQuickTimeMetadataKeyDescription;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyDescription"] = AVMetadataQuickTimeMetadataKeyDescription;
	p = (void*) &AVMetadataiTunesMetadataKeyDiscCompilation;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyDiscCompilation"] = AVMetadataiTunesMetadataKeyDiscCompilation;
	p = (void*) &AVMetadataQuickTimeMetadataKeyTitle;
	if (p != NULL) context[@"AVMetadataQuickTimeMetadataKeyTitle"] = AVMetadataQuickTimeMetadataKeyTitle;
	p = (void*) &AVMetadataKeySpaceiTunes;
	if (p != NULL) context[@"AVMetadataKeySpaceiTunes"] = AVMetadataKeySpaceiTunes;
	p = (void*) &AVMetadataiTunesMetadataKeySongName;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeySongName"] = AVMetadataiTunesMetadataKeySongName;
	p = (void*) &AVMetadataiTunesMetadataKeyPhonogramRights;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyPhonogramRights"] = AVMetadataiTunesMetadataKeyPhonogramRights;
	p = (void*) &AVMetadataiTunesMetadataKeyArranger;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyArranger"] = AVMetadataiTunesMetadataKeyArranger;
	p = (void*) &AVMetadataID3MetadataKeySubTitle;
	if (p != NULL) context[@"AVMetadataID3MetadataKeySubTitle"] = AVMetadataID3MetadataKeySubTitle;
	p = (void*) &AVMetadata3GPUserDataKeyLocation;
	if (p != NULL) context[@"AVMetadata3GPUserDataKeyLocation"] = AVMetadata3GPUserDataKeyLocation;
	p = (void*) &AVMetadataQuickTimeUserDataKeyModel;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyModel"] = AVMetadataQuickTimeUserDataKeyModel;
	p = (void*) &AVMetadataID3MetadataKeyMusicCDIdentifier;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyMusicCDIdentifier"] = AVMetadataID3MetadataKeyMusicCDIdentifier;
	p = (void*) &AVMetadataiTunesMetadataKeyLinerNotes;
	if (p != NULL) context[@"AVMetadataiTunesMetadataKeyLinerNotes"] = AVMetadataiTunesMetadataKeyLinerNotes;
	p = (void*) &AVMetadataQuickTimeUserDataKeyGenre;
	if (p != NULL) context[@"AVMetadataQuickTimeUserDataKeyGenre"] = AVMetadataQuickTimeUserDataKeyGenre;
	p = (void*) &AVMetadataCommonKeySoftware;
	if (p != NULL) context[@"AVMetadataCommonKeySoftware"] = AVMetadataCommonKeySoftware;
	p = (void*) &AVMetadataID3MetadataKeyLyricist;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyLyricist"] = AVMetadataID3MetadataKeyLyricist;
	p = (void*) &AVMetadataID3MetadataKeyTime;
	if (p != NULL) context[@"AVMetadataID3MetadataKeyTime"] = AVMetadataID3MetadataKeyTime;
}
void load_AVFoundation_AVMetadataFormat_symbols(JSContext* context)
{
    addProtocols();
    registerEnumConstants(context);
    registerCFunctions(context);
    registerGlobalConstants(context);
}
#pragma clang diagnostic pop
