//
//  konymacros.h
//  VM
//
//  Created by Amba on 17/06/11.
//  Copyright 2011 Kony Solutions. All rights reserved.
//

// Widget types used in KonyWrapper
typedef enum KONYWIDGETTYPE {
	KONY_NILWIDGET			,
	KONY_BASE_WIDGET		,
	KONY_BOX				,
	KONY_FORM				,
	KONY_LABEL				,
	KONY_TEXTFIELD			,
	KONY_TEXTAREA			,
	KONY_BUTTON				,
	KONY_LINKWIDGET			,
	KONY_ALERT				,
	KONY_CALENDAR			,
	KONY_IMAGE				,
	KONY_LINE				,
	KONY_IMAGEGALLERY		,
	KONY_IMAGESTRIP			,
	KONY_LISTBOX			,
	KONY_CHECKBOXGROUP		,
	KONY_RADIOBUTTONGROUP	,
	KONY_COMBOBOX			,
	KONY_CAMERA				,
	KONY_DS					,
	KONY_SEGEMETED_UI		,
	KONY_TAB                ,
	KONY_ADBAR				,
	KONY_COLLAPSIBLE_WIDGET,
	KONY_POPUP              ,
	KONY_DATA_GRID			,
	KONY_ONSCR_WHEEL_WIDGET ,
	KONY_ONSCR_SPLIT_WHEEL_WIDGET,
	KONY_SUI_PAGECONTROL,
	KONY_SLIDER,
	KONY_SWITCH,
	KONY_BROWSER,
	KONY_RICHTEXT,
	KONY_MAP,
	KONY_CHART,
	KONY_PHONE,
	KONY_SEGMENT,
	KONY_PICKERVIEW,
    KONY_SEARCHBAR,
    KONY_DVWIDGET,
    KONY_HYBRID_WIDGET,
    KONY_BAR_CHART
}	KONYWIDGETTYPE;


