// Generated by Kony Inc
// Don't modify the file or any of it's part/s
// Copyright Kony Inc. 2018

#import "NFIAllLoader.h"
#import <NFISecurity/NFISecurityLoader.h>
#import <NFICoreFoundation/NFICoreFoundationLoader.h>
#import <NFICFNetwork/NFICFNetworkLoader.h>
#import <NFIFoundation/NFIFoundationLoader.h>
#import <NFIKonySyncV2/NFIKonySyncV2Loader.h>
#import <NFIBinary/NFIBinaryLoader.h>
#import <NFISDKCommons/NFISDKCommonsLoader.h>

// loadAllModules stub
void loadAllModules(JSContext *context){
	loadNFISecurityModules(context);
	loadNFICoreFoundationModules(context);
	loadNFICFNetworkModules(context);
	loadNFIFoundationModules(context);
	loadNFIKonySyncV2Modules(context);
	loadNFIBinaryModules(context);
	loadNFISDKCommonsModules(context);
}

// extractStructArgument stub
JSValue* extractStructArgument(const char* type, NSInvocation* invocation, NSUInteger index, JSContext* context){
	if(extractNFISecurityStructArgument(type, invocation, index, context)){
		return extractNFISecurityStructArgument(type, invocation, index, context); 
	}
	else if(extractNFICoreFoundationStructArgument(type, invocation, index, context)){
		return extractNFICoreFoundationStructArgument(type, invocation, index, context); 
	}
	else if(extractNFICFNetworkStructArgument(type, invocation, index, context)){
		return extractNFICFNetworkStructArgument(type, invocation, index, context); 
	}
	else if(extractNFIFoundationStructArgument(type, invocation, index, context)){
		return extractNFIFoundationStructArgument(type, invocation, index, context); 
	}
	else if(extractNFIKonySyncV2StructArgument(type, invocation, index, context)){
		return extractNFIKonySyncV2StructArgument(type, invocation, index, context); 
	}
	else if(extractNFIBinaryStructArgument(type, invocation, index, context)){
		return extractNFIBinaryStructArgument(type, invocation, index, context); 
	}
	else if(extractNFISDKCommonsStructArgument(type, invocation, index, context)){
		return extractNFISDKCommonsStructArgument(type, invocation, index, context); 
	}
    return nil;
}

// setStructReturnValue stub
void setStructReturnValue(const char* type, JSValue* value, NSInvocation* invocation){
	if(setNFISecurityStructReturnValue(type, value, invocation)){
		return;
	}
	else if(setNFICoreFoundationStructReturnValue(type, value, invocation)){
		return;
	}
	else if(setNFICFNetworkStructReturnValue(type, value, invocation)){
		return;
	}
	else if(setNFIFoundationStructReturnValue(type, value, invocation)){
		return;
	}
	else if(setNFIKonySyncV2StructReturnValue(type, value, invocation)){
		return;
	}
	else if(setNFIBinaryStructReturnValue(type, value, invocation)){
		return;
	}
	else if(setNFISDKCommonsStructReturnValue(type, value, invocation)){
		return;
	}
}