#import <objc/runtime.h>
#import "allincludes.h"
#import <NFIUtility/CallbackSupport.h>
#import <NFIUtility/PointerSupport.h>
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#pragma clang diagnostic ignored "-Wnullability-completeness"
static void addProtocols()
{
}
static void registerCFunctions(JSContext* context)
{
}
static void registerEnumConstants(JSContext* context)
{
}
static void registerGlobalConstants(JSContext* context)
{
	void* p; p = NULL;
	p = (void*) &AVMetadataIdentifieriTunesMetadataPlaylistID;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataPlaylistID"] = AVMetadataIdentifieriTunesMetadataPlaylistID;
	p = (void*) &AVMetadataIdentifieriTunesMetadataPerformer;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataPerformer"] = AVMetadataIdentifieriTunesMetadataPerformer;
	p = (void*) &AVMetadataIdentifieriTunesMetadataRecordCompany;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataRecordCompany"] = AVMetadataIdentifieriTunesMetadataRecordCompany;
	p = (void*) &AVMetadataIdentifierID3MetadataOfficialPublisherWebpage;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOfficialPublisherWebpage"] = AVMetadataIdentifierID3MetadataOfficialPublisherWebpage;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataChapter;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataChapter"] = AVMetadataIdentifierQuickTimeUserDataChapter;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataCredits;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataCredits"] = AVMetadataIdentifierQuickTimeUserDataCredits;
	p = (void*) &AVMetadataIdentifierID3MetadataMusicCDIdentifier;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataMusicCDIdentifier"] = AVMetadataIdentifierID3MetadataMusicCDIdentifier;
	p = (void*) &AVMetadataIdentifierID3MetadataProducedNotice;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataProducedNotice"] = AVMetadataIdentifierID3MetadataProducedNotice;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataPublisher;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataPublisher"] = AVMetadataIdentifierQuickTimeMetadataPublisher;
	p = (void*) &AVMetadataIdentifierID3MetadataOfficialArtistWebpage;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOfficialArtistWebpage"] = AVMetadataIdentifierID3MetadataOfficialArtistWebpage;
	p = (void*) &AVMetadataIdentifierID3MetadataInternationalStandardRecordingCode;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataInternationalStandardRecordingCode"] = AVMetadataIdentifierID3MetadataInternationalStandardRecordingCode;
	p = (void*) &AVMetadataIdentifierID3MetadataTitleDescription;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataTitleDescription"] = AVMetadataIdentifierID3MetadataTitleDescription;
	p = (void*) &AVMetadataCommonIdentifierLastModifiedDate;
	if (p != NULL) context[@"AVMetadataCommonIdentifierLastModifiedDate"] = AVMetadataCommonIdentifierLastModifiedDate;
	p = (void*) &AVMetadataIdentifierID3MetadataAttachedPicture;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataAttachedPicture"] = AVMetadataIdentifierID3MetadataAttachedPicture;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataComment;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataComment"] = AVMetadataIdentifierQuickTimeMetadataComment;
	p = (void*) &AVMetadataIdentifierID3MetadataRecordingTime;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataRecordingTime"] = AVMetadataIdentifierID3MetadataRecordingTime;
	p = (void*) &AVMetadataIdentifierID3MetadataOriginalLyricist;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOriginalLyricist"] = AVMetadataIdentifierID3MetadataOriginalLyricist;
	p = (void*) &AVMetadataIdentifieriTunesMetadataArranger;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataArranger"] = AVMetadataIdentifieriTunesMetadataArranger;
	p = (void*) &AVMetadataIdentifieriTunesMetadataContentRating;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataContentRating"] = AVMetadataIdentifieriTunesMetadataContentRating;
	p = (void*) &AVMetadataIdentifierID3MetadataUserURL;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataUserURL"] = AVMetadataIdentifierID3MetadataUserURL;
	p = (void*) &AVMetadataIdentifierID3MetadataEqualization2;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataEqualization2"] = AVMetadataIdentifierID3MetadataEqualization2;
	p = (void*) &AVMetadataIdentifieriTunesMetadataCopyright;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataCopyright"] = AVMetadataIdentifieriTunesMetadataCopyright;
	p = (void*) &AVMetadataIdentifieriTunesMetadataGrouping;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataGrouping"] = AVMetadataIdentifieriTunesMetadataGrouping;
	p = (void*) &AVMetadataIdentifierID3MetadataCommercial;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataCommercial"] = AVMetadataIdentifierID3MetadataCommercial;
	p = (void*) &AVMetadataIdentifierID3MetadataConductor;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataConductor"] = AVMetadataIdentifierID3MetadataConductor;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataDisplayName;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataDisplayName"] = AVMetadataIdentifierQuickTimeMetadataDisplayName;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataSoftware;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataSoftware"] = AVMetadataIdentifierQuickTimeMetadataSoftware;
	p = (void*) &AVMetadataIdentifieriTunesMetadataArtDirector;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataArtDirector"] = AVMetadataIdentifieriTunesMetadataArtDirector;
	p = (void*) &AVMetadataCommonIdentifierAssetIdentifier;
	if (p != NULL) context[@"AVMetadataCommonIdentifierAssetIdentifier"] = AVMetadataCommonIdentifierAssetIdentifier;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataKeywords;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataKeywords"] = AVMetadataIdentifierQuickTimeMetadataKeywords;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataHostComputer;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataHostComputer"] = AVMetadataIdentifierQuickTimeUserDataHostComputer;
	p = (void*) &AVMetadataIdentifierID3MetadataReverb;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataReverb"] = AVMetadataIdentifierID3MetadataReverb;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataAuthor;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataAuthor"] = AVMetadataIdentifierQuickTimeUserDataAuthor;
	p = (void*) &AVMetadataIdentifier3GPUserDataKeywordList;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataKeywordList"] = AVMetadataIdentifier3GPUserDataKeywordList;
	p = (void*) &AVMetadataIdentifieriTunesMetadataEncodedBy;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataEncodedBy"] = AVMetadataIdentifieriTunesMetadataEncodedBy;
	p = (void*) &AVMetadataIdentifierID3MetadataComments;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataComments"] = AVMetadataIdentifierID3MetadataComments;
	p = (void*) &AVMetadataCommonIdentifierSource;
	if (p != NULL) context[@"AVMetadataCommonIdentifierSource"] = AVMetadataCommonIdentifierSource;
	p = (void*) &AVMetadataIdentifierID3MetadataPayment;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataPayment"] = AVMetadataIdentifierID3MetadataPayment;
	p = (void*) &AVMetadataIdentifierID3MetadataSynchronizedTempoCodes;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataSynchronizedTempoCodes"] = AVMetadataIdentifierID3MetadataSynchronizedTempoCodes;
	p = (void*) &AVMetadataIdentifieriTunesMetadataAcknowledgement;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataAcknowledgement"] = AVMetadataIdentifieriTunesMetadataAcknowledgement;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataDirector;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataDirector"] = AVMetadataIdentifierQuickTimeMetadataDirector;
	p = (void*) &AVMetadataIdentifierID3MetadataSynchronizedLyric;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataSynchronizedLyric"] = AVMetadataIdentifierID3MetadataSynchronizedLyric;
	p = (void*) &AVMetadataIdentifierID3MetadataAudioSeekPointIndex;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataAudioSeekPointIndex"] = AVMetadataIdentifierID3MetadataAudioSeekPointIndex;
	p = (void*) &AVMetadataIdentifierID3MetadataMPEGLocationLookupTable;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataMPEGLocationLookupTable"] = AVMetadataIdentifierID3MetadataMPEGLocationLookupTable;
	p = (void*) &AVMetadataIdentifierID3MetadataMood;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataMood"] = AVMetadataIdentifierID3MetadataMood;
	p = (void*) &AVMetadataIdentifieriTunesMetadataSongID;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataSongID"] = AVMetadataIdentifieriTunesMetadataSongID;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataArtist;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataArtist"] = AVMetadataIdentifierQuickTimeUserDataArtist;
	p = (void*) &AVMetadataIdentifierID3MetadataCopyright;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataCopyright"] = AVMetadataIdentifierID3MetadataCopyright;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataTaggedCharacteristic;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataTaggedCharacteristic"] = AVMetadataIdentifierQuickTimeUserDataTaggedCharacteristic;
	p = (void*) &AVMetadataIdentifieriTunesMetadataPredefinedGenre;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataPredefinedGenre"] = AVMetadataIdentifieriTunesMetadataPredefinedGenre;
	p = (void*) &AVMetadataIdentifieriTunesMetadataGenreID;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataGenreID"] = AVMetadataIdentifieriTunesMetadataGenreID;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataPreferredAffineTransform;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataPreferredAffineTransform"] = AVMetadataIdentifierQuickTimeMetadataPreferredAffineTransform;
	p = (void*) &AVMetadataIdentifierID3MetadataPositionSynchronization;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataPositionSynchronization"] = AVMetadataIdentifierID3MetadataPositionSynchronization;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataCreationDate;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataCreationDate"] = AVMetadataIdentifierQuickTimeMetadataCreationDate;
	p = (void*) &AVMetadataIdentifieriTunesMetadataUserGenre;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataUserGenre"] = AVMetadataIdentifieriTunesMetadataUserGenre;
	p = (void*) &AVMetadataIdentifierID3MetadataAudioEncryption;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataAudioEncryption"] = AVMetadataIdentifierID3MetadataAudioEncryption;
	p = (void*) &AVMetadataIdentifierID3MetadataPerformerSortOrder;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataPerformerSortOrder"] = AVMetadataIdentifierID3MetadataPerformerSortOrder;
	p = (void*) &AVMetadataIdentifieriTunesMetadataPhonogramRights;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataPhonogramRights"] = AVMetadataIdentifieriTunesMetadataPhonogramRights;
	p = (void*) &AVMetadataIdentifier3GPUserDataMediaRating;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataMediaRating"] = AVMetadataIdentifier3GPUserDataMediaRating;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataCredits;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataCredits"] = AVMetadataIdentifierQuickTimeMetadataCredits;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataWriter;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataWriter"] = AVMetadataIdentifierQuickTimeUserDataWriter;
	p = (void*) &AVMetadataIdentifierID3MetadataContentGroupDescription;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataContentGroupDescription"] = AVMetadataIdentifierID3MetadataContentGroupDescription;
	p = (void*) &AVMetadataIdentifierID3MetadataLink;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataLink"] = AVMetadataIdentifierID3MetadataLink;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataInformation;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataInformation"] = AVMetadataIdentifierQuickTimeMetadataInformation;
	p = (void*) &AVMetadataIdentifieriTunesMetadataArtistID;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataArtistID"] = AVMetadataIdentifieriTunesMetadataArtistID;
	p = (void*) &AVMetadataIdentifier3GPUserDataRecordingYear;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataRecordingYear"] = AVMetadataIdentifier3GPUserDataRecordingYear;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataMake;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataMake"] = AVMetadataIdentifierQuickTimeMetadataMake;
	p = (void*) &AVMetadataIdentifierID3MetadataModifiedBy;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataModifiedBy"] = AVMetadataIdentifierID3MetadataModifiedBy;
	p = (void*) &AVMetadataIdentifierID3MetadataSize;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataSize"] = AVMetadataIdentifierID3MetadataSize;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataEncodedBy;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataEncodedBy"] = AVMetadataIdentifierQuickTimeMetadataEncodedBy;
	p = (void*) &AVMetadataIdentifierID3MetadataInternetRadioStationName;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataInternetRadioStationName"] = AVMetadataIdentifierID3MetadataInternetRadioStationName;
	p = (void*) &AVMetadataIdentifieriTunesMetadataSongName;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataSongName"] = AVMetadataIdentifieriTunesMetadataSongName;
	p = (void*) &AVMetadataCommonIdentifierCreator;
	if (p != NULL) context[@"AVMetadataCommonIdentifierCreator"] = AVMetadataCommonIdentifierCreator;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataComment;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataComment"] = AVMetadataIdentifierQuickTimeUserDataComment;
	p = (void*) &AVMetadataIdentifieriTunesMetadataProducer;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataProducer"] = AVMetadataIdentifieriTunesMetadataProducer;
	p = (void*) &AVMetadataCommonIdentifierCopyrights;
	if (p != NULL) context[@"AVMetadataCommonIdentifierCopyrights"] = AVMetadataCommonIdentifierCopyrights;
	p = (void*) &AVMetadataIdentifieriTunesMetadataDiscNumber;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataDiscNumber"] = AVMetadataIdentifieriTunesMetadataDiscNumber;
	p = (void*) &AVMetadataIdentifierID3MetadataPlaylistDelay;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataPlaylistDelay"] = AVMetadataIdentifierID3MetadataPlaylistDelay;
	p = (void*) &AVMetadataIdentifieriTunesMetadataLyrics;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataLyrics"] = AVMetadataIdentifieriTunesMetadataLyrics;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataDescription;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataDescription"] = AVMetadataIdentifierQuickTimeMetadataDescription;
	p = (void*) &AVMetadataIdentifierID3MetadataRelativeVolumeAdjustment;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataRelativeVolumeAdjustment"] = AVMetadataIdentifierID3MetadataRelativeVolumeAdjustment;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataModel;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataModel"] = AVMetadataIdentifierQuickTimeUserDataModel;
	p = (void*) &AVMetadataIdentifieriTunesMetadataOnlineExtras;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataOnlineExtras"] = AVMetadataIdentifieriTunesMetadataOnlineExtras;
	p = (void*) &AVMetadataIdentifierISOUserDataTaggedCharacteristic;
	if (p != NULL) context[@"AVMetadataIdentifierISOUserDataTaggedCharacteristic"] = AVMetadataIdentifierISOUserDataTaggedCharacteristic;
	p = (void*) &AVMetadataIdentifier3GPUserDataTitle;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataTitle"] = AVMetadataIdentifier3GPUserDataTitle;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataArranger;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataArranger"] = AVMetadataIdentifierQuickTimeMetadataArranger;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataTitle;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataTitle"] = AVMetadataIdentifierQuickTimeMetadataTitle;
	p = (void*) &AVMetadataCommonIdentifierModel;
	if (p != NULL) context[@"AVMetadataCommonIdentifierModel"] = AVMetadataCommonIdentifierModel;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataOriginalArtist;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataOriginalArtist"] = AVMetadataIdentifierQuickTimeMetadataOriginalArtist;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataAlbum;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataAlbum"] = AVMetadataIdentifierQuickTimeMetadataAlbum;
	p = (void*) &AVMetadataIdentifierID3MetadataFileOwner;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataFileOwner"] = AVMetadataIdentifierID3MetadataFileOwner;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataOriginalArtist;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataOriginalArtist"] = AVMetadataIdentifierQuickTimeUserDataOriginalArtist;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataRatingUser;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataRatingUser"] = AVMetadataIdentifierQuickTimeMetadataRatingUser;
	p = (void*) &AVMetadataIdentifierIcyMetadataStreamTitle;
	if (p != NULL) context[@"AVMetadataIdentifierIcyMetadataStreamTitle"] = AVMetadataIdentifierIcyMetadataStreamTitle;
	p = (void*) &AVMetadataIdentifierID3MetadataInternetRadioStationOwner;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataInternetRadioStationOwner"] = AVMetadataIdentifierID3MetadataInternetRadioStationOwner;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataArtist;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataArtist"] = AVMetadataIdentifierQuickTimeMetadataArtist;
	p = (void*) &AVMetadataIdentifierID3MetadataMediaType;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataMediaType"] = AVMetadataIdentifierID3MetadataMediaType;
	p = (void*) &AVMetadataIdentifier3GPUserDataUserRating;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataUserRating"] = AVMetadataIdentifier3GPUserDataUserRating;
	p = (void*) &AVMetadataIdentifieriTunesMetadataArtist;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataArtist"] = AVMetadataIdentifieriTunesMetadataArtist;
	p = (void*) &AVMetadataIdentifieriTunesMetadataAlbumArtist;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataAlbumArtist"] = AVMetadataIdentifieriTunesMetadataAlbumArtist;
	p = (void*) &AVMetadataIdentifierID3MetadataOwnership;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOwnership"] = AVMetadataIdentifierID3MetadataOwnership;
	p = (void*) &AVMetadataIdentifier3GPUserDataAlbumAndTrack;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataAlbumAndTrack"] = AVMetadataIdentifier3GPUserDataAlbumAndTrack;
	p = (void*) &AVMetadataCommonIdentifierSoftware;
	if (p != NULL) context[@"AVMetadataCommonIdentifierSoftware"] = AVMetadataCommonIdentifierSoftware;
	p = (void*) &AVMetadataIdentifierID3MetadataDate;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataDate"] = AVMetadataIdentifierID3MetadataDate;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataGenre;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataGenre"] = AVMetadataIdentifierQuickTimeMetadataGenre;
	p = (void*) &AVMetadataIdentifierID3MetadataOfficialAudioSourceWebpage;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOfficialAudioSourceWebpage"] = AVMetadataIdentifierID3MetadataOfficialAudioSourceWebpage;
	p = (void*) &AVMetadataIdentifieriTunesMetadataTrackNumber;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataTrackNumber"] = AVMetadataIdentifieriTunesMetadataTrackNumber;
	p = (void*) &AVMetadataIdentifieriTunesMetadataSoloist;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataSoloist"] = AVMetadataIdentifieriTunesMetadataSoloist;
	p = (void*) &AVMetadataIdentifierIcyMetadataStreamURL;
	if (p != NULL) context[@"AVMetadataIdentifierIcyMetadataStreamURL"] = AVMetadataIdentifierIcyMetadataStreamURL;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataVideoOrientation;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataVideoOrientation"] = AVMetadataIdentifierQuickTimeMetadataVideoOrientation;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataSoftware;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataSoftware"] = AVMetadataIdentifierQuickTimeUserDataSoftware;
	p = (void*) &AVMetadataIdentifierID3MetadataTime;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataTime"] = AVMetadataIdentifierID3MetadataTime;
	p = (void*) &AVMetadataIdentifierID3MetadataEncodingTime;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataEncodingTime"] = AVMetadataIdentifierID3MetadataEncodingTime;
	p = (void*) &AVMetadataIdentifierID3MetadataEncodedBy;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataEncodedBy"] = AVMetadataIdentifierID3MetadataEncodedBy;
	p = (void*) &AVMetadataCommonIdentifierArtist;
	if (p != NULL) context[@"AVMetadataCommonIdentifierArtist"] = AVMetadataCommonIdentifierArtist;
	p = (void*) &AVMetadataIdentifieriTunesMetadataAuthor;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataAuthor"] = AVMetadataIdentifieriTunesMetadataAuthor;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataLocationISO6709;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataLocationISO6709"] = AVMetadataIdentifierQuickTimeUserDataLocationISO6709;
	p = (void*) &AVMetadataIdentifier3GPUserDataCopyright;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataCopyright"] = AVMetadataIdentifier3GPUserDataCopyright;
	p = (void*) &AVMetadataIdentifieriTunesMetadataCredits;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataCredits"] = AVMetadataIdentifieriTunesMetadataCredits;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataLocationRole;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataLocationRole"] = AVMetadataIdentifierQuickTimeMetadataLocationRole;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataFullName;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataFullName"] = AVMetadataIdentifierQuickTimeUserDataFullName;
	p = (void*) &AVMetadataIdentifierID3MetadataTrackNumber;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataTrackNumber"] = AVMetadataIdentifierID3MetadataTrackNumber;
	p = (void*) &AVMetadataIdentifieriTunesMetadataPublisher;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataPublisher"] = AVMetadataIdentifieriTunesMetadataPublisher;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataMake;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataMake"] = AVMetadataIdentifierQuickTimeUserDataMake;
	p = (void*) &AVMetadataIdentifierID3MetadataEventTimingCodes;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataEventTimingCodes"] = AVMetadataIdentifierID3MetadataEventTimingCodes;
	p = (void*) &AVMetadataIdentifier3GPUserDataLocation;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataLocation"] = AVMetadataIdentifier3GPUserDataLocation;
	p = (void*) &AVMetadataIdentifieriTunesMetadataAccountKind;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataAccountKind"] = AVMetadataIdentifieriTunesMetadataAccountKind;
	p = (void*) &AVMetadataIdentifierID3MetadataBeatsPerMinute;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataBeatsPerMinute"] = AVMetadataIdentifierID3MetadataBeatsPerMinute;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataPublisher;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataPublisher"] = AVMetadataIdentifierQuickTimeUserDataPublisher;
	p = (void*) &AVMetadataIdentifierID3MetadataPlayCounter;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataPlayCounter"] = AVMetadataIdentifierID3MetadataPlayCounter;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataYear;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataYear"] = AVMetadataIdentifierQuickTimeMetadataYear;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataDescription;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataDescription"] = AVMetadataIdentifierQuickTimeUserDataDescription;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataLocationName;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataLocationName"] = AVMetadataIdentifierQuickTimeMetadataLocationName;
	p = (void*) &AVMetadataIdentifieriTunesMetadataAlbum;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataAlbum"] = AVMetadataIdentifieriTunesMetadataAlbum;
	p = (void*) &AVMetadataIdentifierID3MetadataLength;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataLength"] = AVMetadataIdentifierID3MetadataLength;
	p = (void*) &AVMetadataCommonIdentifierPublisher;
	if (p != NULL) context[@"AVMetadataCommonIdentifierPublisher"] = AVMetadataCommonIdentifierPublisher;
	p = (void*) &AVMetadataIdentifieriTunesMetadataOriginalArtist;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataOriginalArtist"] = AVMetadataIdentifieriTunesMetadataOriginalArtist;
	p = (void*) &AVMetadataIdentifieriTunesMetadataDescription;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataDescription"] = AVMetadataIdentifieriTunesMetadataDescription;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataCreationDate;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataCreationDate"] = AVMetadataIdentifierQuickTimeUserDataCreationDate;
	p = (void*) &AVMetadataIdentifierID3MetadataOriginalReleaseYear;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOriginalReleaseYear"] = AVMetadataIdentifierID3MetadataOriginalReleaseYear;
	p = (void*) &AVMetadataIdentifier3GPUserDataCollection;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataCollection"] = AVMetadataIdentifier3GPUserDataCollection;
	p = (void*) &AVMetadataIdentifierID3MetadataUserText;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataUserText"] = AVMetadataIdentifierID3MetadataUserText;
	p = (void*) &AVMetadataCommonIdentifierFormat;
	if (p != NULL) context[@"AVMetadataCommonIdentifierFormat"] = AVMetadataCommonIdentifierFormat;
	p = (void*) &AVMetadataIdentifierID3MetadataUnsynchronizedLyric;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataUnsynchronizedLyric"] = AVMetadataIdentifierID3MetadataUnsynchronizedLyric;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataDirectionMotion;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataDirectionMotion"] = AVMetadataIdentifierQuickTimeMetadataDirectionMotion;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataContentIdentifier;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataContentIdentifier"] = AVMetadataIdentifierQuickTimeMetadataContentIdentifier;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataDirector;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataDirector"] = AVMetadataIdentifierQuickTimeUserDataDirector;
	p = (void*) &AVMetadataIdentifierID3MetadataTitleSortOrder;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataTitleSortOrder"] = AVMetadataIdentifierID3MetadataTitleSortOrder;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataCameraIdentifier;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataCameraIdentifier"] = AVMetadataIdentifierQuickTimeMetadataCameraIdentifier;
	p = (void*) &AVMetadataIdentifierID3MetadataSetSubtitle;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataSetSubtitle"] = AVMetadataIdentifierID3MetadataSetSubtitle;
	p = (void*) &AVMetadataCommonIdentifierCreationDate;
	if (p != NULL) context[@"AVMetadataCommonIdentifierCreationDate"] = AVMetadataCommonIdentifierCreationDate;
	p = (void*) &AVMetadataIdentifierID3MetadataBand;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataBand"] = AVMetadataIdentifierID3MetadataBand;
	p = (void*) &AVMetadataIdentifierID3MetadataSubTitle;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataSubTitle"] = AVMetadataIdentifierID3MetadataSubTitle;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataModel;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataModel"] = AVMetadataIdentifierQuickTimeMetadataModel;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataWarning;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataWarning"] = AVMetadataIdentifierQuickTimeUserDataWarning;
	p = (void*) &AVMetadataIdentifier3GPUserDataAuthor;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataAuthor"] = AVMetadataIdentifier3GPUserDataAuthor;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataTrackName;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataTrackName"] = AVMetadataIdentifierQuickTimeUserDataTrackName;
	p = (void*) &AVMetadataCommonIdentifierContributor;
	if (p != NULL) context[@"AVMetadataCommonIdentifierContributor"] = AVMetadataCommonIdentifierContributor;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataComposer;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataComposer"] = AVMetadataIdentifierQuickTimeMetadataComposer;
	p = (void*) &AVMetadataIdentifierISOUserDataDate;
	if (p != NULL) context[@"AVMetadataIdentifierISOUserDataDate"] = AVMetadataIdentifierISOUserDataDate;
	p = (void*) &AVMetadataIdentifierID3MetadataPrivate;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataPrivate"] = AVMetadataIdentifierID3MetadataPrivate;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataEncodedBy;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataEncodedBy"] = AVMetadataIdentifierQuickTimeUserDataEncodedBy;
	p = (void*) &AVMetadataIdentifier3GPUserDataGenre;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataGenre"] = AVMetadataIdentifier3GPUserDataGenre;
	p = (void*) &AVMetadataIdentifierID3MetadataUniqueFileIdentifier;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataUniqueFileIdentifier"] = AVMetadataIdentifierID3MetadataUniqueFileIdentifier;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataProducer;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataProducer"] = AVMetadataIdentifierQuickTimeUserDataProducer;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataOriginalFormat;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataOriginalFormat"] = AVMetadataIdentifierQuickTimeUserDataOriginalFormat;
	p = (void*) &AVMetadataIdentifierID3MetadataGeneralEncapsulatedObject;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataGeneralEncapsulatedObject"] = AVMetadataIdentifierID3MetadataGeneralEncapsulatedObject;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataArranger;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataArranger"] = AVMetadataIdentifierQuickTimeUserDataArranger;
	p = (void*) &AVMetadataIdentifierID3MetadataCommerical;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataCommerical"] = AVMetadataIdentifierID3MetadataCommerical;
	p = (void*) &AVMetadataIdentifierID3MetadataOriginalAlbumTitle;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOriginalAlbumTitle"] = AVMetadataIdentifierID3MetadataOriginalAlbumTitle;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataCollectionUser;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataCollectionUser"] = AVMetadataIdentifierQuickTimeMetadataCollectionUser;
	p = (void*) &AVMetadataIdentifierID3MetadataSeek;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataSeek"] = AVMetadataIdentifierID3MetadataSeek;
	p = (void*) &AVMetadataIdentifierID3MetadataPopularimeter;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataPopularimeter"] = AVMetadataIdentifierID3MetadataPopularimeter;
	p = (void*) &AVMetadataCommonIdentifierSubject;
	if (p != NULL) context[@"AVMetadataCommonIdentifierSubject"] = AVMetadataCommonIdentifierSubject;
	p = (void*) &AVMetadataIdentifierID3MetadataOriginalReleaseTime;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOriginalReleaseTime"] = AVMetadataIdentifierID3MetadataOriginalReleaseTime;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataCameraFrameReadoutTime;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataCameraFrameReadoutTime"] = AVMetadataIdentifierQuickTimeMetadataCameraFrameReadoutTime;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataTrack;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataTrack"] = AVMetadataIdentifierQuickTimeUserDataTrack;
	p = (void*) &AVMetadataIdentifieriTunesMetadataComposer;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataComposer"] = AVMetadataIdentifieriTunesMetadataComposer;
	p = (void*) &AVMetadataIdentifieriTunesMetadataLinerNotes;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataLinerNotes"] = AVMetadataIdentifieriTunesMetadataLinerNotes;
	p = (void*) &AVMetadataIdentifieriTunesMetadataEQ;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataEQ"] = AVMetadataIdentifieriTunesMetadataEQ;
	p = (void*) &AVMetadataCommonIdentifierMake;
	if (p != NULL) context[@"AVMetadataCommonIdentifierMake"] = AVMetadataCommonIdentifierMake;
	p = (void*) &AVMetadataIdentifier3GPUserDataDescription;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataDescription"] = AVMetadataIdentifier3GPUserDataDescription;
	p = (void*) &AVMetadataIdentifierID3MetadataAlbumTitle;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataAlbumTitle"] = AVMetadataIdentifierID3MetadataAlbumTitle;
	p = (void*) &AVMetadataIdentifieriTunesMetadataUserComment;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataUserComment"] = AVMetadataIdentifieriTunesMetadataUserComment;
	p = (void*) &AVMetadataIdentifieriTunesMetadataReleaseDate;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataReleaseDate"] = AVMetadataIdentifieriTunesMetadataReleaseDate;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataComposer;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataComposer"] = AVMetadataIdentifierQuickTimeUserDataComposer;
	p = (void*) &AVMetadataIdentifierID3MetadataLeadPerformer;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataLeadPerformer"] = AVMetadataIdentifierID3MetadataLeadPerformer;
	p = (void*) &AVMetadataIdentifier3GPUserDataMediaClassification;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataMediaClassification"] = AVMetadataIdentifier3GPUserDataMediaClassification;
	p = (void*) &AVMetadataIdentifierID3MetadataInitialKey;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataInitialKey"] = AVMetadataIdentifierID3MetadataInitialKey;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataArtwork;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataArtwork"] = AVMetadataIdentifierQuickTimeMetadataArtwork;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataInformation;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataInformation"] = AVMetadataIdentifierQuickTimeUserDataInformation;
	p = (void*) &AVMetadataCommonIdentifierAlbumName;
	if (p != NULL) context[@"AVMetadataCommonIdentifierAlbumName"] = AVMetadataCommonIdentifierAlbumName;
	p = (void*) &AVMetadataIdentifierID3MetadataSignature;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataSignature"] = AVMetadataIdentifierID3MetadataSignature;
	p = (void*) &AVMetadataIdentifieriTunesMetadataDirector;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataDirector"] = AVMetadataIdentifieriTunesMetadataDirector;
	p = (void*) &AVMetadataIdentifierID3MetadataOriginalFilename;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOriginalFilename"] = AVMetadataIdentifierID3MetadataOriginalFilename;
	p = (void*) &AVMetadataIdentifieriTunesMetadataConductor;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataConductor"] = AVMetadataIdentifieriTunesMetadataConductor;
	p = (void*) &AVMetadataIdentifierID3MetadataLanguage;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataLanguage"] = AVMetadataIdentifierID3MetadataLanguage;
	p = (void*) &AVMetadataIdentifierID3MetadataMusicianCreditsList;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataMusicianCreditsList"] = AVMetadataIdentifierID3MetadataMusicianCreditsList;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataDisclaimer;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataDisclaimer"] = AVMetadataIdentifierQuickTimeUserDataDisclaimer;
	p = (void*) &AVMetadataIdentifierID3MetadataAlbumSortOrder;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataAlbumSortOrder"] = AVMetadataIdentifierID3MetadataAlbumSortOrder;
	p = (void*) &AVMetadataIdentifierID3MetadataInvolvedPeopleList_v23;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataInvolvedPeopleList_v23"] = AVMetadataIdentifierID3MetadataInvolvedPeopleList_v23;
	p = (void*) &AVMetadataCommonIdentifierType;
	if (p != NULL) context[@"AVMetadataCommonIdentifierType"] = AVMetadataCommonIdentifierType;
	p = (void*) &AVMetadataIdentifieriTunesMetadataEncodingTool;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataEncodingTool"] = AVMetadataIdentifieriTunesMetadataEncodingTool;
	p = (void*) &AVMetadataIdentifierID3MetadataContentType;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataContentType"] = AVMetadataIdentifierID3MetadataContentType;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataGenre;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataGenre"] = AVMetadataIdentifierQuickTimeUserDataGenre;
	p = (void*) &AVMetadataIdentifierID3MetadataReleaseTime;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataReleaseTime"] = AVMetadataIdentifierID3MetadataReleaseTime;
	p = (void*) &AVMetadataIdentifierID3MetadataLyricist;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataLyricist"] = AVMetadataIdentifierID3MetadataLyricist;
	p = (void*) &AVMetadataIdentifierID3MetadataGroupIdentifier;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataGroupIdentifier"] = AVMetadataIdentifierID3MetadataGroupIdentifier;
	p = (void*) &AVMetadataCommonIdentifierLanguage;
	if (p != NULL) context[@"AVMetadataCommonIdentifierLanguage"] = AVMetadataCommonIdentifierLanguage;
	p = (void*) &AVMetadataCommonIdentifierRelation;
	if (p != NULL) context[@"AVMetadataCommonIdentifierRelation"] = AVMetadataCommonIdentifierRelation;
	p = (void*) &AVMetadataIdentifieriTunesMetadataAppleID;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataAppleID"] = AVMetadataIdentifieriTunesMetadataAppleID;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataProduct;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataProduct"] = AVMetadataIdentifierQuickTimeUserDataProduct;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataPhonogramRights;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataPhonogramRights"] = AVMetadataIdentifierQuickTimeUserDataPhonogramRights;
	p = (void*) &AVMetadataIdentifierID3MetadataRelativeVolumeAdjustment2;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataRelativeVolumeAdjustment2"] = AVMetadataIdentifierID3MetadataRelativeVolumeAdjustment2;
	p = (void*) &AVMetadataIdentifierID3MetadataEncodedWith;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataEncodedWith"] = AVMetadataIdentifierID3MetadataEncodedWith;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataLocationISO6709;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataLocationISO6709"] = AVMetadataIdentifierQuickTimeMetadataLocationISO6709;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataLocationBody;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataLocationBody"] = AVMetadataIdentifierQuickTimeMetadataLocationBody;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataPhonogramRights;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataPhonogramRights"] = AVMetadataIdentifierQuickTimeMetadataPhonogramRights;
	p = (void*) &AVMetadataIdentifieriTunesMetadataDiscCompilation;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataDiscCompilation"] = AVMetadataIdentifieriTunesMetadataDiscCompilation;
	p = (void*) &AVMetadataIdentifieriTunesMetadataExecProducer;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataExecProducer"] = AVMetadataIdentifieriTunesMetadataExecProducer;
	p = (void*) &AVMetadataIdentifierISOUserDataCopyright;
	if (p != NULL) context[@"AVMetadataIdentifierISOUserDataCopyright"] = AVMetadataIdentifierISOUserDataCopyright;
	p = (void*) &AVMetadataIdentifierID3MetadataPublisher;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataPublisher"] = AVMetadataIdentifierID3MetadataPublisher;
	p = (void*) &AVMetadataIdentifierID3MetadataTermsOfUse;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataTermsOfUse"] = AVMetadataIdentifierID3MetadataTermsOfUse;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataDirectionFacing;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataDirectionFacing"] = AVMetadataIdentifierQuickTimeMetadataDirectionFacing;
	p = (void*) &AVMetadataIdentifierID3MetadataComposer;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataComposer"] = AVMetadataIdentifierID3MetadataComposer;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataOriginalSource;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataOriginalSource"] = AVMetadataIdentifierQuickTimeUserDataOriginalSource;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataKeywords;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataKeywords"] = AVMetadataIdentifierQuickTimeUserDataKeywords;
	p = (void*) &AVMetadataIdentifierID3MetadataFileType;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataFileType"] = AVMetadataIdentifierID3MetadataFileType;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataiXML;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataiXML"] = AVMetadataIdentifierQuickTimeMetadataiXML;
	p = (void*) &AVMetadataIdentifieriTunesMetadataThanks;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataThanks"] = AVMetadataIdentifieriTunesMetadataThanks;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataLocationNote;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataLocationNote"] = AVMetadataIdentifierQuickTimeMetadataLocationNote;
	p = (void*) &AVMetadataIdentifier3GPUserDataPerformer;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataPerformer"] = AVMetadataIdentifier3GPUserDataPerformer;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataCopyright;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataCopyright"] = AVMetadataIdentifierQuickTimeMetadataCopyright;
	p = (void*) &AVMetadataCommonIdentifierDescription;
	if (p != NULL) context[@"AVMetadataCommonIdentifierDescription"] = AVMetadataCommonIdentifierDescription;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataProducer;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataProducer"] = AVMetadataIdentifierQuickTimeMetadataProducer;
	p = (void*) &AVMetadataIdentifierID3MetadataOfficialInternetRadioStationHomepage;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOfficialInternetRadioStationHomepage"] = AVMetadataIdentifierID3MetadataOfficialInternetRadioStationHomepage;
	p = (void*) &AVMetadataCommonIdentifierAuthor;
	if (p != NULL) context[@"AVMetadataCommonIdentifierAuthor"] = AVMetadataCommonIdentifierAuthor;
	p = (void*) &AVMetadataIdentifieriTunesMetadataBeatsPerMin;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataBeatsPerMin"] = AVMetadataIdentifieriTunesMetadataBeatsPerMin;
	p = (void*) &AVMetadataIdentifierID3MetadataOfficialAudioFileWebpage;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOfficialAudioFileWebpage"] = AVMetadataIdentifierID3MetadataOfficialAudioFileWebpage;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataSpecialPlaybackRequirements;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataSpecialPlaybackRequirements"] = AVMetadataIdentifierQuickTimeUserDataSpecialPlaybackRequirements;
	p = (void*) &AVMetadataIdentifier3GPUserDataThumbnail;
	if (p != NULL) context[@"AVMetadataIdentifier3GPUserDataThumbnail"] = AVMetadataIdentifier3GPUserDataThumbnail;
	p = (void*) &AVMetadataIdentifierID3MetadataCommercialInformation;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataCommercialInformation"] = AVMetadataIdentifierID3MetadataCommercialInformation;
	p = (void*) &AVMetadataIdentifieriTunesMetadataCoverArt;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataCoverArt"] = AVMetadataIdentifieriTunesMetadataCoverArt;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataPerformer;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataPerformer"] = AVMetadataIdentifierQuickTimeMetadataPerformer;
	p = (void*) &AVMetadataIdentifierID3MetadataYear;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataYear"] = AVMetadataIdentifierID3MetadataYear;
	p = (void*) &AVMetadataIdentifierID3MetadataCopyrightInformation;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataCopyrightInformation"] = AVMetadataIdentifierID3MetadataCopyrightInformation;
	p = (void*) &AVMetadataIdentifierID3MetadataTaggingTime;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataTaggingTime"] = AVMetadataIdentifierID3MetadataTaggingTime;
	p = (void*) &AVMetadataIdentifierID3MetadataRecommendedBufferSize;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataRecommendedBufferSize"] = AVMetadataIdentifierID3MetadataRecommendedBufferSize;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataURLLink;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataURLLink"] = AVMetadataIdentifierQuickTimeUserDataURLLink;
	p = (void*) &AVMetadataIdentifieriTunesMetadataSoundEngineer;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataSoundEngineer"] = AVMetadataIdentifieriTunesMetadataSoundEngineer;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataAlbum;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataAlbum"] = AVMetadataIdentifierQuickTimeUserDataAlbum;
	p = (void*) &AVMetadataIdentifierID3MetadataInvolvedPeopleList_v24;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataInvolvedPeopleList_v24"] = AVMetadataIdentifierID3MetadataInvolvedPeopleList_v24;
	p = (void*) &AVMetadataIdentifierID3MetadataPartOfASet;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataPartOfASet"] = AVMetadataIdentifierID3MetadataPartOfASet;
	p = (void*) &AVMetadataIdentifierID3MetadataEqualization;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataEqualization"] = AVMetadataIdentifierID3MetadataEqualization;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataPerformers;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataPerformers"] = AVMetadataIdentifierQuickTimeUserDataPerformers;
	p = (void*) &AVMetadataIdentifierQuickTimeUserDataCopyright;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeUserDataCopyright"] = AVMetadataIdentifierQuickTimeUserDataCopyright;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataAuthor;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataAuthor"] = AVMetadataIdentifierQuickTimeMetadataAuthor;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataLocationDate;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataLocationDate"] = AVMetadataIdentifierQuickTimeMetadataLocationDate;
	p = (void*) &AVMetadataIdentifierID3MetadataOriginalArtist;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataOriginalArtist"] = AVMetadataIdentifierID3MetadataOriginalArtist;
	p = (void*) &AVMetadataCommonIdentifierTitle;
	if (p != NULL) context[@"AVMetadataCommonIdentifierTitle"] = AVMetadataCommonIdentifierTitle;
	p = (void*) &AVMetadataCommonIdentifierArtwork;
	if (p != NULL) context[@"AVMetadataCommonIdentifierArtwork"] = AVMetadataCommonIdentifierArtwork;
	p = (void*) &AVMetadataIdentifierID3MetadataEncryption;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataEncryption"] = AVMetadataIdentifierID3MetadataEncryption;
	p = (void*) &AVMetadataIdentifierID3MetadataRecordingDates;
	if (p != NULL) context[@"AVMetadataIdentifierID3MetadataRecordingDates"] = AVMetadataIdentifierID3MetadataRecordingDates;
	p = (void*) &AVMetadataIdentifieriTunesMetadataTrackSubTitle;
	if (p != NULL) context[@"AVMetadataIdentifieriTunesMetadataTrackSubTitle"] = AVMetadataIdentifieriTunesMetadataTrackSubTitle;
	p = (void*) &AVMetadataIdentifierQuickTimeMetadataDetectedFace;
	if (p != NULL) context[@"AVMetadataIdentifierQuickTimeMetadataDetectedFace"] = AVMetadataIdentifierQuickTimeMetadataDetectedFace;
	p = (void*) &AVMetadataCommonIdentifierLocation;
	if (p != NULL) context[@"AVMetadataCommonIdentifierLocation"] = AVMetadataCommonIdentifierLocation;
}
void load_AVFoundation_AVMetadataIdentifiers_symbols(JSContext* context)
{
    addProtocols();
    registerEnumConstants(context);
    registerCFunctions(context);
    registerGlobalConstants(context);
}
#pragma clang diagnostic pop
