//
//  CoreComponent.h
//  CoreComponent
//
//  Created by Aravind Macharla on 13/04/18.
//  Copyright © 2018 Aravind Macharla. All rights reserved.
//

#import <UIKit/UIKit.h>

//! Project version number for CoreComponent.
FOUNDATION_EXPORT double CoreComponentVersionNumber;

//! Project version string for CoreComponent.
FOUNDATION_EXPORT const unsigned char CoreComponentVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <CoreComponent/PublicHeader.h>

#import <CoreComponent/KonyCollection.h>
#import <CoreComponent/NSData+Hex.h>
#import <CoreComponent/BoxTemplateWidget.h>
#import <CoreComponent/NetworkException.h>
#import <CoreComponent/KonyScrollViewDelegate.h>
#import <CoreComponent/WidgetModel+PreviewingModel.h>
#import <CoreComponent/Switch3DTransition.h>
#import <CoreComponent/KonyTitleBarSkin.h>
#import <CoreComponent/JSScriptLoader.h>
#import <CoreComponent/FlexLayoutHorizontalFlowEngineImpl.h>
#import <CoreComponent/FlexScrollContainerProxy.h>
#import <CoreComponent/FontsLoader.h>
#import <CoreComponent/FormController1.h>
#import <CoreComponent/CommonI18nAPI.h>
#import <CoreComponent/CustomAnimationController.h>
#import <CoreComponent/MSGradient.h>
#import <CoreComponent/WidgetLayout.h>
#import <CoreComponent/JSStaticAPI.h>
#import <CoreComponent/KonyModuleProxyProtocol.h>
#import <CoreComponent/AnimationStep.h>
#import <CoreComponent/KonyHighlightHandler.h>
#import <CoreComponent/JSKonyAPI.h>
#import <CoreComponent/FlexContainerModel.h>
#import <CoreComponent/BadgeSkin.h>
#import <CoreComponent/KonyWrapper.h>
#import <CoreComponent/PropertyMap.h>
#import <CoreComponent/Theme.h>
#import <CoreComponent/JSFunctionalModule.h>
#import <CoreComponent/CustomCellBackgroundView.h>
#import <CoreComponent/PickerControl.h>
#import <CoreComponent/KonyTapGesture.h>
#import <CoreComponent/SkinModel.h>
#import <CoreComponent/JSForm.h>
#import <CoreComponent/CustomKVOArrayProxy.h>
#import <CoreComponent/JSLabel.h>
#import <CoreComponent/KonyI18n.h>
#import <CoreComponent/archive_entry.h>
#import <CoreComponent/LayoutUtil.h>
#import <CoreComponent/ObservationInfo.h>
#import <CoreComponent/KonyTintUtil.h>
#import <CoreComponent/KonyShapeLayer.h>
#import <CoreComponent/RootContainerWidgetWithSafeAreaLayout.h>
#import <CoreComponent/CJSONDataSerializer.h>
#import <CoreComponent/JSAppHeaderFooterObject.h>
#import <CoreComponent/KonyTabBarController.h>
#import <CoreComponent/KonyTouchEvents.h>
#import <CoreComponent/JSi18nAPI.h>
#import <CoreComponent/CSerializedJSONData.h>
#import <CoreComponent/KonyTextInputTypes.h>
#import <CoreComponent/CustomContentViewWithLayer.h>
#import <CoreComponent/GenericSkin.h>
#import <CoreComponent/FlexContainerProxy.h>
#import <CoreComponent/AppMenuObservingProtocol.h>
#import <CoreComponent/ContainerBackgroundView.h>
#import <CoreComponent/iCarousel+CustomMethods.h>
#import <CoreComponent/FlexLayoutInfoProtocol.h>
#import <CoreComponent/WidgetModel.h>
#import <CoreComponent/LayoutModel.h>
#import <CoreComponent/FormController1+PreviewingController.h>
#import <CoreComponent/KonyException.h>
#import <CoreComponent/RawBytesMemoryPool.h>
#import <CoreComponent/ClosureExecuter.h>
#import <CoreComponent/AnimationUtils.h>
#import <CoreComponent/JSValueRef.h>
#import <CoreComponent/gekus.h>
#import <CoreComponent/KonyCustomAnimator.h>
#import <CoreComponent/KonyStaticClassProxyImpMethods.h>
#import <CoreComponent/VMAppDelegate.h>
#import <CoreComponent/KonyWidgetEventListenerProtocol.h>
#import <CoreComponent/FlexScrollContainerModel.h>
#import <CoreComponent/KonyAppMenuController.h>
#import <CoreComponent/LicenseLoader.h>
#import <CoreComponent/JSVocabulary.h>
#import <CoreComponent/ScrollContainerModelWithNavigation.h>
#import <CoreComponent/KonyGlobalContext.h>
#import <CoreComponent/KonyInputAccessoryView.h>
#import <CoreComponent/JSStringRefCF.h>
#import <CoreComponent/KonyLibrary.h>
#import <CoreComponent/Kony_NSData+Base64.h>
#import <CoreComponent/HMGLTransitionManager.h>
#import <CoreComponent/FlexLayoutContainerSkin.h>
#import <CoreComponent/AnimationHandleProxy.h>
#import <CoreComponent/KonyUIContext.h>
#import <CoreComponent/AppMenuSkin.h>
#import <CoreComponent/JSObjectParsing.h>
#import <CoreComponent/KonyUnitTestManager.h>
#import <CoreComponent/I18nStore.h>
#import <CoreComponent/JSTransfromObject.h>
#import <CoreComponent/TransformDataModel.h>
#import <CoreComponent/FlexScrollLayoutContainer.h>
#import <CoreComponent/ObservingProxy.h>
#import <CoreComponent/KonyWidgetEventSenderProtocol.h>
#import <CoreComponent/JSBarButtonItem.h>
#import <CoreComponent/PersistantThemeStore.h>
#import <CoreComponent/JSBridgeForNativeContext.h>
#import <CoreComponent/KonyAPIValidationUtility.h>
#import <CoreComponent/NextPrevToolBar.h>
#import <CoreComponent/Widget.h>
#import <CoreComponent/KeyFrameAnchorPointAnimator.h>
#import <CoreComponent/KeyFrameAnimationModel.h>
#import <CoreComponent/ClothTransition.h>
#import <CoreComponent/KonyManager.h>
#import <CoreComponent/FlexLayoutMetaInfoProtocol.h>
#import <CoreComponent/KonyDismissOnTapGestureRecognizer.h>
#import <CoreComponent/BoxWidgetBase.h>
#import <CoreComponent/KonyPasteBoard.h>
#import <CoreComponent/KeyFrameAnimationUIViewBased.h>
#import <CoreComponent/KonyScrollViewOffsetHandler.h>
#import <CoreComponent/KonyModuleManagerConstants.h>
#import <CoreComponent/OsAPI.h>
#import <CoreComponent/WheelWidgetHandler.h>
#import <CoreComponent/CustomAnimationProtocol.h>
#import <CoreComponent/NSCharacterSet_Extensions.h>
#import <CoreComponent/JSRawBytes.h>
#import <CoreComponent/NativeContainerModel.h>
#import <CoreComponent/BoxWidget.h>
#import <CoreComponent/KonyLabel.h>
#import <CoreComponent/ViewDrawingDelegate.h>
#import <CoreComponent/KonyInputAccessoryViewCancel.h>
#import <CoreComponent/KonyModuleStaticClassProxyProtocol.h>
#import <CoreComponent/BoxSkin.h>
#import <CoreComponent/CDataScanner_Extensions.h>
#import <CoreComponent/BarButtonItemModel.h>
#import <CoreComponent/KonyLongPressGesture.h>
#import <CoreComponent/JSScriptLoaderUtil.h>
#import <CoreComponent/UserProtocol.h>
#import <CoreComponent/WidgetModel+Defaults.h>
#import <CoreComponent/KonyResourceAccessUtil.h>
#import <CoreComponent/KonyWrapperDS.h>
#import <CoreComponent/KonyError.h>
#import <CoreComponent/KonyTypeUtils.h>
#import <CoreComponent/CustomBadge.h>
#import <CoreComponent/Unarchiver.h>
#import <CoreComponent/FunctionExecuterDelegate.h>
#import <CoreComponent/NSException+KonyErrorException.h>
#import <CoreComponent/ScrollingInfo.h>
#import <CoreComponent/JSCache.h>
#import <CoreComponent/ConversionUtility.h>
#import <CoreComponent/NativeContainerView.h>
#import <CoreComponent/LabelWidet.h>
#import <CoreComponent/KonyCacheSettingUtil.h>
#import <CoreComponent/splashView.h>
#import <CoreComponent/FlexLayoutConversionUtil.h>
#import <CoreComponent/LabelProxy.h>
#import <CoreComponent/KonyCustomAppMenuItem.h>
#import <CoreComponent/BoxTemplateProxy.h>
#import <CoreComponent/SkinAnimator.h>
#import <CoreComponent/WrapperUtils.h>
#import <CoreComponent/LuaTable.h>
#import <CoreComponent/ExeContext.h>
#import <CoreComponent/KeyframeAlphaAnimator.h>
#import <CoreComponent/JSObject.h>
#import <CoreComponent/BoxLayoutManager.h>
#import <CoreComponent/AppMenuManager.h>
#import <CoreComponent/b64.h>
#import <CoreComponent/KonyIndex.h>
#import <CoreComponent/UnarchiverDelegate.h>
#import <CoreComponent/KonyCustomNavigationController.h>
#import <CoreComponent/KonyCustomAnimationDelegate.h>
#import <CoreComponent/KeyFrameZIndexAnimator.h>
#import <CoreComponent/KonyNotificationCenterConstants.h>
#import <CoreComponent/NativeContainerProxy.h>
#import <CoreComponent/FormSkin.h>
#import <CoreComponent/JSWorkerStaticAPI.h>
#import <CoreComponent/WidgetBackgroundLayer.h>
#import <CoreComponent/ObjCPropertyInfo.h>
#import <CoreComponent/KonyModulePrincipalClassProtocol.h>
#import <CoreComponent/FrameworkLogger.h>
#import <CoreComponent/ScrollableBoxView.h>
#import <CoreComponent/KonyAppMenuItem.h>
#import <CoreComponent/KonyTouchDownGestureRecognizer.h>
#import <CoreComponent/BarButtonItemProxy.h>
#import <CoreComponent/KonyModuleManager.h>
#import <CoreComponent/JSNativeContainer.h>
#import <CoreComponent/FlexLayoutManager.h>
#import <CoreComponent/JSAnimationAPI.h>
#import <CoreComponent/KonyTypes.h>
#import <CoreComponent/KonyTitleBarButton.h>
#import <CoreComponent/LayerLayoutDelegate.h>
#import <CoreComponent/ltypes.h>
#import <CoreComponent/KonyTrafficRecordedDataManager.h>
#import <CoreComponent/BoxTemplateModel.h>
#import <CoreComponent/KonyJSValue.h>
#import <CoreComponent/opcodes.h>
#import <CoreComponent/FlexScrollModelProtocol.h>
#import <CoreComponent/JSFlexContainer.h>
#import <CoreComponent/KonySplitHorizontal.h>
#import <CoreComponent/LabelModel.h>
#import <CoreComponent/CustomShapeLayer.h>
#import <CoreComponent/CJSONSerializer.h>
#import <CoreComponent/KonyModuleContext.h>
#import <CoreComponent/JSBackgroundJobsAPI.h>
#import <CoreComponent/KonyCustomAppMenuController.h>
#import <CoreComponent/FlexLayoutUtil.h>
#import <CoreComponent/KonyTabBarPosition.h>
#import <CoreComponent/FlexScrollLayoutContainerSkin.h>
#import <CoreComponent/AlertModel.h>
#import <CoreComponent/PropertyMapStore.h>
#import <CoreComponent/FlexLayoutEngine.h>
#import <CoreComponent/RawBytes.h>
#import <CoreComponent/FormProxy+PreviewingProxy.h>
#import <CoreComponent/GestureUtils.h>
#import <CoreComponent/NSString+KonyLib.h>
#import <CoreComponent/ApplicationContext.h>
#import <CoreComponent/MSGradientBorderLayer.h>
#import <CoreComponent/KeyFrameTransformAnimator.h>
#import <CoreComponent/KonyConstants.h>
#import <CoreComponent/KonyHeader.h>
#import <CoreComponent/OperationInvoker.h>
#import <CoreComponent/ApplicationContextManager.h>
#import <CoreComponent/KonyTransitionFlip.h>
#import <CoreComponent/FunctionModuleLoader.h>
#import <CoreComponent/WebKitAvailability.h>
#import <CoreComponent/Runtime.h>
#import <CoreComponent/KonyXMLReader.h>
#import <CoreComponent/KonyDockableSplit.h>
#import <CoreComponent/JSUser.h>
#import <CoreComponent/KonyNotificationCenter.h>
#import <CoreComponent/SynthesizeSingleton.h>
#import <CoreComponent/AnimationBaseInterface.h>
#import <CoreComponent/KonyRotateGesture.h>
#import <CoreComponent/JavaScript.h>
#import <CoreComponent/WorkerThread.h>
#import <CoreComponent/DummyAppDelegate.h>
#import <CoreComponent/NotificationSettingConstants.h>
#import <CoreComponent/KonyBoolean.h>
#import <CoreComponent/lglobals.h>
#import <CoreComponent/I18nFile.h>
#import <CoreComponent/NSString+MD5Addition.h>
#import <CoreComponent/iCarousel.h>
#import <CoreComponent/KeyFrameAnimation.h>
#import <CoreComponent/HapticFeedbackGenerator.h>
#import <CoreComponent/NetworkStatusBar.h>
#import <CoreComponent/AnimationModel.h>
#import <CoreComponent/BaseAnimation.h>
#import <CoreComponent/archive_reader.h>
#import <CoreComponent/BoxProxy.h>
#import <CoreComponent/JSFunctionStack.h>
#import <CoreComponent/KonyUI.h>
#import <CoreComponent/KonyTrafficInspector.h>
#import <CoreComponent/JSUtil.h>
#import <CoreComponent/I18nStoreProtocol.h>
#import <CoreComponent/FormAPI.h>
#import <CoreComponent/ExtendedView.h>
#import <CoreComponent/Reachability.h>
#import <CoreComponent/JSBoxTemplate.h>
#import <CoreComponent/AccessibilityDelegate.h>
#import <CoreComponent/CWIWidget.h>
#import <CoreComponent/Shadows.h>
#import <CoreComponent/FlexLayoutFreeFormEngineImpl.h>
#import <CoreComponent/CustomContentView.h>
#import <CoreComponent/KonyTabItem.h>
#import <CoreComponent/BoxView.h>
#import <CoreComponent/KonyTrafficRecordedDataModel.h>
#import <CoreComponent/KonyDS.h>
#import <CoreComponent/FlexLayoutEnginePrivate.h>
#import <CoreComponent/FnModuleInfo.h>
#import <CoreComponent/KonyTapGestureRecognizer.h>
#import <CoreComponent/DoorsTransition.h>
#import <CoreComponent/JSObjectMemoryManager.h>
#import <CoreComponent/KonyPreviewActionItem.h>
#import <CoreComponent/Skin.h>
#import <CoreComponent/KonyModuleConstructorClassProxyProtocol.h>
#import <CoreComponent/ContainerWidget.h>
#import <CoreComponent/JSBox.h>
#import <CoreComponent/JavaScriptCore.h>
#import <CoreComponent/KonyAlert.h>
#import <CoreComponent/RunTimeManager.h>
#import <CoreComponent/CustomSwitchCaseMacros.h>
#import <CoreComponent/FlexLayoutModelProperty.h>
#import <CoreComponent/KonySwipeGesture.h>
#import <CoreComponent/KonyWidgetUtility.h>
#import <CoreComponent/JSFunctionExecuter.h>
#import <CoreComponent/UserInterfaceManager.h>
#import <CoreComponent/SkinUtils.h>
#import <CoreComponent/CJSONScanner.h>
#import <CoreComponent/SwizzeledMethods.h>
#import <CoreComponent/PickerControlWithLayer.h>
#import <CoreComponent/UIDeviceExt.h>
#import <CoreComponent/KonyCWIEnvironment.h>
#import <CoreComponent/LayoutManager.h>
#import <CoreComponent/PickerControlWithDrawing.h>
#import <CoreComponent/ValidationUtility.h>
#import <CoreComponent/util.h>
#import <CoreComponent/FunctionExecuter.h>
#import <CoreComponent/JSBasicAPI.h>
#import <CoreComponent/VideoWidgetLoader.h>
#import <CoreComponent/AppMenuModel.h>
#import <CoreComponent/ContentView.h>
#import <CoreComponent/KonyApplicationGlobalHeaderFooters.h>
#import <CoreComponent/FlexLayoutEngineImpl.h>
#import <CoreComponent/LoadingScreen.h>
#import <CoreComponent/ObjectCounter.h>
#import <CoreComponent/ContainerWidgetLayout.h>
#import <CoreComponent/I18nDB.h>
#import <CoreComponent/BoxModel.h>
#import <CoreComponent/ViewLayoutDelegate.h>
#import <CoreComponent/FormModel+PreviewingModel.h>
#import <CoreComponent/KonyGestureManager.h>
#import <CoreComponent/LanguageContext.h>
#import <CoreComponent/KonyApplicationContext.h>
#import <CoreComponent/KonyPanGesture.h>
#import <CoreComponent/KonyIdleTimer.h>
#import <CoreComponent/AnimationGroup.h>
#import <CoreComponent/RootContainerWidget.h>
#import <CoreComponent/KonyTestStaticProxyClass.h>
#import <CoreComponent/ScrollContainerModel.h>
#import <CoreComponent/KonyLibraryInitializationDelegate.h>
#import <CoreComponent/UserWidget.h>
#import <CoreComponent/KonyContainer.h>
#import <CoreComponent/FlexLayoutModel.h>
#import <CoreComponent/LuaBoolean.h>
#import <CoreComponent/HMGLTransition.h>
#import <CoreComponent/ProfilerFunctionData.h>
#import <CoreComponent/FormProxy.h>
#import <CoreComponent/JSFlexScrollContainer.h>
#import <CoreComponent/NSDictionary_JSONExtensions.h>
#import <CoreComponent/TitleBarSkin.h>
#import <CoreComponent/CustomCellBackgroundViewWithLayer.h>
#import <CoreComponent/JSConversionUtility.h>
#import <CoreComponent/RuntimeObject.h>
#import <CoreComponent/UserProxy.h>
#import <CoreComponent/FormWidget.h>
#import <CoreComponent/LabelSkin.h>
#import <CoreComponent/FlexLayoutVerticalFlowEngineImpl.h>
#import <CoreComponent/JSTransformAPI.h>
#import <CoreComponent/ObserverProtocol.h>
#import <CoreComponent/FlipTransition.h>
#import <CoreComponent/CallBackListenerProtocol.h>
#import <CoreComponent/BaseProxy+PreviewingProxy.h>
#import <CoreComponent/WidgetTypeManager.h>
#import <CoreComponent/UIDevice+IdentifierAddition.h>
#import <CoreComponent/HMGLTransitionView.h>
#import <CoreComponent/RuntimeDelegate.h>
#import <CoreComponent/CJSONDeserializer.h>
#import <CoreComponent/ConstructorSwapLoader.h>
#import <CoreComponent/JSLangAPI.h>
#import <CoreComponent/KonyTestModule.h>
#import <CoreComponent/NativeContainerViewController.h>
#import <CoreComponent/ObservableObject.h>
#import <CoreComponent/KonyWidgetFocusProtocol.h>
#import <CoreComponent/JSFunction.h>
#import <CoreComponent/KonyUtil.h>
#import <CoreComponent/KonyImageUtil.h>
#import <CoreComponent/Widget+Hierarchy.h>
#import <CoreComponent/BaseModel.h>
#import <CoreComponent/JSONKit.h>
#import <CoreComponent/KonyUIApplication.h>
#import <CoreComponent/KonyLibraryResultDelegate.h>
#import <CoreComponent/CustomAnimationWorker.h>
#import <CoreComponent/KonyWidgetProtocol.h>
#import <CoreComponent/KonyAnimTwoSplitRotate.h>
#import <CoreComponent/JSBase.h>
#import <CoreComponent/SkinManager.h>
#import <CoreComponent/Skin+Default.h>
#import <CoreComponent/FlexLayoutContainer.h>
#import <CoreComponent/NativeContainerWidget.h>
#import <CoreComponent/JSOldForm.h>
#import <CoreComponent/CachedDictionary.h>
#import <CoreComponent/Profiler.h>
#import <CoreComponent/KonyGestureProtocol.h>
#import <CoreComponent/JSWidget.h>
#import <CoreComponent/JSMVCAPI.h>
#import <CoreComponent/JSFunctionStackTracer.h>
#import <CoreComponent/BoxLayoutModel.h>
#import <CoreComponent/AppMenuItemModel.h>
#import <CoreComponent/UIViewController_CustomAppMenu.h>
#import <CoreComponent/TransientLayoutModelProxy.h>
#import <CoreComponent/KonySplitVertical.h>
#import <CoreComponent/ProfilerWriterBasic.h>
#import <CoreComponent/JSObjectRef.h>
#import <CoreComponent/ClientTrustManager.h>
#import <CoreComponent/BoxContainerLayoutModel.h>
#import <CoreComponent/CallBack.h>
#import <CoreComponent/CDataScanner.h>
#import <CoreComponent/UILabel+labelExtension.h>
#import <CoreComponent/KonyTabBar.h>
#import <CoreComponent/KonyBackgroundJobManager.h>
#import <CoreComponent/AlertBindingUtility.h>
#import <CoreComponent/KonyScrollViewDelegateProxy.h>
#import <CoreComponent/KonyTrafficInspectorRulesManager.h>
#import <CoreComponent/FormModel.h>
#import <CoreComponent/KonyLayoutContainerView.h>
#import <CoreComponent/KonyTwoSplit.h>
#import <CoreComponent/BarButtonItemWidget.h>
#import <CoreComponent/AlertManager.h>
#import <CoreComponent/KonyGestureRecognizer.h>
#import <CoreComponent/JSStringRef.h>
#import <CoreComponent/CustomContentViewWithDrawing.h>
#import <CoreComponent/OMPageControl.h>
#import <CoreComponent/NSScanner_Extensions.h>
#import <CoreComponent/UserModel.h>
#import <CoreComponent/KonyTouchEventsProtocol.h>
#import <CoreComponent/JSObjectProtector.h>
#import <CoreComponent/ApplicationController.h>
#import <CoreComponent/ScreenCapturer.h>
#import <CoreComponent/JSMVCForm.h>
#import <CoreComponent/RotateTransition.h>
#import <CoreComponent/KonyShapeLayerController.h>
#import <CoreComponent/PlatformConstants.h>
#import <CoreComponent/KonyMacros1.h>
#import <CoreComponent/KonyTabBarControllerDelegate.h>
#import <CoreComponent/CustomCellBackgroundViewWithDrawing.h>
#import <CoreComponent/ContainerModel.h>
#import <CoreComponent/JSContextRef.h>
#import <CoreComponent/JSAlert.h>
#import <CoreComponent/FlexLayoutDirectionalFlowEngineImpl.h>
#import <CoreComponent/JSBackgroundTaskReply.h>
#import <CoreComponent/KeyboardStyle.h>
#import <CoreComponent/KonyCustomNavigationProtocol.h>
#import <CoreComponent/KonyDrawCommon.h>
#import <CoreComponent/BaseProxy.h>
#import <CoreComponent/KonyCustomAnimationManager.h>
#import <CoreComponent/FlexLayoutEngines.h>
#import <CoreComponent/KonyPinchGesture.h>
#import <CoreComponent/KonyValueConversionUtility.h>
#import <CoreComponent/KonyStoryboardManager.h>
#import <CoreComponent/KonyStoryboard.h>
#import <CoreComponent/KonyStoryboardModel.h>
#import <CoreComponent/KonyLaunchStoryboard.h>
#import <CoreComponent/KonyLaunchStoryboardModel.h>
#import <CoreComponent/KonyMVCUtils.h>
#import <CoreComponent/AnimationForGifImages.h>

