#import "allincludes.h"
#import <JavaScriptCore/JavaScriptCore.h>
void loadNFIUIKitModules(JSContext* context)
{
	load_UIKit_UIAttachmentBehavior_symbols(context);
	load_UIKit_UIRotationGestureRecognizer_symbols(context);
	load_UIKit_UIResponder_symbols(context);
	load_UIKit_UIVideoEditorController_symbols(context);
	load_UIKit_UISplitViewController_symbols(context);
	load_UIKit_NSTextAttachment_symbols(context);
	load_UIKit_UINavigationItem_symbols(context);
	load_UIKit_UITextDragPreviewRenderer_symbols(context);
	load_UIKit_UIBarCommon_symbols(context);
	load_UIKit_UIAccessibilityElement_symbols(context);
	load_UIKit_UITableViewHeaderFooterView_symbols(context);
	load_UIKit_UIScreenMode_symbols(context);
	load_UIKit_UIViewController_symbols(context);
	load_UIKit_UIInputViewController_symbols(context);
	load_UIKit_UIToolbar_symbols(context);
	load_UIKit_UIDocumentMenuViewController_symbols(context);
	load_UIKit_UIScreen_symbols(context);
	load_UIKit_UIPress_symbols(context);
	load_UIKit_UITapGestureRecognizer_symbols(context);
	load_UIKit_UIDocumentInteractionController_symbols(context);
	load_UIKit_UIDragPreview_symbols(context);
	load_UIKit_UIActivity_symbols(context);
	load_UIKit_UILexicon_symbols(context);
	load_UIKit_UIImageAsset_symbols(context);
	load_UIKit_NSLayoutAnchor_symbols(context);
	load_UIKit_UIViewControllerTransitioning_symbols(context);
	load_UIKit_UISegmentedControl_symbols(context);
	load_UIKit_UIDataDetectors_symbols(context);
	load_UIKit_UIPressesEvent_symbols(context);
	load_UIKit_UIGraphicsRenderer_symbols(context);
	load_UIKit_UISearchContainerViewController_symbols(context);
	load_UIKit_UIEvent_symbols(context);
	load_UIKit_UIPrinter_symbols(context);
	load_UIKit_UISwipeGestureRecognizer_symbols(context);
	load_UIKit_UIAccessibilityAdditions_symbols(context);
	load_UIKit_DocumentManager_UIDocumentBrowserViewController_symbols(context);
	load_UIKit_UIDropInteraction_symbols(context);
	load_UIKit_UIPinchGestureRecognizer_symbols(context);
	load_UIKit_UIStringDrawing_symbols(context);
	load_UIKit_UIFocus_symbols(context);
	load_UIKit_UIDocumentPickerExtensionViewController_symbols(context);
	load_UIKit_UIAccessibility_symbols(context);
	load_UIKit_NSTextContainer_symbols(context);
	load_UIKit_UIAccessibilityConstants_symbols(context);
	load_UIKit_NSAttributedString_symbols(context);
	load_UIKit_UISearchDisplayController_symbols(context);
	load_UIKit_UITextDragURLPreviews_symbols(context);
	load_UIKit_UIAccessibilityZoom_symbols(context);
	load_UIKit_UIDragSession_symbols(context);
	load_UIKit_UIPresentationController_symbols(context);
	load_UIKit_UIPasteConfigurationSupporting_symbols(context);
	load_UIKit_UITraitCollection_symbols(context);
	load_UIKit_UICollectionViewController_symbols(context);
	load_UIKit_UIRefreshControl_symbols(context);
	load_UIKit_UIDragInteraction_symbols(context);
	load_UIKit_UIControl_symbols(context);
	load_UIKit_UIViewPropertyAnimator_symbols(context);
	load_UIKit_UITabBarItem_symbols(context);
	load_UIKit_UIFocusDebugger_symbols(context);
	load_UIKit_UIPopoverBackgroundView_symbols(context);
	load_UIKit_UITextInteraction_symbols(context);
	load_UIKit_UIVibrancyEffect_symbols(context);
	load_UIKit_UIViewAnimating_symbols(context);
	load_UIKit_UIInteraction_symbols(context);
	load_UIKit_UIDragItem_symbols(context);
	load_UIKit_UIFieldBehavior_symbols(context);
	load_UIKit_UIPrintInteractionController_symbols(context);
	load_UIKit_UIFontMetrics_symbols(context);
	load_UIKit_UIGestureRecognizer_symbols(context);
	load_UIKit_UIAccessibilityIdentification_symbols(context);
	load_UIKit_UITabBar_symbols(context);
	load_UIKit_UICollisionBehavior_symbols(context);
	load_UIKit_UIActivityViewController_symbols(context);
	load_UIKit_UIFontDescriptor_symbols(context);
	load_UIKit_UIFeedbackGenerator_symbols(context);
	load_UIKit_UIScrollView_symbols(context);
	load_UIKit_UITimingCurveProvider_symbols(context);
	load_UIKit_UIScreenEdgePanGestureRecognizer_symbols(context);
	load_UIKit_UIStateRestoration_symbols(context);
	load_UIKit_UITouch_symbols(context);
	load_UIKit_UIAccessibilityContentSizeCategoryImageAdjusting_symbols(context);
	load_UIKit_UIFont_symbols(context);
	load_UIKit_UIApplication_symbols(context);
	load_UIKit_UIFocusSystem_symbols(context);
	load_UIKit_UICollectionView_symbols(context);
	load_UIKit_UIContextualAction_symbols(context);
	load_UIKit_UIPasteConfiguration_symbols(context);
	load_UIKit_UIImageView_symbols(context);
	load_UIKit_UINib_symbols(context);
	load_UIKit_UIAccessibilityCustomAction_symbols(context);
	load_UIKit_NSTextStorage_symbols(context);
	load_UIKit_UIGuidedAccessRestrictions_symbols(context);
	load_UIKit_UIImpactFeedbackGenerator_symbols(context);
	load_UIKit_UIBlurEffect_symbols(context);
	load_UIKit_UIPopoverController_symbols(context);
	load_UIKit_UILocalizedIndexedCollation_symbols(context);
	load_UIKit_UIBarButtonItemGroup_symbols(context);
	load_UIKit_UIPageViewController_symbols(context);
	load_UIKit_UIPrintPageRenderer_symbols(context);
	load_UIKit_UIInterface_symbols(context);
	load_UIKit_UITabBarController_symbols(context);
	load_UIKit_UISlider_symbols(context);
	load_UIKit_UITextPasteConfigurationSupporting_symbols(context);
	load_UIKit_UIFocusGuide_symbols(context);
	load_UIKit_UIDynamicAnimator_symbols(context);
	load_UIKit_UINavigationBar_symbols(context);
	load_UIKit_UITextPasteDelegate_symbols(context);
	load_UIKit_UIPushBehavior_symbols(context);
	load_UIKit_UIPrinterPickerController_symbols(context);
	load_UIKit_UINotificationFeedbackGenerator_symbols(context);
	load_UIKit_UITextDragging_symbols(context);
	load_UIKit_UITextField_symbols(context);
	load_UIKit_UIContentSizeCategory_symbols(context);
	load_UIKit_UIDevice_symbols(context);
	load_UIKit_UISwitch_symbols(context);
	load_UIKit_UIManagedDocument_symbols(context);
	load_UIKit_UICollectionViewCell_symbols(context);
	load_UIKit_UICollectionViewLayout_symbols(context);
	load_UIKit_UITableView_symbols(context);
	load_UIKit_UIPanGestureRecognizer_symbols(context);
	load_UIKit_UIGravityBehavior_symbols(context);
	load_UIKit_UIDynamicItemBehavior_symbols(context);
	load_UIKit_NSParagraphStyle_symbols(context);
	load_UIKit_UIDynamicBehavior_symbols(context);
	load_UIKit_UITextDropping_symbols(context);
	load_UIKit_UIPreviewInteraction_symbols(context);
	load_UIKit_NSItemProvider_UIKitAdditions_symbols(context);
	load_UIKit_NSShadow_symbols(context);
	load_UIKit_UIActivityIndicatorView_symbols(context);
	load_UIKit_UIPageControl_symbols(context);
	load_UIKit_UIBarButtonItem_symbols(context);
	load_UIKit_UITextChecker_symbols(context);
	load_UIKit_UIViewControllerTransitionCoordinator_symbols(context);
	load_UIKit_UIView_symbols(context);
	load_UIKit_UIAccelerometer_symbols(context);
	load_UIKit_UIImage_symbols(context);
	load_UIKit_UILayoutGuide_symbols(context);
	load_UIKit_UIGraphicsImageRenderer_symbols(context);
	load_UIKit_UIFocusAnimationCoordinator_symbols(context);
	load_UIKit_UIPopoverSupport_symbols(context);
	load_UIKit_UIWindow_symbols(context);
	load_UIKit_UISpringLoadedInteractionSupporting_symbols(context);
	load_UIKit_UIStoryboardPopoverSegue_symbols(context);
	load_UIKit_UIStoryboardSegue_symbols(context);
	load_UIKit_UIVisualEffectView_symbols(context);
	load_UIKit_NSText_symbols(context);
	load_UIKit_UIStoryboard_symbols(context);
	load_UIKit_UIAccessibilityCustomRotor_symbols(context);
	load_UIKit_UISnapBehavior_symbols(context);
	load_UIKit_UITextInputTraits_symbols(context);
	load_UIKit_UIBarItem_symbols(context);
	load_UIKit_UISearchBar_symbols(context);
	load_UIKit_UIBezierPath_symbols(context);
	load_UIKit_DocumentManager_UIDocumentBrowserAction_symbols(context);
	load_UIKit_UIInputView_symbols(context);
	load_UIKit_UIPasteboard_symbols(context);
	load_UIKit_UILongPressGestureRecognizer_symbols(context);
	load_UIKit_UIPrintFormatter_symbols(context);
	load_UIKit_UIGeometry_symbols(context);
	load_UIKit_UISearchController_symbols(context);
	load_UIKit_UIAccessibilityContainer_symbols(context);
	load_UIKit_UIActionSheet_symbols(context);
	load_UIKit_UIMenuController_symbols(context);
	load_UIKit_UITableViewController_symbols(context);
	load_UIKit_UISpringLoadedInteraction_symbols(context);
	load_UIKit_UIDocumentPickerViewController_symbols(context);
	load_UIKit_UIPickerView_symbols(context);
	load_UIKit_UIPrintInfo_symbols(context);
	load_UIKit_UICollectionViewFlowLayout_symbols(context);
	load_UIKit_UIStackView_symbols(context);
	load_UIKit_UITargetedDragPreview_symbols(context);
	load_UIKit_UICollectionViewTransitionLayout_symbols(context);
	load_UIKit_NSDataAsset_symbols(context);
	load_UIKit_UIPopoverPresentationController_symbols(context);
	load_UIKit_UIContentSizeCategoryAdjusting_symbols(context);
	load_UIKit_UIMotionEffect_symbols(context);
	load_UIKit_UILabel_symbols(context);
	load_UIKit_UIButton_symbols(context);
	load_UIKit_UIVisualEffect_symbols(context);
	load_UIKit_UIImagePickerController_symbols(context);
	load_UIKit_UITimingParameters_symbols(context);
	load_UIKit_UISelectionFeedbackGenerator_symbols(context);
	load_UIKit_UIGraphicsPDFRenderer_symbols(context);
	load_UIKit_UIAccessibilityLocationDescriptor_symbols(context);
	load_UIKit_UINavigationController_symbols(context);
	load_UIKit_UITextDropProposal_symbols(context);
	load_UIKit_UITextInput_symbols(context);
	load_UIKit_UINibLoading_symbols(context);
	load_UIKit_UIColor_symbols(context);
	load_UIKit_UIAppearance_symbols(context);
	load_UIKit_UIPrintPaper_symbols(context);
	load_UIKit_UIUserNotificationSettings_symbols(context);
	load_UIKit_UIStepper_symbols(context);
	load_UIKit_UITextView_symbols(context);
	load_UIKit_UIPrintError_symbols(context);
	load_UIKit_NSLayoutManager_symbols(context);
	load_UIKit_UIProgressView_symbols(context);
	load_UIKit_UILocalNotification_symbols(context);
	load_UIKit_UIDocument_symbols(context);
	load_UIKit_UIGraphics_symbols(context);
	load_UIKit_NSStringDrawing_symbols(context);
	load_UIKit_UISwipeActionsConfiguration_symbols(context);
	load_UIKit_UIAlertController_symbols(context);
	load_UIKit_UIReferenceLibraryViewController_symbols(context);
	load_UIKit_UIDataSourceTranslating_symbols(context);
	load_UIKit_UIApplicationShortcutItem_symbols(context);
	load_UIKit_NSIndexPath_UIKitAdditions_symbols(context);
	load_UIKit_UIActivityItemProvider_symbols(context);
	load_UIKit_UICloudSharingController_symbols(context);
	load_UIKit_UIAlertView_symbols(context);
	load_UIKit_UIRegion_symbols(context);
	load_UIKit_UITableViewCell_symbols(context);
	load_UIKit_UIDatePicker_symbols(context);
	load_UIKit_NSLayoutConstraint_symbols(context);
	load_UIKit_UIDragPreviewParameters_symbols(context);
}

JSValue* extractNFIUIKitStructArgument(const char* type, NSInvocation* invocation, NSUInteger index, JSContext* context)
{
	if (strcmp(type, @encode(UIFloatRange)) == 0) {
		UIFloatRange argument;
		[invocation getArgument: &argument atIndex: index];
		return [JSValue valueWithUIFloatRange: argument inContext: context];
	} else if (strcmp(type, @encode(UIEdgeInsets)) == 0) {
		UIEdgeInsets argument;
		[invocation getArgument: &argument atIndex: index];
		return [JSValue valueWithUIEdgeInsets: argument inContext: context];
	} else if (strcmp(type, @encode(UIOffset)) == 0) {
		UIOffset argument;
		[invocation getArgument: &argument atIndex: index];
		return [JSValue valueWithUIOffset: argument inContext: context];
	} else if (strcmp(type, @encode(NSDirectionalEdgeInsets)) == 0) {
		NSDirectionalEdgeInsets argument;
		[invocation getArgument: &argument atIndex: index];
		return [JSValue valueWithNSDirectionalEdgeInsets: argument inContext: context];
	}    
    return nil;
}

BOOL setNFIUIKitStructReturnValue(const char* type, JSValue* value, NSInvocation* invocation)
{
	if (strcmp(type, @encode(UIFloatRange)) == 0) {
		UIFloatRange returnValue = value.toUIFloatRange;
		[invocation setReturnValue: &returnValue];
		return YES;
	} else if (strcmp(type, @encode(UIEdgeInsets)) == 0) {
		UIEdgeInsets returnValue = value.toUIEdgeInsets;
		[invocation setReturnValue: &returnValue];
		return YES;
	} else if (strcmp(type, @encode(UIOffset)) == 0) {
		UIOffset returnValue = value.toUIOffset;
		[invocation setReturnValue: &returnValue];
		return YES;
	} else if (strcmp(type, @encode(NSDirectionalEdgeInsets)) == 0) {
		NSDirectionalEdgeInsets returnValue = value.toNSDirectionalEdgeInsets;
		[invocation setReturnValue: &returnValue];
		return YES;
	}    
    return NO;
}

