#import <objc/runtime.h>
#import "allincludes.h"
#import <NFIUtility/CallbackSupport.h>
#import <NFIUtility/PointerSupport.h>
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wincompatible-pointer-types"
#pragma clang diagnostic ignored "-Wnullability-completeness"
static void addProtocols()
{
}
static void registerCFunctions(JSContext* context)
{
}
static void registerEnumConstants(JSContext* context)
{
	context[@"kCGImagePropertyOrientationUp"] = @1U;
	context[@"kCGImagePropertyOrientationUpMirrored"] = @2U;
	context[@"kCGImagePropertyOrientationDown"] = @3U;
	context[@"kCGImagePropertyOrientationDownMirrored"] = @4U;
	context[@"kCGImagePropertyOrientationLeftMirrored"] = @5U;
	context[@"kCGImagePropertyOrientationRight"] = @6U;
	context[@"kCGImagePropertyOrientationRightMirrored"] = @7U;
	context[@"kCGImagePropertyOrientationLeft"] = @8U;

}
static void registerGlobalConstants(JSContext* context)
{
	void* p; p = NULL;
	p = (void*) &kCGImagePropertyHeight;
	if (p != NULL) context[@"kCGImagePropertyHeight"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyHeight inContext: context];
	p = (void*) &kCGImagePropertyDNGVersion;
	if (p != NULL) context[@"kCGImagePropertyDNGVersion"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGVersion inContext: context];
	p = (void*) &kCGImagePropertyDNGLensInfo;
	if (p != NULL) context[@"kCGImagePropertyDNGLensInfo"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGLensInfo inContext: context];
	p = (void*) &kCGImagePropertyGPSProcessingMethod;
	if (p != NULL) context[@"kCGImagePropertyGPSProcessingMethod"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSProcessingMethod inContext: context];
	p = (void*) &kCGImagePropertyExifSaturation;
	if (p != NULL) context[@"kCGImagePropertyExifSaturation"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSaturation inContext: context];
	p = (void*) &kCGImagePropertyGIFHasGlobalColorMap;
	if (p != NULL) context[@"kCGImagePropertyGIFHasGlobalColorMap"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGIFHasGlobalColorMap inContext: context];
	p = (void*) &kCGImagePropertyPNGCopyright;
	if (p != NULL) context[@"kCGImagePropertyPNGCopyright"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGCopyright inContext: context];
	p = (void*) &kCGImagePropertyJFIFYDensity;
	if (p != NULL) context[@"kCGImagePropertyJFIFYDensity"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyJFIFYDensity inContext: context];
	p = (void*) &kCGImagePropertyIPTCEditorialUpdate;
	if (p != NULL) context[@"kCGImagePropertyIPTCEditorialUpdate"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCEditorialUpdate inContext: context];
	p = (void*) &kCGImagePropertyIPTCImageOrientation;
	if (p != NULL) context[@"kCGImagePropertyIPTCImageOrientation"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCImageOrientation inContext: context];
	p = (void*) &kCGImagePropertyGPSVersion;
	if (p != NULL) context[@"kCGImagePropertyGPSVersion"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSVersion inContext: context];
	p = (void*) &kCGImagePropertyDNGWarpFisheye;
	if (p != NULL) context[@"kCGImagePropertyDNGWarpFisheye"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGWarpFisheye inContext: context];
	p = (void*) &kCGImagePropertyExifMakerNote;
	if (p != NULL) context[@"kCGImagePropertyExifMakerNote"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifMakerNote inContext: context];
	p = (void*) &kCGImagePropertyExifAuxFlashCompensation;
	if (p != NULL) context[@"kCGImagePropertyExifAuxFlashCompensation"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifAuxFlashCompensation inContext: context];
	p = (void*) &kCGImagePropertyCIFFRecordID;
	if (p != NULL) context[@"kCGImagePropertyCIFFRecordID"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFRecordID inContext: context];
	p = (void*) &kCGImagePropertyTIFFImageDescription;
	if (p != NULL) context[@"kCGImagePropertyTIFFImageDescription"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFImageDescription inContext: context];
	p = (void*) &kCGImagePropertyExifFlashPixVersion;
	if (p != NULL) context[@"kCGImagePropertyExifFlashPixVersion"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifFlashPixVersion inContext: context];
	p = (void*) &kCGImagePropertyCIFFReleaseTiming;
	if (p != NULL) context[@"kCGImagePropertyCIFFReleaseTiming"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFReleaseTiming inContext: context];
	p = (void*) &kCGImagePropertyExifISOSpeedRatings;
	if (p != NULL) context[@"kCGImagePropertyExifISOSpeedRatings"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifISOSpeedRatings inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonSharpenMode;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonSharpenMode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonSharpenMode inContext: context];
	p = (void*) &kCGImagePropertyJFIFDictionary;
	if (p != NULL) context[@"kCGImagePropertyJFIFDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyJFIFDictionary inContext: context];
	p = (void*) &kCGImagePropertyIPTCCaptionAbstract;
	if (p != NULL) context[@"kCGImagePropertyIPTCCaptionAbstract"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCCaptionAbstract inContext: context];
	p = (void*) &kCGImagePropertyIPTCContactInfoPostalCode;
	if (p != NULL) context[@"kCGImagePropertyIPTCContactInfoPostalCode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCContactInfoPostalCode inContext: context];
	p = (void*) &kCGImagePropertyMakerCanonFirmware;
	if (p != NULL) context[@"kCGImagePropertyMakerCanonFirmware"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerCanonFirmware inContext: context];
	p = (void*) &kCGImagePropertyExifImageUniqueID;
	if (p != NULL) context[@"kCGImagePropertyExifImageUniqueID"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifImageUniqueID inContext: context];
	p = (void*) &kCGImagePropertyGPSDictionary;
	if (p != NULL) context[@"kCGImagePropertyGPSDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDictionary inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonDigitalZoom;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonDigitalZoom"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonDigitalZoom inContext: context];
	p = (void*) &kCGImagePropertyExifAuxLensModel;
	if (p != NULL) context[@"kCGImagePropertyExifAuxLensModel"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifAuxLensModel inContext: context];
	p = (void*) &kCGImagePropertyCIFFCameraSerialNumber;
	if (p != NULL) context[@"kCGImagePropertyCIFFCameraSerialNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFCameraSerialNumber inContext: context];
	p = (void*) &kCGImagePropertyPixelFormat;
	if (p != NULL) context[@"kCGImagePropertyPixelFormat"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPixelFormat inContext: context];
	p = (void*) &kCGImagePropertyExifGamma;
	if (p != NULL) context[@"kCGImagePropertyExifGamma"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifGamma inContext: context];
	p = (void*) &kCGImageAuxiliaryDataInfoDataDescription;
	if (p != NULL) context[@"kCGImageAuxiliaryDataInfoDataDescription"] = [JSValue valueWithObject: (__bridge id) kCGImageAuxiliaryDataInfoDataDescription inContext: context];
	p = (void*) &kCGImagePropertyIPTCRightsUsageTerms;
	if (p != NULL) context[@"kCGImagePropertyIPTCRightsUsageTerms"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCRightsUsageTerms inContext: context];
	p = (void*) &kCGImagePropertyExifFNumber;
	if (p != NULL) context[@"kCGImagePropertyExifFNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifFNumber inContext: context];
	p = (void*) &kCGImagePropertyExifFocalLenIn35mmFilm;
	if (p != NULL) context[@"kCGImagePropertyExifFocalLenIn35mmFilm"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifFocalLenIn35mmFilm inContext: context];
	p = (void*) &kCGImagePropertyPNGGamma;
	if (p != NULL) context[@"kCGImagePropertyPNGGamma"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGGamma inContext: context];
	p = (void*) &kCGImagePropertyExifLensSerialNumber;
	if (p != NULL) context[@"kCGImagePropertyExifLensSerialNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifLensSerialNumber inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonLensInfo;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonLensInfo"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonLensInfo inContext: context];
	p = (void*) &kCGImageAuxiliaryDataTypeDisparity;
	if (p != NULL) context[@"kCGImageAuxiliaryDataTypeDisparity"] = [JSValue valueWithObject: (__bridge id) kCGImageAuxiliaryDataTypeDisparity inContext: context];
	p = (void*) &kCGImagePropertyIPTCDictionary;
	if (p != NULL) context[@"kCGImagePropertyIPTCDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCDictionary inContext: context];
	p = (void*) &kCGImagePropertyDNGBackwardVersion;
	if (p != NULL) context[@"kCGImagePropertyDNGBackwardVersion"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGBackwardVersion inContext: context];
	p = (void*) &kCGImagePropertyCIFFImageSerialNumber;
	if (p != NULL) context[@"kCGImagePropertyCIFFImageSerialNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFImageSerialNumber inContext: context];
	p = (void*) &kCGImagePropertyExifFlashEnergy;
	if (p != NULL) context[@"kCGImagePropertyExifFlashEnergy"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifFlashEnergy inContext: context];
	p = (void*) &kCGImagePropertyCIFFDescription;
	if (p != NULL) context[@"kCGImagePropertyCIFFDescription"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFDescription inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonFocusMode;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonFocusMode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonFocusMode inContext: context];
	p = (void*) &kCGImagePropertyDNGDictionary;
	if (p != NULL) context[@"kCGImagePropertyDNGDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGDictionary inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonFlashExposureComp;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonFlashExposureComp"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonFlashExposureComp inContext: context];
	p = (void*) &kCGImagePropertyExifFocalPlaneYResolution;
	if (p != NULL) context[@"kCGImagePropertyExifFocalPlaneYResolution"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifFocalPlaneYResolution inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonLensType;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonLensType"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonLensType inContext: context];
	p = (void*) &kCGImagePropertyIPTCReleaseTime;
	if (p != NULL) context[@"kCGImagePropertyIPTCReleaseTime"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCReleaseTime inContext: context];
	p = (void*) &kCGImagePropertyGPSImgDirectionRef;
	if (p != NULL) context[@"kCGImagePropertyGPSImgDirectionRef"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSImgDirectionRef inContext: context];
	p = (void*) &kCGImagePropertyGPSMeasureMode;
	if (p != NULL) context[@"kCGImagePropertyGPSMeasureMode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSMeasureMode inContext: context];
	p = (void*) &kCGImagePropertyExifSubsecTimeOrginal;
	if (p != NULL) context[@"kCGImagePropertyExifSubsecTimeOrginal"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSubsecTimeOrginal inContext: context];
	p = (void*) &kCGImagePropertyExifExposureProgram;
	if (p != NULL) context[@"kCGImagePropertyExifExposureProgram"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifExposureProgram inContext: context];
	p = (void*) &kCGImagePropertyIPTCContactInfoCountry;
	if (p != NULL) context[@"kCGImagePropertyIPTCContactInfoCountry"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCContactInfoCountry inContext: context];
	p = (void*) &kCGImagePropertyExifComponentsConfiguration;
	if (p != NULL) context[@"kCGImagePropertyExifComponentsConfiguration"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifComponentsConfiguration inContext: context];
	p = (void*) &kCGImagePropertyExifISOSpeed;
	if (p != NULL) context[@"kCGImagePropertyExifISOSpeed"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifISOSpeed inContext: context];
	p = (void*) &kCGImagePropertyGPSDestLatitude;
	if (p != NULL) context[@"kCGImagePropertyGPSDestLatitude"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDestLatitude inContext: context];
	p = (void*) &kCGImagePropertyCIFFImageFileName;
	if (p != NULL) context[@"kCGImagePropertyCIFFImageFileName"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFImageFileName inContext: context];
	p = (void*) &kCGImagePropertyIPTCObjectCycle;
	if (p != NULL) context[@"kCGImagePropertyIPTCObjectCycle"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCObjectCycle inContext: context];
	p = (void*) &kCGImagePropertyIPTCProvinceState;
	if (p != NULL) context[@"kCGImagePropertyIPTCProvinceState"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCProvinceState inContext: context];
	p = (void*) &kCGImagePropertyJFIFVersion;
	if (p != NULL) context[@"kCGImagePropertyJFIFVersion"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyJFIFVersion inContext: context];
	p = (void*) &kCGImagePropertyIPTCObjectTypeReference;
	if (p != NULL) context[@"kCGImagePropertyIPTCObjectTypeReference"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCObjectTypeReference inContext: context];
	p = (void*) &kCGImagePropertyExifAuxLensSerialNumber;
	if (p != NULL) context[@"kCGImagePropertyExifAuxLensSerialNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifAuxLensSerialNumber inContext: context];
	p = (void*) &kCGImagePropertyCIFFWhiteBalanceIndex;
	if (p != NULL) context[@"kCGImagePropertyCIFFWhiteBalanceIndex"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFWhiteBalanceIndex inContext: context];
	p = (void*) &kCGImagePropertyExifGainControl;
	if (p != NULL) context[@"kCGImagePropertyExifGainControl"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifGainControl inContext: context];
	p = (void*) &kCGImagePropertyIPTCContact;
	if (p != NULL) context[@"kCGImagePropertyIPTCContact"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCContact inContext: context];
	p = (void*) &kCGImagePropertyGPSTrackRef;
	if (p != NULL) context[@"kCGImagePropertyGPSTrackRef"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSTrackRef inContext: context];
	p = (void*) &kCGImagePropertyIPTCContactInfoAddress;
	if (p != NULL) context[@"kCGImagePropertyIPTCContactInfoAddress"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCContactInfoAddress inContext: context];
	p = (void*) &kCGImagePropertyTIFFDateTime;
	if (p != NULL) context[@"kCGImagePropertyTIFFDateTime"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFDateTime inContext: context];
	p = (void*) &kCGImagePropertyExifAuxSerialNumber;
	if (p != NULL) context[@"kCGImagePropertyExifAuxSerialNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifAuxSerialNumber inContext: context];
	p = (void*) &kCGImagePropertyExifCameraOwnerName;
	if (p != NULL) context[@"kCGImagePropertyExifCameraOwnerName"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifCameraOwnerName inContext: context];
	p = (void*) &kCGImagePropertyExifLensModel;
	if (p != NULL) context[@"kCGImagePropertyExifLensModel"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifLensModel inContext: context];
	p = (void*) &kCGImagePropertyExifExposureIndex;
	if (p != NULL) context[@"kCGImagePropertyExifExposureIndex"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifExposureIndex inContext: context];
	p = (void*) &kCGImagePropertyIPTCCategory;
	if (p != NULL) context[@"kCGImagePropertyIPTCCategory"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCCategory inContext: context];
	p = (void*) &kCGImagePropertyExifVersion;
	if (p != NULL) context[@"kCGImagePropertyExifVersion"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifVersion inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonShootingMode;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonShootingMode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonShootingMode inContext: context];
	p = (void*) &kCGImagePropertyColorModelRGB;
	if (p != NULL) context[@"kCGImagePropertyColorModelRGB"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyColorModelRGB inContext: context];
	p = (void*) &kCGImagePropertyDepth;
	if (p != NULL) context[@"kCGImagePropertyDepth"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDepth inContext: context];
	p = (void*) &kCGImagePropertyMakerCanonDictionary;
	if (p != NULL) context[@"kCGImagePropertyMakerCanonDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerCanonDictionary inContext: context];
	p = (void*) &kCGImagePropertyExifFocalPlaneResolutionUnit;
	if (p != NULL) context[@"kCGImagePropertyExifFocalPlaneResolutionUnit"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifFocalPlaneResolutionUnit inContext: context];
	p = (void*) &kCGImagePropertyExifWhiteBalance;
	if (p != NULL) context[@"kCGImagePropertyExifWhiteBalance"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifWhiteBalance inContext: context];
	p = (void*) &kCGImagePropertyExifAuxLensInfo;
	if (p != NULL) context[@"kCGImagePropertyExifAuxLensInfo"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifAuxLensInfo inContext: context];
	p = (void*) &kCGImagePropertyDNGColorMatrix2;
	if (p != NULL) context[@"kCGImagePropertyDNGColorMatrix2"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGColorMatrix2 inContext: context];
	p = (void*) &kCGImagePropertyIPTCBylineTitle;
	if (p != NULL) context[@"kCGImagePropertyIPTCBylineTitle"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCBylineTitle inContext: context];
	p = (void*) &kCGImagePropertyExifDigitalZoomRatio;
	if (p != NULL) context[@"kCGImagePropertyExifDigitalZoomRatio"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifDigitalZoomRatio inContext: context];
	p = (void*) &kCGImagePropertyExifISOSpeedLatitudezzz;
	if (p != NULL) context[@"kCGImagePropertyExifISOSpeedLatitudezzz"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifISOSpeedLatitudezzz inContext: context];
	p = (void*) &kCGImagePropertyPNGAuthor;
	if (p != NULL) context[@"kCGImagePropertyPNGAuthor"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGAuthor inContext: context];
	p = (void*) &kCGImagePropertyIPTCUrgency;
	if (p != NULL) context[@"kCGImagePropertyIPTCUrgency"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCUrgency inContext: context];
	p = (void*) &kCGImagePropertyTIFFArtist;
	if (p != NULL) context[@"kCGImagePropertyTIFFArtist"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFArtist inContext: context];
	p = (void*) &kCGImagePropertyGPSImgDirection;
	if (p != NULL) context[@"kCGImagePropertyGPSImgDirection"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSImgDirection inContext: context];
	p = (void*) &kCGImagePropertyIPTCContactInfoWebURLs;
	if (p != NULL) context[@"kCGImagePropertyIPTCContactInfoWebURLs"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCContactInfoWebURLs inContext: context];
	p = (void*) &kCGImagePropertyCIFFOwnerName;
	if (p != NULL) context[@"kCGImagePropertyCIFFOwnerName"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFOwnerName inContext: context];
	p = (void*) &kCGImagePropertyDNGCameraSerialNumber;
	if (p != NULL) context[@"kCGImagePropertyDNGCameraSerialNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGCameraSerialNumber inContext: context];
	p = (void*) &kCGImagePropertyIPTCWriterEditor;
	if (p != NULL) context[@"kCGImagePropertyIPTCWriterEditor"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCWriterEditor inContext: context];
	p = (void*) &kCGImagePropertyAuxiliaryData;
	if (p != NULL) context[@"kCGImagePropertyAuxiliaryData"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyAuxiliaryData inContext: context];
	p = (void*) &kCGImagePropertyCIFFLensMaxMM;
	if (p != NULL) context[@"kCGImagePropertyCIFFLensMaxMM"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFLensMaxMM inContext: context];
	p = (void*) &kCGImagePropertyDNGProfileCalibrationSignature;
	if (p != NULL) context[@"kCGImagePropertyDNGProfileCalibrationSignature"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGProfileCalibrationSignature inContext: context];
	p = (void*) &kCGImagePropertyExifLightSource;
	if (p != NULL) context[@"kCGImagePropertyExifLightSource"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifLightSource inContext: context];
	p = (void*) &kCGImagePropertyExifAuxOwnerName;
	if (p != NULL) context[@"kCGImagePropertyExifAuxOwnerName"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifAuxOwnerName inContext: context];
	p = (void*) &kCGImagePropertyIPTCContactInfoEmails;
	if (p != NULL) context[@"kCGImagePropertyIPTCContactInfoEmails"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCContactInfoEmails inContext: context];
	p = (void*) &kCGImagePropertyDNGLocalizedCameraModel;
	if (p != NULL) context[@"kCGImagePropertyDNGLocalizedCameraModel"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGLocalizedCameraModel inContext: context];
	p = (void*) &kCGImagePropertyExifSensitivityType;
	if (p != NULL) context[@"kCGImagePropertyExifSensitivityType"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSensitivityType inContext: context];
	p = (void*) &kCGImagePropertyPNGInterlaceType;
	if (p != NULL) context[@"kCGImagePropertyPNGInterlaceType"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGInterlaceType inContext: context];
	p = (void*) &kCGImagePropertyGPSLongitude;
	if (p != NULL) context[@"kCGImagePropertyGPSLongitude"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSLongitude inContext: context];
	p = (void*) &kCGImagePropertyIPTCLanguageIdentifier;
	if (p != NULL) context[@"kCGImagePropertyIPTCLanguageIdentifier"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCLanguageIdentifier inContext: context];
	p = (void*) &kCGImagePropertyGPSDestLongitudeRef;
	if (p != NULL) context[@"kCGImagePropertyGPSDestLongitudeRef"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDestLongitudeRef inContext: context];
	p = (void*) &kCGImagePropertyIPTCSubLocation;
	if (p != NULL) context[@"kCGImagePropertyIPTCSubLocation"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCSubLocation inContext: context];
	p = (void*) &kCGImagePropertyTIFFTileWidth;
	if (p != NULL) context[@"kCGImagePropertyTIFFTileWidth"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFTileWidth inContext: context];
	p = (void*) &kCGImagePropertyGPSDOP;
	if (p != NULL) context[@"kCGImagePropertyGPSDOP"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDOP inContext: context];
	p = (void*) &kCGImagePropertyDNGNoiseProfile;
	if (p != NULL) context[@"kCGImagePropertyDNGNoiseProfile"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGNoiseProfile inContext: context];
	p = (void*) &kCGImagePropertyIPTCStarRating;
	if (p != NULL) context[@"kCGImagePropertyIPTCStarRating"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCStarRating inContext: context];
	p = (void*) &kCGImagePropertyExifMaxApertureValue;
	if (p != NULL) context[@"kCGImagePropertyExifMaxApertureValue"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifMaxApertureValue inContext: context];
	p = (void*) &kCGImagePropertyExifAuxImageNumber;
	if (p != NULL) context[@"kCGImagePropertyExifAuxImageNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifAuxImageNumber inContext: context];
	p = (void*) &kCGImagePropertyIPTCCreatorContactInfo;
	if (p != NULL) context[@"kCGImagePropertyIPTCCreatorContactInfo"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCCreatorContactInfo inContext: context];
	p = (void*) &kCGImagePropertyGPSHPositioningError;
	if (p != NULL) context[@"kCGImagePropertyGPSHPositioningError"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSHPositioningError inContext: context];
	p = (void*) &kCGImagePropertyGPSLatitude;
	if (p != NULL) context[@"kCGImagePropertyGPSLatitude"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSLatitude inContext: context];
	p = (void*) &kCGImagePropertyExifAuxLensID;
	if (p != NULL) context[@"kCGImagePropertyExifAuxLensID"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifAuxLensID inContext: context];
	p = (void*) &kCGImagePropertyExifSceneCaptureType;
	if (p != NULL) context[@"kCGImagePropertyExifSceneCaptureType"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSceneCaptureType inContext: context];
	p = (void*) &kCGImagePropertyExifExposureMode;
	if (p != NULL) context[@"kCGImagePropertyExifExposureMode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifExposureMode inContext: context];
	p = (void*) &kCGImagePropertyExifFlash;
	if (p != NULL) context[@"kCGImagePropertyExifFlash"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifFlash inContext: context];
	p = (void*) &kCGImagePropertyThumbnailImages;
	if (p != NULL) context[@"kCGImagePropertyThumbnailImages"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyThumbnailImages inContext: context];
	p = (void*) &kCGImagePropertyTIFFCompression;
	if (p != NULL) context[@"kCGImagePropertyTIFFCompression"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFCompression inContext: context];
	p = (void*) &kCGImagePropertyPixelHeight;
	if (p != NULL) context[@"kCGImagePropertyPixelHeight"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPixelHeight inContext: context];
	p = (void*) &kCGImagePropertyDNGWarpRectilinear;
	if (p != NULL) context[@"kCGImagePropertyDNGWarpRectilinear"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGWarpRectilinear inContext: context];
	p = (void*) &kCGImagePropertyIPTCCountryPrimaryLocationName;
	if (p != NULL) context[@"kCGImagePropertyIPTCCountryPrimaryLocationName"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCCountryPrimaryLocationName inContext: context];
	p = (void*) &kCGImagePropertyGPSTimeStamp;
	if (p != NULL) context[@"kCGImagePropertyGPSTimeStamp"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSTimeStamp inContext: context];
	p = (void*) &kCGImagePropertyIPTCSpecialInstructions;
	if (p != NULL) context[@"kCGImagePropertyIPTCSpecialInstructions"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCSpecialInstructions inContext: context];
	p = (void*) &kCGImagePropertyHasAlpha;
	if (p != NULL) context[@"kCGImagePropertyHasAlpha"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyHasAlpha inContext: context];
	p = (void*) &kCGImagePropertyPNGCreationTime;
	if (p != NULL) context[@"kCGImagePropertyPNGCreationTime"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGCreationTime inContext: context];
	p = (void*) &kCGImagePropertyExifDateTimeDigitized;
	if (p != NULL) context[@"kCGImagePropertyExifDateTimeDigitized"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifDateTimeDigitized inContext: context];
	p = (void*) &kCGImagePropertyCIFFMeasuredEV;
	if (p != NULL) context[@"kCGImagePropertyCIFFMeasuredEV"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFMeasuredEV inContext: context];
	p = (void*) &kCGImagePropertyIPTCObjectAttributeReference;
	if (p != NULL) context[@"kCGImagePropertyIPTCObjectAttributeReference"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCObjectAttributeReference inContext: context];
	p = (void*) &kCGImagePropertyColorModel;
	if (p != NULL) context[@"kCGImagePropertyColorModel"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyColorModel inContext: context];
	p = (void*) &kCGImagePropertyFileContentsDictionary;
	if (p != NULL) context[@"kCGImagePropertyFileContentsDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyFileContentsDictionary inContext: context];
	p = (void*) &kCGImagePropertyCIFFFirmware;
	if (p != NULL) context[@"kCGImagePropertyCIFFFirmware"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFFirmware inContext: context];
	p = (void*) &kCGImagePropertyExifLensSpecification;
	if (p != NULL) context[@"kCGImagePropertyExifLensSpecification"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifLensSpecification inContext: context];
	p = (void*) &kCGImagePropertyDNGCameraCalibration2;
	if (p != NULL) context[@"kCGImagePropertyDNGCameraCalibration2"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGCameraCalibration2 inContext: context];
	p = (void*) &kCGImagePropertyGIFUnclampedDelayTime;
	if (p != NULL) context[@"kCGImagePropertyGIFUnclampedDelayTime"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGIFUnclampedDelayTime inContext: context];
	p = (void*) &kCGImagePropertyExifSubsecTime;
	if (p != NULL) context[@"kCGImagePropertyExifSubsecTime"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSubsecTime inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonISOSelection;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonISOSelection"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonISOSelection inContext: context];
	p = (void*) &kCGImagePropertyExifApertureValue;
	if (p != NULL) context[@"kCGImagePropertyExifApertureValue"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifApertureValue inContext: context];
	p = (void*) &kCGImagePropertyExifAuxDictionary;
	if (p != NULL) context[@"kCGImagePropertyExifAuxDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifAuxDictionary inContext: context];
	p = (void*) &kCGImagePropertyIPTCContactInfoPhones;
	if (p != NULL) context[@"kCGImagePropertyIPTCContactInfoPhones"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCContactInfoPhones inContext: context];
	p = (void*) &kCGImagePropertyGPSDateStamp;
	if (p != NULL) context[@"kCGImagePropertyGPSDateStamp"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDateStamp inContext: context];
	p = (void*) &kCGImagePropertyIPTCContentLocationCode;
	if (p != NULL) context[@"kCGImagePropertyIPTCContentLocationCode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCContentLocationCode inContext: context];
	p = (void*) &kCGImagePropertyPNGCompressionFilter;
	if (p != NULL) context[@"kCGImagePropertyPNGCompressionFilter"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGCompressionFilter inContext: context];
	p = (void*) &kCGImagePropertyMakerCanonLensModel;
	if (p != NULL) context[@"kCGImagePropertyMakerCanonLensModel"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerCanonLensModel inContext: context];
	p = (void*) &kCGImagePropertyCIFFSelfTimingTime;
	if (p != NULL) context[@"kCGImagePropertyCIFFSelfTimingTime"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFSelfTimingTime inContext: context];
	p = (void*) &kCGImagePropertyProfileName;
	if (p != NULL) context[@"kCGImagePropertyProfileName"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyProfileName inContext: context];
	p = (void*) &kCGImagePropertyExifExposureBiasValue;
	if (p != NULL) context[@"kCGImagePropertyExifExposureBiasValue"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifExposureBiasValue inContext: context];
	p = (void*) &kCGImagePropertyPNGTitle;
	if (p != NULL) context[@"kCGImagePropertyPNGTitle"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGTitle inContext: context];
	p = (void*) &kCGImagePropertyColorModelLab;
	if (p != NULL) context[@"kCGImagePropertyColorModelLab"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyColorModelLab inContext: context];
	p = (void*) &kCGImagePropertyJFIFIsProgressive;
	if (p != NULL) context[@"kCGImagePropertyJFIFIsProgressive"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyJFIFIsProgressive inContext: context];
	p = (void*) &kCGImagePropertyExifContrast;
	if (p != NULL) context[@"kCGImagePropertyExifContrast"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifContrast inContext: context];
	p = (void*) &kCGImagePropertyExifMeteringMode;
	if (p != NULL) context[@"kCGImagePropertyExifMeteringMode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifMeteringMode inContext: context];
	p = (void*) &kCGImagePropertyDNGAsShotWhiteXY;
	if (p != NULL) context[@"kCGImagePropertyDNGAsShotWhiteXY"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGAsShotWhiteXY inContext: context];
	p = (void*) &kCGImagePropertyWidth;
	if (p != NULL) context[@"kCGImagePropertyWidth"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyWidth inContext: context];
	p = (void*) &kCGImagePropertyIPTCEditStatus;
	if (p != NULL) context[@"kCGImagePropertyIPTCEditStatus"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCEditStatus inContext: context];
	p = (void*) &kCGImagePropertyDNGAsShotNeutral;
	if (p != NULL) context[@"kCGImagePropertyDNGAsShotNeutral"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGAsShotNeutral inContext: context];
	p = (void*) &kCGImagePropertyExifSpectralSensitivity;
	if (p != NULL) context[@"kCGImagePropertyExifSpectralSensitivity"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSpectralSensitivity inContext: context];
	p = (void*) &kCGImagePropertyColorModelCMYK;
	if (p != NULL) context[@"kCGImagePropertyColorModelCMYK"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyColorModelCMYK inContext: context];
	p = (void*) &kCGImagePropertyPNGModificationTime;
	if (p != NULL) context[@"kCGImagePropertyPNGModificationTime"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGModificationTime inContext: context];
	p = (void*) &kCGImageAuxiliaryDataInfoMetadata;
	if (p != NULL) context[@"kCGImageAuxiliaryDataInfoMetadata"] = [JSValue valueWithObject: (__bridge id) kCGImageAuxiliaryDataInfoMetadata inContext: context];
	p = (void*) &kCGImagePropertyExifStandardOutputSensitivity;
	if (p != NULL) context[@"kCGImagePropertyExifStandardOutputSensitivity"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifStandardOutputSensitivity inContext: context];
	p = (void*) &kCGImagePropertyExifShutterSpeedValue;
	if (p != NULL) context[@"kCGImagePropertyExifShutterSpeedValue"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifShutterSpeedValue inContext: context];
	p = (void*) &kCGImagePropertyTIFFPrimaryChromaticities;
	if (p != NULL) context[@"kCGImagePropertyTIFFPrimaryChromaticities"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFPrimaryChromaticities inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonDictionary;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonDictionary inContext: context];
	p = (void*) &kCGImagePropertyIPTCCredit;
	if (p != NULL) context[@"kCGImagePropertyIPTCCredit"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCCredit inContext: context];
	p = (void*) &kCGImagePropertyIPTCReferenceService;
	if (p != NULL) context[@"kCGImagePropertyIPTCReferenceService"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCReferenceService inContext: context];
	p = (void*) &kCGImagePropertyGPSMapDatum;
	if (p != NULL) context[@"kCGImagePropertyGPSMapDatum"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSMapDatum inContext: context];
	p = (void*) &kCGImagePropertyIPTCCity;
	if (p != NULL) context[@"kCGImagePropertyIPTCCity"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCCity inContext: context];
	p = (void*) &kCGImagePropertyIPTCActionAdvised;
	if (p != NULL) context[@"kCGImagePropertyIPTCActionAdvised"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCActionAdvised inContext: context];
	p = (void*) &kCGImagePropertyTIFFDocumentName;
	if (p != NULL) context[@"kCGImagePropertyTIFFDocumentName"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFDocumentName inContext: context];
	p = (void*) &kCGImagePropertyGPSStatus;
	if (p != NULL) context[@"kCGImagePropertyGPSStatus"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSStatus inContext: context];
	p = (void*) &kCGImagePropertyDPIHeight;
	if (p != NULL) context[@"kCGImagePropertyDPIHeight"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDPIHeight inContext: context];
	p = (void*) &kCGImagePropertyExifSubjectDistance;
	if (p != NULL) context[@"kCGImagePropertyExifSubjectDistance"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSubjectDistance inContext: context];
	p = (void*) &kCGImagePropertyExifPixelXDimension;
	if (p != NULL) context[@"kCGImagePropertyExifPixelXDimension"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifPixelXDimension inContext: context];
	p = (void*) &kCGImagePropertyExifBrightnessValue;
	if (p != NULL) context[@"kCGImagePropertyExifBrightnessValue"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifBrightnessValue inContext: context];
	p = (void*) &kCGImagePropertyPNGDescription;
	if (p != NULL) context[@"kCGImagePropertyPNGDescription"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGDescription inContext: context];
	p = (void*) &kCGImagePropertyPNGsRGBIntent;
	if (p != NULL) context[@"kCGImagePropertyPNGsRGBIntent"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGsRGBIntent inContext: context];
	p = (void*) &kCGImagePropertyExifFileSource;
	if (p != NULL) context[@"kCGImagePropertyExifFileSource"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifFileSource inContext: context];
	p = (void*) &kCGImagePropertyPNGSoftware;
	if (p != NULL) context[@"kCGImagePropertyPNGSoftware"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGSoftware inContext: context];
	p = (void*) &kCGImagePropertyExifCFAPattern;
	if (p != NULL) context[@"kCGImagePropertyExifCFAPattern"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifCFAPattern inContext: context];
	p = (void*) &kCGImagePropertyDNGBaselineNoise;
	if (p != NULL) context[@"kCGImagePropertyDNGBaselineNoise"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGBaselineNoise inContext: context];
	p = (void*) &kCGImagePropertyCIFFFlashExposureComp;
	if (p != NULL) context[@"kCGImagePropertyCIFFFlashExposureComp"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFFlashExposureComp inContext: context];
	p = (void*) &kCGImagePropertyExifRecommendedExposureIndex;
	if (p != NULL) context[@"kCGImagePropertyExifRecommendedExposureIndex"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifRecommendedExposureIndex inContext: context];
	p = (void*) &kCGImagePropertyExifOECF;
	if (p != NULL) context[@"kCGImagePropertyExifOECF"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifOECF inContext: context];
	p = (void*) &kCGImageProperty8BIMLayerNames;
	if (p != NULL) context[@"kCGImageProperty8BIMLayerNames"] = [JSValue valueWithObject: (__bridge id) kCGImageProperty8BIMLayerNames inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonWhiteBalanceMode;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonWhiteBalanceMode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonWhiteBalanceMode inContext: context];
	p = (void*) &kCGImagePropertyGIFImageColorMap;
	if (p != NULL) context[@"kCGImagePropertyGIFImageColorMap"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGIFImageColorMap inContext: context];
	p = (void*) &kCGImagePropertyPNGChromaticities;
	if (p != NULL) context[@"kCGImagePropertyPNGChromaticities"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGChromaticities inContext: context];
	p = (void*) &kCGImagePropertyGPSAltitudeRef;
	if (p != NULL) context[@"kCGImagePropertyGPSAltitudeRef"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSAltitudeRef inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonColorMode;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonColorMode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonColorMode inContext: context];
	p = (void*) &kCGImagePropertyGPSLatitudeRef;
	if (p != NULL) context[@"kCGImagePropertyGPSLatitudeRef"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSLatitudeRef inContext: context];
	p = (void*) &kCGImagePropertyGPSDifferental;
	if (p != NULL) context[@"kCGImagePropertyGPSDifferental"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDifferental inContext: context];
	p = (void*) &kCGImagePropertyTIFFModel;
	if (p != NULL) context[@"kCGImagePropertyTIFFModel"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFModel inContext: context];
	p = (void*) &kCGImagePropertyExifCompressedBitsPerPixel;
	if (p != NULL) context[@"kCGImagePropertyExifCompressedBitsPerPixel"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifCompressedBitsPerPixel inContext: context];
	p = (void*) &kCGImagePropertyDNGBaselineExposure;
	if (p != NULL) context[@"kCGImagePropertyDNGBaselineExposure"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGBaselineExposure inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonQuality;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonQuality"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonQuality inContext: context];
	p = (void*) &kCGImagePropertyDNGBaselineSharpness;
	if (p != NULL) context[@"kCGImagePropertyDNGBaselineSharpness"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGBaselineSharpness inContext: context];
	p = (void*) &kCGImagePropertyCIFFLensMinMM;
	if (p != NULL) context[@"kCGImagePropertyCIFFLensMinMM"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFLensMinMM inContext: context];
	p = (void*) &kCGImagePropertyIPTCExpirationTime;
	if (p != NULL) context[@"kCGImagePropertyIPTCExpirationTime"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCExpirationTime inContext: context];
	p = (void*) &kCGImagePropertyIPTCReleaseDate;
	if (p != NULL) context[@"kCGImagePropertyIPTCReleaseDate"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCReleaseDate inContext: context];
	p = (void*) &kCGImagePropertyTIFFWhitePoint;
	if (p != NULL) context[@"kCGImagePropertyTIFFWhitePoint"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFWhitePoint inContext: context];
	p = (void*) &kCGImagePropertyDNGCameraCalibration1;
	if (p != NULL) context[@"kCGImagePropertyDNGCameraCalibration1"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGCameraCalibration1 inContext: context];
	p = (void*) &kCGImagePropertyExifISOSpeedLatitudeyyy;
	if (p != NULL) context[@"kCGImagePropertyExifISOSpeedLatitudeyyy"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifISOSpeedLatitudeyyy inContext: context];
	p = (void*) &kCGImagePropertyExifFocalPlaneXResolution;
	if (p != NULL) context[@"kCGImagePropertyExifFocalPlaneXResolution"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifFocalPlaneXResolution inContext: context];
	p = (void*) &kCGImagePropertyDNGFixVignetteRadial;
	if (p != NULL) context[@"kCGImagePropertyDNGFixVignetteRadial"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGFixVignetteRadial inContext: context];
	p = (void*) &kCGImagePropertyIPTCReferenceNumber;
	if (p != NULL) context[@"kCGImagePropertyIPTCReferenceNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCReferenceNumber inContext: context];
	p = (void*) &kCGImagePropertyImages;
	if (p != NULL) context[@"kCGImagePropertyImages"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyImages inContext: context];
	p = (void*) &kCGImagePropertyDPIWidth;
	if (p != NULL) context[@"kCGImagePropertyDPIWidth"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDPIWidth inContext: context];
	p = (void*) &kCGImagePropertyTIFFCopyright;
	if (p != NULL) context[@"kCGImagePropertyTIFFCopyright"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFCopyright inContext: context];
	p = (void*) &kCGImageAuxiliaryDataInfoData;
	if (p != NULL) context[@"kCGImageAuxiliaryDataInfoData"] = [JSValue valueWithObject: (__bridge id) kCGImageAuxiliaryDataInfoData inContext: context];
	p = (void*) &kCGImagePropertyIPTCSource;
	if (p != NULL) context[@"kCGImagePropertyIPTCSource"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCSource inContext: context];
	p = (void*) &kCGImagePropertyCIFFImageName;
	if (p != NULL) context[@"kCGImagePropertyCIFFImageName"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFImageName inContext: context];
	p = (void*) &kCGImagePropertyTIFFTileLength;
	if (p != NULL) context[@"kCGImagePropertyTIFFTileLength"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFTileLength inContext: context];
	p = (void*) &kCGImagePropertyTIFFDictionary;
	if (p != NULL) context[@"kCGImagePropertyTIFFDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFDictionary inContext: context];
	p = (void*) &kCGImagePropertyCIFFMeteringMode;
	if (p != NULL) context[@"kCGImagePropertyCIFFMeteringMode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFMeteringMode inContext: context];
	p = (void*) &kCGImagePropertyTIFFResolutionUnit;
	if (p != NULL) context[@"kCGImagePropertyTIFFResolutionUnit"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFResolutionUnit inContext: context];
	p = (void*) &kCGImagePropertyExifCustomRendered;
	if (p != NULL) context[@"kCGImagePropertyExifCustomRendered"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifCustomRendered inContext: context];
	p = (void*) &kCGImagePropertyGIFLoopCount;
	if (p != NULL) context[@"kCGImagePropertyGIFLoopCount"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGIFLoopCount inContext: context];
	p = (void*) &kCGImagePropertyMakerCanonCameraSerialNumber;
	if (p != NULL) context[@"kCGImagePropertyMakerCanonCameraSerialNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerCanonCameraSerialNumber inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonFocusDistance;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonFocusDistance"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonFocusDistance inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonCameraSerialNumber;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonCameraSerialNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonCameraSerialNumber inContext: context];
	p = (void*) &kCGImagePropertyIPTCDigitalCreationDate;
	if (p != NULL) context[@"kCGImagePropertyIPTCDigitalCreationDate"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCDigitalCreationDate inContext: context];
	p = (void*) &kCGImagePropertyGPSDestBearingRef;
	if (p != NULL) context[@"kCGImagePropertyGPSDestBearingRef"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDestBearingRef inContext: context];
	p = (void*) &kCGImagePropertyDNGUniqueCameraModel;
	if (p != NULL) context[@"kCGImagePropertyDNGUniqueCameraModel"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGUniqueCameraModel inContext: context];
	p = (void*) &kCGImagePropertyTIFFXResolution;
	if (p != NULL) context[@"kCGImagePropertyTIFFXResolution"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFXResolution inContext: context];
	p = (void*) &kCGImagePropertyTIFFHostComputer;
	if (p != NULL) context[@"kCGImagePropertyTIFFHostComputer"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFHostComputer inContext: context];
	p = (void*) &kCGImagePropertyExifBodySerialNumber;
	if (p != NULL) context[@"kCGImagePropertyExifBodySerialNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifBodySerialNumber inContext: context];
	p = (void*) &kCGImagePropertyGIFDelayTime;
	if (p != NULL) context[@"kCGImagePropertyGIFDelayTime"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGIFDelayTime inContext: context];
	p = (void*) &kCGImagePropertyCIFFFocusMode;
	if (p != NULL) context[@"kCGImagePropertyCIFFFocusMode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFFocusMode inContext: context];
	p = (void*) &kCGImagePropertyExifRelatedSoundFile;
	if (p != NULL) context[@"kCGImagePropertyExifRelatedSoundFile"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifRelatedSoundFile inContext: context];
	p = (void*) &kCGImagePropertyIPTCObjectName;
	if (p != NULL) context[@"kCGImagePropertyIPTCObjectName"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCObjectName inContext: context];
	p = (void*) &kCGImagePropertyIPTCScene;
	if (p != NULL) context[@"kCGImagePropertyIPTCScene"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCScene inContext: context];
	p = (void*) &kCGImagePropertyIPTCOriginatingProgram;
	if (p != NULL) context[@"kCGImagePropertyIPTCOriginatingProgram"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCOriginatingProgram inContext: context];
	p = (void*) &kCGImagePropertyExifSubjectArea;
	if (p != NULL) context[@"kCGImagePropertyExifSubjectArea"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSubjectArea inContext: context];
	p = (void*) &kCGImagePropertyDNGColorMatrix1;
	if (p != NULL) context[@"kCGImagePropertyDNGColorMatrix1"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGColorMatrix1 inContext: context];
	p = (void*) &kCGImagePropertyIsFloat;
	if (p != NULL) context[@"kCGImagePropertyIsFloat"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIsFloat inContext: context];
	p = (void*) &kCGImagePropertyExifSharpness;
	if (p != NULL) context[@"kCGImagePropertyExifSharpness"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSharpness inContext: context];
	p = (void*) &kCGImagePropertyAuxiliaryDataType;
	if (p != NULL) context[@"kCGImagePropertyAuxiliaryDataType"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyAuxiliaryDataType inContext: context];
	p = (void*) &kCGImagePropertyExifSensingMethod;
	if (p != NULL) context[@"kCGImagePropertyExifSensingMethod"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSensingMethod inContext: context];
	p = (void*) &kCGImagePropertyGPSDestBearing;
	if (p != NULL) context[@"kCGImagePropertyGPSDestBearing"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDestBearing inContext: context];
	p = (void*) &kCGImagePropertyDNGWhiteLevel;
	if (p != NULL) context[@"kCGImagePropertyDNGWhiteLevel"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGWhiteLevel inContext: context];
	p = (void*) &kCGImagePropertyExifLensMake;
	if (p != NULL) context[@"kCGImagePropertyExifLensMake"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifLensMake inContext: context];
	p = (void*) &kCGImagePropertyDNGPrivateData;
	if (p != NULL) context[@"kCGImagePropertyDNGPrivateData"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGPrivateData inContext: context];
	p = (void*) &kCGImagePropertyIPTCReferenceDate;
	if (p != NULL) context[@"kCGImagePropertyIPTCReferenceDate"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCReferenceDate inContext: context];
	p = (void*) &kCGImagePropertyPNGYPixelsPerMeter;
	if (p != NULL) context[@"kCGImagePropertyPNGYPixelsPerMeter"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGYPixelsPerMeter inContext: context];
	p = (void*) &kCGImagePropertyGPSDestLongitude;
	if (p != NULL) context[@"kCGImagePropertyGPSDestLongitude"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDestLongitude inContext: context];
	p = (void*) &kCGImagePropertyIPTCCountryPrimaryLocationCode;
	if (p != NULL) context[@"kCGImagePropertyIPTCCountryPrimaryLocationCode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCCountryPrimaryLocationCode inContext: context];
	p = (void*) &kCGImagePropertyExifAuxFirmware;
	if (p != NULL) context[@"kCGImagePropertyExifAuxFirmware"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifAuxFirmware inContext: context];
	p = (void*) &kCGImagePropertyJFIFDensityUnit;
	if (p != NULL) context[@"kCGImagePropertyJFIFDensityUnit"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyJFIFDensityUnit inContext: context];
	p = (void*) &kCGImagePropertyTIFFOrientation;
	if (p != NULL) context[@"kCGImagePropertyTIFFOrientation"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFOrientation inContext: context];
	p = (void*) &kCGImagePropertyIPTCContactInfoCity;
	if (p != NULL) context[@"kCGImagePropertyIPTCContactInfoCity"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCContactInfoCity inContext: context];
	p = (void*) &kCGImagePropertyMakerCanonContinuousDrive;
	if (p != NULL) context[@"kCGImagePropertyMakerCanonContinuousDrive"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerCanonContinuousDrive inContext: context];
	p = (void*) &kCGImagePropertyMakerCanonImageSerialNumber;
	if (p != NULL) context[@"kCGImagePropertyMakerCanonImageSerialNumber"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerCanonImageSerialNumber inContext: context];
	p = (void*) &kCGImagePropertyExifUserComment;
	if (p != NULL) context[@"kCGImagePropertyExifUserComment"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifUserComment inContext: context];
	p = (void*) &kCGImagePropertyIPTCCopyrightNotice;
	if (p != NULL) context[@"kCGImagePropertyIPTCCopyrightNotice"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCCopyrightNotice inContext: context];
	p = (void*) &kCGImagePropertyTIFFSoftware;
	if (p != NULL) context[@"kCGImagePropertyTIFFSoftware"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFSoftware inContext: context];
	p = (void*) &kCGImagePropertyExifDateTimeOriginal;
	if (p != NULL) context[@"kCGImagePropertyExifDateTimeOriginal"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifDateTimeOriginal inContext: context];
	p = (void*) &kCGImagePropertyPNGXPixelsPerMeter;
	if (p != NULL) context[@"kCGImagePropertyPNGXPixelsPerMeter"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGXPixelsPerMeter inContext: context];
	p = (void*) &kCGImagePropertyIPTCDigitalCreationTime;
	if (p != NULL) context[@"kCGImagePropertyIPTCDigitalCreationTime"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCDigitalCreationTime inContext: context];
	p = (void*) &kCGImagePropertyCIFFDictionary;
	if (p != NULL) context[@"kCGImagePropertyCIFFDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFDictionary inContext: context];
	p = (void*) &kCGImagePropertyIPTCSubjectReference;
	if (p != NULL) context[@"kCGImagePropertyIPTCSubjectReference"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCSubjectReference inContext: context];
	p = (void*) &kCGImagePropertyTIFFPhotometricInterpretation;
	if (p != NULL) context[@"kCGImagePropertyTIFFPhotometricInterpretation"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFPhotometricInterpretation inContext: context];
	p = (void*) &kCGImagePropertyIPTCImageType;
	if (p != NULL) context[@"kCGImagePropertyIPTCImageType"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCImageType inContext: context];
	p = (void*) &kCGImagePropertyGPSLongitudeRef;
	if (p != NULL) context[@"kCGImagePropertyGPSLongitudeRef"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSLongitudeRef inContext: context];
	p = (void*) &kCGImagePropertyMakerCanonAspectRatioInfo;
	if (p != NULL) context[@"kCGImagePropertyMakerCanonAspectRatioInfo"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerCanonAspectRatioInfo inContext: context];
	p = (void*) &kCGImagePropertyGPSDestLatitudeRef;
	if (p != NULL) context[@"kCGImagePropertyGPSDestLatitudeRef"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDestLatitudeRef inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonShutterCount;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonShutterCount"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonShutterCount inContext: context];
	p = (void*) &kCGImagePropertyExifDeviceSettingDescription;
	if (p != NULL) context[@"kCGImagePropertyExifDeviceSettingDescription"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifDeviceSettingDescription inContext: context];
	p = (void*) &kCGImagePropertyNamedColorSpace;
	if (p != NULL) context[@"kCGImagePropertyNamedColorSpace"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyNamedColorSpace inContext: context];
	p = (void*) &kCGImagePropertyIPTCByline;
	if (p != NULL) context[@"kCGImagePropertyIPTCByline"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCByline inContext: context];
	p = (void*) &kCGImagePropertyBytesPerRow;
	if (p != NULL) context[@"kCGImagePropertyBytesPerRow"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyBytesPerRow inContext: context];
	p = (void*) &kCGImagePropertyExifSubjectLocation;
	if (p != NULL) context[@"kCGImagePropertyExifSubjectLocation"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSubjectLocation inContext: context];
	p = (void*) &kCGImagePropertyTIFFYResolution;
	if (p != NULL) context[@"kCGImagePropertyTIFFYResolution"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFYResolution inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonFlashSetting;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonFlashSetting"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonFlashSetting inContext: context];
	p = (void*) &kCGImagePropertyColorModelGray;
	if (p != NULL) context[@"kCGImagePropertyColorModelGray"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyColorModelGray inContext: context];
	p = (void*) &kCGImageAuxiliaryDataTypeDepth;
	if (p != NULL) context[@"kCGImageAuxiliaryDataTypeDepth"] = [JSValue valueWithObject: (__bridge id) kCGImageAuxiliaryDataTypeDepth inContext: context];
	p = (void*) &kCGImagePropertyIsIndexed;
	if (p != NULL) context[@"kCGImagePropertyIsIndexed"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIsIndexed inContext: context];
	p = (void*) &kCGImagePropertyIPTCOriginalTransmissionReference;
	if (p != NULL) context[@"kCGImagePropertyIPTCOriginalTransmissionReference"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCOriginalTransmissionReference inContext: context];
	p = (void*) &kCGImagePropertyGIFDictionary;
	if (p != NULL) context[@"kCGImagePropertyGIFDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGIFDictionary inContext: context];
	p = (void*) &kCGImagePropertyFileSize;
	if (p != NULL) context[@"kCGImagePropertyFileSize"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyFileSize inContext: context];
	p = (void*) &kCGImagePropertyTIFFTransferFunction;
	if (p != NULL) context[@"kCGImagePropertyTIFFTransferFunction"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFTransferFunction inContext: context];
	p = (void*) &kCGImagePropertyIPTCContentLocationName;
	if (p != NULL) context[@"kCGImagePropertyIPTCContentLocationName"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCContentLocationName inContext: context];
	p = (void*) &kCGImagePropertyIPTCSupplementalCategory;
	if (p != NULL) context[@"kCGImagePropertyIPTCSupplementalCategory"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCSupplementalCategory inContext: context];
	p = (void*) &kCGImagePropertyGPSSatellites;
	if (p != NULL) context[@"kCGImagePropertyGPSSatellites"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSSatellites inContext: context];
	p = (void*) &kCGImagePropertyIPTCHeadline;
	if (p != NULL) context[@"kCGImagePropertyIPTCHeadline"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCHeadline inContext: context];
	p = (void*) &kCGImagePropertyPixelWidth;
	if (p != NULL) context[@"kCGImagePropertyPixelWidth"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPixelWidth inContext: context];
	p = (void*) &kCGImagePropertyIPTCContactInfoStateProvince;
	if (p != NULL) context[@"kCGImagePropertyIPTCContactInfoStateProvince"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCContactInfoStateProvince inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonLensAdapter;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonLensAdapter"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonLensAdapter inContext: context];
	p = (void*) &kCGImagePropertyExifExposureTime;
	if (p != NULL) context[@"kCGImagePropertyExifExposureTime"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifExposureTime inContext: context];
	p = (void*) &kCGImagePropertyMakerCanonOwnerName;
	if (p != NULL) context[@"kCGImagePropertyMakerCanonOwnerName"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerCanonOwnerName inContext: context];
	p = (void*) &kCGImagePropertyGPSAltitude;
	if (p != NULL) context[@"kCGImagePropertyGPSAltitude"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSAltitude inContext: context];
	p = (void*) &kCGImagePropertyIPTCTimeCreated;
	if (p != NULL) context[@"kCGImagePropertyIPTCTimeCreated"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCTimeCreated inContext: context];
	p = (void*) &kCGImagePropertyTIFFMake;
	if (p != NULL) context[@"kCGImagePropertyTIFFMake"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyTIFFMake inContext: context];
	p = (void*) &kCGImagePropertyExifPixelYDimension;
	if (p != NULL) context[@"kCGImagePropertyExifPixelYDimension"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifPixelYDimension inContext: context];
	p = (void*) &kCGImagePropertyExifSubjectDistRange;
	if (p != NULL) context[@"kCGImagePropertyExifSubjectDistRange"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSubjectDistRange inContext: context];
	p = (void*) &kCGImagePropertyIPTCKeywords;
	if (p != NULL) context[@"kCGImagePropertyIPTCKeywords"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCKeywords inContext: context];
	p = (void*) &kCGImagePropertyExifColorSpace;
	if (p != NULL) context[@"kCGImagePropertyExifColorSpace"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifColorSpace inContext: context];
	p = (void*) &kCGImagePropertyMakerAppleDictionary;
	if (p != NULL) context[@"kCGImagePropertyMakerAppleDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerAppleDictionary inContext: context];
	p = (void*) &kCGImagePropertyGPSSpeedRef;
	if (p != NULL) context[@"kCGImagePropertyGPSSpeedRef"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSSpeedRef inContext: context];
	p = (void*) &kCGImagePropertyExifSpatialFrequencyResponse;
	if (p != NULL) context[@"kCGImagePropertyExifSpatialFrequencyResponse"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSpatialFrequencyResponse inContext: context];
	p = (void*) &kCGImagePropertyGPSDestDistanceRef;
	if (p != NULL) context[@"kCGImagePropertyGPSDestDistanceRef"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDestDistanceRef inContext: context];
	p = (void*) &kCGImagePropertyDNGCalibrationIlluminant2;
	if (p != NULL) context[@"kCGImagePropertyDNGCalibrationIlluminant2"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGCalibrationIlluminant2 inContext: context];
	p = (void*) &kCGImagePropertyGPSSpeed;
	if (p != NULL) context[@"kCGImagePropertyGPSSpeed"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSSpeed inContext: context];
	p = (void*) &kCGImagePropertyDNGCalibrationIlluminant1;
	if (p != NULL) context[@"kCGImagePropertyDNGCalibrationIlluminant1"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGCalibrationIlluminant1 inContext: context];
	p = (void*) &kCGImagePropertyCIFFLensModel;
	if (p != NULL) context[@"kCGImagePropertyCIFFLensModel"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFLensModel inContext: context];
	p = (void*) &kCGImagePropertyCIFFReleaseMethod;
	if (p != NULL) context[@"kCGImagePropertyCIFFReleaseMethod"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFReleaseMethod inContext: context];
	p = (void*) &kCGImagePropertyJFIFXDensity;
	if (p != NULL) context[@"kCGImagePropertyJFIFXDensity"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyJFIFXDensity inContext: context];
	p = (void*) &kCGImagePropertyDNGBlackLevel;
	if (p != NULL) context[@"kCGImagePropertyDNGBlackLevel"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGBlackLevel inContext: context];
	p = (void*) &kCGImagePropertyGPSAreaInformation;
	if (p != NULL) context[@"kCGImagePropertyGPSAreaInformation"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSAreaInformation inContext: context];
	p = (void*) &kCGImagePropertyIPTCProgramVersion;
	if (p != NULL) context[@"kCGImagePropertyIPTCProgramVersion"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCProgramVersion inContext: context];
	p = (void*) &kCGImagePropertyIPTCExpirationDate;
	if (p != NULL) context[@"kCGImagePropertyIPTCExpirationDate"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCExpirationDate inContext: context];
	p = (void*) &kCGImagePropertyExifDictionary;
	if (p != NULL) context[@"kCGImagePropertyExifDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifDictionary inContext: context];
	p = (void*) &kCGImagePropertyCIFFContinuousDrive;
	if (p != NULL) context[@"kCGImagePropertyCIFFContinuousDrive"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFContinuousDrive inContext: context];
	p = (void*) &kCGImagePropertyDNGCameraCalibrationSignature;
	if (p != NULL) context[@"kCGImagePropertyDNGCameraCalibrationSignature"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyDNGCameraCalibrationSignature inContext: context];
	p = (void*) &kCGImagePropertyExifFocalLength;
	if (p != NULL) context[@"kCGImagePropertyExifFocalLength"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifFocalLength inContext: context];
	p = (void*) &kCGImagePropertyIPTCDateCreated;
	if (p != NULL) context[@"kCGImagePropertyIPTCDateCreated"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCDateCreated inContext: context];
	p = (void*) &kCGImagePropertyExifSceneType;
	if (p != NULL) context[@"kCGImagePropertyExifSceneType"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSceneType inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonImageAdjustment;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonImageAdjustment"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonImageAdjustment inContext: context];
	p = (void*) &kCGImagePropertyExifSubsecTimeDigitized;
	if (p != NULL) context[@"kCGImagePropertyExifSubsecTimeDigitized"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyExifSubsecTimeDigitized inContext: context];
	p = (void*) &kCGImagePropertyImageCount;
	if (p != NULL) context[@"kCGImagePropertyImageCount"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyImageCount inContext: context];
	p = (void*) &kCGImageProperty8BIMDictionary;
	if (p != NULL) context[@"kCGImageProperty8BIMDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImageProperty8BIMDictionary inContext: context];
	p = (void*) &kCGImagePropertyGPSTrack;
	if (p != NULL) context[@"kCGImagePropertyGPSTrack"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSTrack inContext: context];
	p = (void*) &kCGImagePropertyMakerNikonISOSetting;
	if (p != NULL) context[@"kCGImagePropertyMakerNikonISOSetting"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerNikonISOSetting inContext: context];
	p = (void*) &kCGImagePropertyIPTCFixtureIdentifier;
	if (p != NULL) context[@"kCGImagePropertyIPTCFixtureIdentifier"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyIPTCFixtureIdentifier inContext: context];
	p = (void*) &kCGImagePropertyRawDictionary;
	if (p != NULL) context[@"kCGImagePropertyRawDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyRawDictionary inContext: context];
	p = (void*) &kCGImagePropertyMakerCanonFlashExposureComp;
	if (p != NULL) context[@"kCGImagePropertyMakerCanonFlashExposureComp"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyMakerCanonFlashExposureComp inContext: context];
	p = (void*) &kCGImagePropertyGPSDestDistance;
	if (p != NULL) context[@"kCGImagePropertyGPSDestDistance"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyGPSDestDistance inContext: context];
	p = (void*) &kCGImagePropertyOrientation;
	if (p != NULL) context[@"kCGImagePropertyOrientation"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyOrientation inContext: context];
	p = (void*) &kCGImagePropertyCIFFShootingMode;
	if (p != NULL) context[@"kCGImagePropertyCIFFShootingMode"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyCIFFShootingMode inContext: context];
	p = (void*) &kCGImagePropertyPNGDictionary;
	if (p != NULL) context[@"kCGImagePropertyPNGDictionary"] = [JSValue valueWithObject: (__bridge id) kCGImagePropertyPNGDictionary inContext: context];
}
void load_ImageIO_CGImageProperties_symbols(JSContext* context)
{
    addProtocols();
    registerEnumConstants(context);
    registerCFunctions(context);
    registerGlobalConstants(context);
}
#pragma clang diagnostic pop
