#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
#ifndef BUTTON_SWIFT_H
#define BUTTON_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreComponent;
@import CoreFoundation;
@import CoreGraphics;
@import Foundation;
@import NetworkComponent;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Button",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;
@class CallBack;
@class RawBytes;
@class UIImage;
@class KonyImage;
@class NSObject;
@class Widget;
@class LayoutModel;

SWIFT_CLASS_NAMED("ButtonModel")
@interface ButtonModel : WidgetModel
@property (nonatomic, copy) NSString * _Nullable text;
@property (nonatomic) BOOL displayText;
@property (nonatomic, copy) NSString * _Nullable normalImage;
@property (nonatomic, copy) NSString * _Nullable focusImage;
@property (nonatomic, copy) NSString * _Nullable highlightedImage;
@property (nonatomic) id _Nullable nativeButtonNormalImage;
@property (nonatomic) id _Nullable nativeButtonFocusImage;
@property (nonatomic, strong) CallBack * _Nullable onClick;
@property (nonatomic, copy) NSString * _Nullable focusSkinID;
@property (nonatomic, copy) NSString * _Nullable highlightedSkinID;
@property (nonatomic) BOOL showProgressIndicator;
@property (nonatomic, copy) NSString * _Nullable progressIndicatorColor;
@property (nonatomic) BOOL glowEffect;
@property (nonatomic, strong) RawBytes * _Nullable rawData;
@property (nonatomic) KonyWidgetContentAlignment contentAlignment;
@property (nonatomic, strong) UIImage * _Nullable rawBytesImage;
@property (nonatomic) KonyTextWrap wrapping;
@property (nonatomic, strong) KonyImage * _Nullable konyImage;
@property (nonatomic) KonyButtonType buttonType;
@property (nonatomic, copy) NSDictionary * _Nullable cacheConfig;
- (Widget * _Null_unspecified)createWidget SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
- (void)updateLayoutDefaultsFor:(LayoutModel * _Nullable)aLayoutModel;
@end


/// creates a Button Widget
SWIFT_CLASS_NAMED("ButtonProxy")
@interface ButtonProxy : BaseProxy
+ (id _Nullable)createWidget:(NSDictionary * _Nullable)config SWIFT_WARN_UNUSED_RESULT;
- (void)setValue:(id _Nullable)value forUndefinedKey:(NSString * _Nonnull)key;
- (null_unspecified instancetype)initWithModel:(WidgetModel * _Null_unspecified)model OBJC_DESIGNATED_INITIALIZER;
- (null_unspecified instancetype)initWithModel:(WidgetModel * _Null_unspecified)aModel andConfig:(NSDictionary * _Null_unspecified)config OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIColor;
@class Shadows;
@class SkinModel;

SWIFT_CLASS_NAMED("ButtonSkin")
@interface ButtonSkin : Skin
@property (nonatomic) BOOL useNative;
@property (nonatomic, strong) UIColor * _Nullable shadowColor;
@property (nonatomic) NSInteger shadowXOffset;
@property (nonatomic) NSInteger shadowYOffset;
@property (nonatomic, strong) Shadows * _Nullable textShadow;
@property (nonatomic, copy) NSDictionary * _Nullable tintConfig;
+ (Skin * _Null_unspecified)defaultSkin SWIFT_WARN_UNUSED_RESULT;
+ (void)registerFactory:(id _Nullable)aClass forType:(KonyWidgetType)aWidgetType;
+ (BOOL)skinmodelRegistration SWIFT_WARN_UNUSED_RESULT;
+ (Skin * _Null_unspecified)defaultSkinOfType:(NSString * _Null_unspecified)aSkinType SWIFT_WARN_UNUSED_RESULT;
- (void)updateTextShadowForSkin:(NSDictionary * _Nonnull)textShadow;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (null_unspecified instancetype)initWithModel:(SkinModel * _Null_unspecified)aSkinModel OBJC_DESIGNATED_INITIALIZER;
@end

@class ShadowsModel;

SWIFT_CLASS_NAMED("ButtonSkinModel")
@interface ButtonSkinModel : SkinModel
@property (nonatomic) BOOL useNative;
@property (nonatomic) NSInteger shadowColor;
@property (nonatomic) NSInteger shadowXOffset;
@property (nonatomic) NSInteger shadowYOffset;
@property (nonatomic, strong) ShadowsModel * _Nullable textShadow;
@property (nonatomic, copy) NSDictionary * _Nullable tintConfig;
+ (SkinModel * _Null_unspecified)defaultModel SWIFT_WARN_UNUSED_RESULT;
+ (void)registerFactory:(id _Null_unspecified)aClass forType:(KonyWidgetType)aWidgetType;
+ (void)widgetRegistration;
- (nonnull instancetype)initWithIdentifier:(NSString * _Nonnull)aIdentifier SWIFT_UNAVAILABLE;
+ (void)propertyRegistration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UIView;
@class NSData;
@class NSURLResponse;

SWIFT_CLASS_NAMED("ButtonWidget")
@interface ButtonWidget : Widget <KonyHighlightProtocol, ViewDrawingDelegate, KonyHttpRequestDelegate>
- (null_unspecified instancetype)initWithModel:(WidgetModel * _Nonnull)model OBJC_DESIGNATED_INITIALIZER;
- (void)setupWidget;
@property (nonatomic, strong) UIView * _Null_unspecified view;
- (void)setWidgetViewFrame:(CGRect)frame;
- (CGSize)getPreferredSizeForGivenSize:(CGSize)givenSize SWIFT_WARN_UNUSED_RESULT;
- (void)progressIndicatorColorUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)textUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)displayTextUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)normalImageUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)focusImageUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)rawDataUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)konyImageUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)skinIdentifierUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)nativeButtonNormalImageUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)nativeButtonFocusImageUpdatedWithNewValue:(id _Nonnull)newValue oldValue:(id _Nonnull)oldValue;
- (void)focusSkinIDUpdatedWithNewValue:(id _Nonnull)newValue oldValue:(id _Nonnull)oldValue;
- (void)contentAlignmentUpdatedWithNewValue:(id _Nonnull)newValue oldValue:(id _Nonnull)oldValue;
- (void)wrappingUpdatedWithNewValue:(id _Nonnull)newValue oldValue:(id _Nonnull)oldValue;
- (BOOL)isDefaultAccessibilityElement SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isAccessibilitySupported SWIFT_WARN_UNUSED_RESULT;
- (void)updateAccessibilityConfiguration;
- (void)action;
- (void)updateWidgetHighlight:(BOOL)value recursive:(BOOL)isRecursive;
- (void)drawView:(UIView * _Nonnull)view withContext:(CGContextRef _Nonnull)context inRect:(CGRect)rect;
- (Skin * _Nullable)getNormalSkin SWIFT_WARN_UNUSED_RESULT;
- (void)fontColorUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)fontSizeUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)fontFamilyUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)textShadowColorUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)textShadowRadiusUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)textShadowOffsetUpdatedWithNewValue:(id _Nullable)newValue oldValue:(id _Nullable)oldValue;
- (void)setHighlighted:(BOOL)shouldHighlight;
- (void)dataTaskReceivedData:(NSData * _Nonnull)data;
- (NSURLCacheStoragePolicy)getCacheStoragePolicy SWIFT_WARN_UNUSED_RESULT;
- (void)dataTaskStartedReceivingReponse:(NSURLResponse * _Nonnull)response_ withCompletionHandler:(void (^ _Nullable)(NSURLSessionResponseDisposition))completionHandler;
- (void)dataTaskcompletedWithError:(NSError * _Nullable)error;
- (void)willExecuteCallBack:(CallBack * _Null_unspecified)aCallBack;
- (void)didExecuteCallBack:(CallBack * _Nonnull)aCallBack;
- (void)reloadSkins;
- (void)reloadWidget;
- (void)updateFontAndLayoutSubWidgets;
- (void)updateAccessibilityTrait;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Proxy object which we will registering as “Button” to the Javscript world
SWIFT_CLASS_NAMED("JSButton")
@interface JSButton : JSWidget
- (nonnull instancetype)initWithArguments:(NSArray * _Nonnull)arguments SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
+ (NSSet * _Nullable)methods SWIFT_WARN_UNUSED_RESULT;
+ (KonyWidgetType)supportedWidgetType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS_NAMED("JSLink")
@interface JSLink : JSWidget
- (nonnull instancetype)initWithArguments:(NSArray * _Nonnull)arguments SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithValue:(id _Nonnull)value OBJC_DESIGNATED_INITIALIZER;
+ (NSString * _Nonnull)className SWIFT_WARN_UNUSED_RESULT;
+ (NSSet * _Nullable)methods SWIFT_WARN_UNUSED_RESULT;
+ (KonyWidgetType)supportedWidgetType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSCoder;
@class UITouch;
@class UIEvent;
@class UIFont;

SWIFT_CLASS_NAMED("KonyCustomButtonBase")
@interface KonyCustomButtonBase : UIButton
@property (nonatomic, weak) id <ViewDrawingDelegate> _Nullable drawingDelegate;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (CGRect)titleRectForContentRect:(CGRect)contentRect SWIFT_WARN_UNUSED_RESULT;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesMoved:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesCancelled:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
- (void)touchesEnded:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
+ (CGSize)suggestSizeForText:(NSString * _Nonnull)text with:(UIFont * _Nonnull)font forWidth:(float)width lineBreakMode:(KonyTextWrap)lineBreakMode SWIFT_WARN_UNUSED_RESULT;
- (void)applySkin:(ButtonSkin * _Nullable)aSkin;
@end


SWIFT_CLASS_NAMED("KonyCustomButtonWithDrawing")
@interface KonyCustomButtonWithDrawing : KonyCustomButtonBase
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("KonyCustomButtonWithLayer")
@interface KonyCustomButtonWithLayer : KonyCustomButtonBase
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (void)applySkin:(ButtonSkin * _Null_unspecified)aSkin;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("LinkModel")
@interface LinkModel : ButtonModel
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
