#import <JavaScriptCore/JavaScriptCore.h>
#import "allheaders.h"
#import "allprotos.h"
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wobjc-property-no-attribute"
#pragma clang diagnostic ignored "-Wnullability-completeness"
void load_UIKit_UIAccessibilityContentSizeCategoryImageAdjusting_symbols(JSContext*);
@protocol UIImageViewUIAccessibilityContentSizeCategoryImageAdjustingCategoryInstanceExports<JSExport, UIAccessibilityContentSizeCategoryImageAdjustingInstanceExports_>
@end
@protocol UIImageViewUIAccessibilityContentSizeCategoryImageAdjustingCategoryClassExports<JSExport, UIAccessibilityContentSizeCategoryImageAdjustingClassExports_>
@end
@protocol NSTextAttachmentUIAccessibilityContentSizeCategoryImageAdjustingCategoryInstanceExports<JSExport, UIAccessibilityContentSizeCategoryImageAdjustingInstanceExports_>
@end
@protocol NSTextAttachmentUIAccessibilityContentSizeCategoryImageAdjustingCategoryClassExports<JSExport, UIAccessibilityContentSizeCategoryImageAdjustingClassExports_>
@end
@protocol UIButtonUIAccessibilityContentSizeCategoryImageAdjustingCategoryInstanceExports<JSExport, UIAccessibilityContentSizeCategoryImageAdjustingInstanceExports_>
@end
@protocol UIButtonUIAccessibilityContentSizeCategoryImageAdjustingCategoryClassExports<JSExport, UIAccessibilityContentSizeCategoryImageAdjustingClassExports_>
@end
@protocol UIAccessibilityContentSizeCategoryImageAdjustingInstanceExports_<JSExport, NSObjectInstanceExports_>
@property (nonatomic) BOOL adjustsImageSizeForAccessibilityContentSizeCategory;
@end
@protocol UIAccessibilityContentSizeCategoryImageAdjustingClassExports_<JSExport, NSObjectClassExports_>
@end
#pragma clang diagnostic pop